lanl/Draco

ChangeLog
Create some dummy changes to walk through the github workflow and create some documentation.
=> My less-than-cool new code feature is ready.

ChangeLog
=> A test commit with the github model

.travis.yml, README.md
+ The updated README.md is displayed by github and points to the new github wiki.
+ The .travis.yml provides continuous integration checks for pull requests.
=> Merge in changes that were present in the demo github repository.

.clang-format, .travis.yml, regression/check_style.sh, regression/mcovdir.cfg, regression/metrics_report.sh
The metric reporting script needed to be updated to reflect the new regression layout on ccscs7. This script was used to generate the 2016 July 4 report.
=> Metric report updates

config/platform_checks.cmake
=> Disable HAVE_CXX11_ARRAY for PGI compilers.

config/vendor_libraries.cmake
=> Add support for OpenBLAS to satisfy optional LAPACK requirement.

regression/Draco_Win32.cmake, regression/setupvendors.bat, regression/update_regression_dir.bat, regression/win32-regress.bat
+ set/unset USE_GITHUB environment variable from the batch file.
+ Update Draco_Win32.cmake to look more like Draco_Linux64.cmake.
=> Teach win32-specific regression scripts about github.

regression/Draco_Win32.cmake, regression/ccscs-regress.msub, regression/draco_regression_macros.cmake, regression/pull_repositories_xf.sh, regression/push_repositories_xf.sh, regression/sync_repository.sh, regression/update_regression_dir.bat, regression/win32-regress.bat, regression/win32-regression-master.bat
* More changes are required for ml and darwin. I'll merge these later.
* Changes for windows platforms:
* Begin using git intead of svn for checkout out the sources.
* Cleanup code to more closely track the Linux system.
* Change the layout of the regress directory to mirror the structure found on Linux.
* Be aware of DOS-style slashes in paths.
* Changes for ccscs7:
* When running as a cronjob, use a keychain to allow authentication to gitlab.lanl.gov.
* Update the scripts that push copies of the repositories to the red network. Basically, teach the scripts that jayenne is now a git repository.
=> More tweaks to the regression system (targets ccscs7 and sunergos).

src/c4/Functors.hh
* This file is still used by Jayenne. I was overly aggressive when retiring accumulatev.
=> Restore file that is still needed by Jayenne.

src/RTT_Format_Reader/CellDefs.cc, src/RTT_Format_Reader/test/TestRTTPolyhedron.cc, src/RTT_Format_Reader/test/rttpolyhedron.mesh.in
Modifying the test mesh for polyhedron. Removed unnecessary print statements
in CellDefs.cc that were used for debugging.
=> Minor changes RTT format polyhedron mesh.

regression/valgrind_suppress.txt
=> Fix a capitalization error in the suppression file.

environment/bashrc/.bashrc_tt
=> Module use ~/modulefiles/trinitite instead of user_contrib, if avail.

.github/PULL_REQUEST_TEMPLATE, regression/ml-crontab, regression/sync_repository.sh
+ CI should run with the `-r` option.
+ Fix bad path for `regression-master.sh`
+ Update comments.
=> Enable automated continuous integration on trinitite

environment/bashrc/.bashrc_tt, regression/tt-regress.msub
=> Adding hugepages module to Trinitite .bashrc

src/cdi_ipcress/python/example_script.py, src/cdi_ipcress/python/ipcress_reader.py, src/cdi_ipcress/python/plot_ipcress_opacity.py
+ Changing python IPCRESS parsing and plotting to be more library like so it can be more general.
* Replacing bad PR #93 with this PR. (#93 was confused about the branch point and introduced a lot of diffs that shouldn't have existed).
=> Refactor python IPCRESS into multiplie files

CMakeLists.txt, ChangeLog, regression/scripts/common.sh, regression/scripts/release_cray.sh, regression/scripts/release_toss2.sh, src/ds++/Release.cc
* Merge the Draco-6_20_0 branch back to develop.
* If this succeeds, I will also merge the Draco-6_20_0 branch to master.
=> Draco-6_20_0

config/application_unit_test.py
=> Fix Python unit test pgdiff functionality on Trinitite

environment/bashrc/.bashrc, environment/bashrc/.bashrc_toss22, environment/cshrc/.cshrc
=> Mustang and Conejo decommissioned.

src/c4/Invert_Comm_Map.cc, src/c4/Invert_Comm_Map.hh, src/c4/test/tstInvert_Comm_Map.cc
* Improve performance of c4's invert_comm_map.
* Related to jayenne's #784
=> Invert comm map

src/c4/Invert_Comm_Map.hh
* This should fix build failures under visual studio.
=> Provide DLL_PUBLIC decoration for new function.

regression/ccscs-regress.msub, regression/draco_regression_macros.cmake
=> Fix autodoc generation and publication to rtt.lanl.gov/autodoc.

regression/alist.sh, regression/push_repositories_xf.sh, regression/sync_repository.sh
* Rework the `sync_repository.sh` script to eliminate some code duplication.
* Add new section for kicking off regression runs on ccscs7 when a Jayenne PR is created.
=> First cut at ccs-net CI for Jayenne.

src/cdi_ipcress/IpcressFile.hh, src/cdi_ipcress/IpcressMaterial.hh, src/cdi_ipcress/IpcressOdfmgOpacity.hh, src/cdi_ipcress/test/ReadOdfIpcressFile.cc, src/cdi_ipcress/test/cdi_ipcress_test.hh, src/cdi_ipcress/test/tIpcressFile.cc
=> Clean up formatting, include directives, duplicate cpp macros.

autodoc/CMakeLists.txt, autodoc/html/footer.html.in, autodoc/html/header.html.in
=> Cleanup links used in published autodoc (rtt.lanl.gov/autodoc).

config/setupMPI.cmake, regression/scripts/common.sh, regression/scripts/release_cray.sh, regression/scripts/release_toss2.sh
+ Teach scripts about KNL nodes on trinitite.
+ Teach scripts about fire and ice.
+ On Cray machines, load craype-hugepages4M to mimic default Draco developer environment.
+ On Toss systems, update the environment used for releasing with gcc/5.3.0
+ Update the mpirun flags used by openmpi to match recommended flags provided by the EAP team.
=> Update release scripts to reflect changes post-6_20_1 updates.

regression/sync_repository.sh
=> Correct commands used to init mirrored repo used by redmine.

regression/draco_regression_macros.cmake, regression/ml-crontab, regression/scripts/release_cray.sh
+ Update macro that finds Draco when building a 'perfbench' version of Jayenne or Capsaicin.
+ Clean up release script for Crays (used when releasing Capsaicin RC).
* [Fixes #807](https://rtt.lanl.gov/redmine/issues/807)
=> WIP: Clean up regress scripts to support perfbench.

config/setupMPI.cmake
* Tests on trinitite have been failing because of a change to MAPN and missing aprun options `-F shared`.
=> Fixing a bad merge that clobbered the '-F shared' option for aprun.

config/windows-cl.cmake
=> Cleanup compile flags for win32

src/quadrature/Ordinate_Space.hh
+ Replace the bad link with a text reference to the actual memorandum.
+ Thanks to Andrew Till for noticing the bad link.
=> Fix a bad link to a pdf document.

src/ds++/Check_Strings.hh, src/ds++/Data_Table.hh, src/ds++/Index_Converter.hh, src/ds++/Index_Counter.hh, src/ds++/Index_Set.hh, src/ds++/Index_Set.t.hh, src/ds++/Packing_Utils.hh, src/ds++/Release.cc, src/ds++/Release.hh, src/ds++/XGetopt.cc, src/ds++/XGetopt.hh, src/ds++/test/tstAssert.cc, src/ds++/test/tstCheck_Strings.cc, src/ds++/test/tstDracoMath.cc, src/ds++/test/tstField_Traits.cc, src/ds++/test/tstFile_Streams.cc, src/ds++/test/tstHomogeneous_New.cc, src/ds++/test/tstIndex_Converter.cc, src/ds++/test/tstIndex_Counter.cc, src/ds++/test/tstIndex_Set.cc, src/ds++/test/tstPacking_Utils.cc, src/ds++/test/tstPath.cc, src/ds++/test/tstSlice.cc, src/ds++/test/tstdbc.cc, src/rng/Counter_RNG.hh
+ Clean up comments
+ Remove old code.
+ Change some for-loops into C++11 format.
=> Minor cleanup of some old-ish code.

CMakeLists.txt, ChangeLog, regression/alist.sh, regression/scripts/release_cray.sh, regression/scripts/release_toss2.sh, src/ds++/Release.cc
=> Merge Draco 6_21_0 branch back to develop

config/unix-g++.cmake, environment/bashrc/.bashrc_tt, regression/scripts/common.sh, regression/scripts/release_cray.msub, regression/scripts/release_cray.sh
=> Minor cleanup for release scripts and dev-env on trinitite.

regression/checkpr.sh, regression/regression-master.sh, regression/sn-crontab, regression/sn-regress.msub, regression/sync_repository.sh
+ On Snow, create two new special builds:
- newtools - Intel-17.0.2 + OpenMPI-2.0.2
- gcc610   - GNU-6.1.0 + OpenMPI-2.0.2
+ Fix some spelling errors.
+ Remove or hide some debug output.
+ [Refs #893](https://rtt.lanl.gov/redmine/issues/893)
=> Stand up nightly regression for Intel-17.0.2 and OpenMPI-2.0.2.

README.draco, environment/bashrc/.bashrc, environment/bashrc/.bashrc_linux64, environment/bin/bash_functions.sh, environment/git/install-hooks.sh, regression/scripts/common.sh, regression/sync_repository.sh
- README.draco - Add some notes about setting up the development environment (git hooks, emacs, bash).
- Create a new bash function 'add_to_path' in bash_functions.sh and use it in .bashrc. and .bashrc_linux64.
- Remove definition of bash functions pkgdepends, findgrep and archive.
- Document bash functions defined in regression/scripts/common.sh
- Modify sync_repository.sh so that it calls checkpr.sh. This significantly reduces the amount of code in sync_repository.sh.
=> Cleanup some of the scripts for the Draco development environment:

regression/valgrind_suppress.txt
=> More valgrind suppressions.

src/ds++/test/cxx11example_move_semantics.cc
=> Minor cleanup suggested by Ryan.

config/vendor_libraries.cmake, src/ds++/test/test_fpe_trap.py
* Minor changes to enable building with Python 3.
=> Enable builds with Python 3.

environment/bashrc/.bashrc, environment/bashrc/sample.bash_profile, environment/bashrc/sample.bashrc, environment/git/canonicalize_filename.sh, regression/valgrind_suppress.txt, src/c4/test/CMakeLists.txt, src/compton/test/CMakeLists.txt
+ Retire some rarely used aliases (.bashrc):
- dmesg, ldmesg
- free, hosts
- print, cd.., sdl, hpss
- mapache, tscp, trsync
+ Add some module related aliases (I have trouble typing 'moduel').
- ma='module avail'
- mls='module list'
- mld='module load'
+ Add some slurm related aliases (from hpcfaq.lanl.gov/faqs/view/58)
- showq-like functions: sqrun, sqpend, pend, sqother, sq, sqall, showme
- checkjob-like functions: chk
- drmgroups, etc: suser, sshare_acct, drmgroups, sreason, showuser
+ For non-interactive shells, ensure that DRACO_ENV_DIR is set.
+ Add two more valgrind suppressions.
+ Remove some dead code (that was only active for MPIEXEC='aprun').
=> Provide some developer environment tweaks and some cleanup.

src/cdi/CDI.cc, src/cdi/CDI.hh, src/cdi/CDI_Integrate_Rosseland_Planckian_Spectrum.cc, src/cdi/CDI_integratePlanckSpectrum.cc, src/cdi/CDI_integrateRosselandSpectrum.cc, src/cdi/test/tCDI.cc
* It looks like there was a bad merge. These changes should have been included with #261.
=> One more change to CDI to fix failures in Capsaicin.

config/setupMPI.cmake, regression/ml-crontab, regression/sn-crontab
+ Cleanup the the comments and code used to set options for `srun` used on trinitite.
+ Move some cronjobs from moonlight to snow to prepare for the retirement of moonlight.
+ [Pre-Merge Code Review](https://github.com/lanl/Draco/wiki/Style-Guide)
=> Do some maintenance on our scripts for LANL HPC system.

regression/ccscs2-crontab, regression/checkpr.sh, regression/sync_repository.sh
+ Run 'Release' continuous integration tests on ccscs2 for each new PR.
+ Fixes redmine [issue 960](https://rtt.lanl.gov/redmine/issues/960).
+ Replaces #277 (which had extra files in the change set)
=> Stand up continuous integration testing on ccscs2.

.travis-install-dependencies.sh, src/lapack_wrap/CMakeLists.txt
=> Remove 2nd 'else()'  from if-block.

src/c4/CMakeLists.txt, src/c4/test/CMakeLists.txt
* Exclude unsupported code for APPLE and WIN32
=> Exclude unsupported code for APPLE and WIN32

.travis.yml
=> Try setting C_FLAGS for -coverage.

config/compilerEnv.cmake
+ Initial testing with gcc looks great.  This PR will allow us to check other compilers.
+ Ref: [Redmine 1046](https://rtt.lanl.gov/redmine/issues/1046)
=> Start requiring C++14 and C-11 language standards.

CMakeLists.txt, ChangeLog, regression/scripts/release_cray.sh, regression/scripts/release_toss.sh, src/ds++/Release.cc
* Details for this release can be found at https://rtt.lanl.gov/redmine/versions/60. 
* Minor changes to version numbers, metrics and release scripts are included in this PR.
* Reference:
* Checks
=> Merge Draco-6_24_0 back to develop

config/ApplicationUnitTest.cmake, config/CMakeLists.txt, regression/alist.sh, regression/ccscs2-crontab, regression/metrics_report.sh, src/diagnostics/Diagnostics.hh, src/ds++/StackTrace.hh
* While building on several different machines, I found a few inconsistencies and poorly formatting source files.  This commit cleans up the files that I was looking at.
* There have been a few tweaks to the automated scripts that run on ccsc2.  Update the repository with the the currently active versions of these scripts.
+ In `ApplicationUnitTest.cmake,` only set the `DRACO_INFO` variable if the build system knows about the `Exe_draco_info` build target. This fixes a rare issue that can can cause tests in ds++ to fail if the `draco_info` application fails to register itself with the build system.
+ Remove the sanity checks from `config/CMakeLists.txt` as these can be misleading when triggered.
+ Wrap some commands to keep line lengths below 80 columns.
+ Collate data in `alist.sh` by …
=> Clean up some files that haven't been touched in a while.

environment/bashrc/.bashrc
+ The identified warning should be silent.  Fixed.
* Reference:
* Checks
=> Eliminate a Draco bashrc error from printing.

src/CMakeLists.txt, src/diagnostics/qt/CMakeLists.txt
+ Do not automatically include headers automatically generated by qt.
+ Simplify the use of FeatureSummary.
* Reference:
* Checks
=> Provide small changes to better support newer versions of CMake.

environment/bashrc/.bashrc_linux64, regression/ccscs-regress.msub, regression/sync_repository.sh
The script tries to create files at `/var/tmp/$USER/`, but the `$USER` subdirectory might not exist.  Update the script to create the directory before trying to create files at that location.
* Reference:
* Checks
=> Fix a bug in sync_repository.sh that prevented PRs from running.

LICENSE.md, README.md, environment/bashrc/.bashrc_slurm
* Mimic some other github pages with a 'version' badge and a 'license' badge.
* You can see how this looks at https://github.com/KineticTheory/Draco/tree/more_github_badges.
* I accidentally included `.bashrc_slurm`, but this change looks okay.  Any command line options given to the slurm bash functions will be propagated to `squeue`.
=> More GitHub badges

config/unix-g++.cmake, environment/bashrc/.bashrc, environment/bashrc/sample.bash_interactive, environment/bashrc/sample.bash_profile, environment/bashrc/sample.bashrc, environment/elisp/sample.emacs
=> Fix a bug in .bashrc; update sample dotfiles.

environment/bashrc/.bashrc, regression/cts1-job-launch.sh, regression/cts1-options.sh, regression/regression-master.sh
* Grizzly is a LANL CTS-1 class machine that we are being requested to make use of once our access to Badger is removed.  This PR updates dev environment and regression scripts to work correctly on Badger.
+ Add entries into Draco's dev environment (`.bashrc`).  Grizzly is a CTS-1 machines.  That is, it looks like Snow and Badger.  However, it is designed for large jobs (> 70 nodes).
+ Update regressions scripts to know how to run on grizzly.
+ These updates depend on a change in *user_contrib* that hasn't been merged yet.
* Reference:
* Checks
=> Add support for Grizzly.

config/CMakeAddFortranSubdirectory.cmake
+ The Visual Studio build of Jayenne was broken partly due to a misconfiguration of the MPI target for CMakeAddFortranSubdirectory-based subdirectories.
+ Update the logic that sets `MPI_gfortran_LIBRARIES` (only for WIN32) to be more general.
* Reference:
* Checks
=> Minor patch to CMakeAddFortranSubdirectory to support Jayenne.

regression/scripts/common.sh, regression/scripts/release_cray.sh
=> Fix a few typos in the release scripts.

regression/push_repositories_xf.sh, regression/repository_list.sh, regression/update_regression_scripts.sh
+ Go ahead and add trt to the repository list for regressions.
+ Update the script 'update_regression_scripts.sh' to be a little more generic.  It will now use the list of git repos find in the file 'repository_list.sh'.
* Reference:
* Checks
=> Update regression system to support new Capsaicin projects.

config/compilerEnv.cmake, config/unix-clang.cmake, config/vendor_libraries.cmake, regression/ccscs-regress.msub, regression/ccscs3-crontab, src/RTT_Format_Reader/test/TestRTTFormatReader.cc, src/cdi/GrayOpacity.hh, src/cdi/OpacityCommon.hh, src/cdi/test/DummyGrayOpacity.hh, src/cdi_analytic/Analytic_Gray_Opacity.cc, src/cdi_analytic/Analytic_Gray_Opacity.hh, src/cdi_analytic/Analytic_Models.hh, src/cdi_analytic/Analytic_MultigroupOpacity.cc, src/cdi_ipcress/IpcressGrayOpacity.hh, src/diagnostics/test/tstTiming.cc, src/ds++/File_Streams.cc, src/ds++/File_Streams.hh, src/ds++/test/tstAssert.cc, src/ds++/test/tstCheck_Strings.cc, src/ds++/test/tstData_Table.cc, src/ds++/test/tstFile_Streams.cc, src/ds++/test/tstdbc.cc, src/lapack_wrap/Blas.hh, src/lapack_wrap/Blas_Prototypes.hh, src/lapack_wrap/test/tstBlas_Level_1.cc
* While working through some existing code, I have made incremental minor updates.
* A couple of items are related to new features of cmake (PIC)
* A couple of items are related to experiments with LLVM inside of Visual Studio.
Build system:
+ Tell _CMake_ to always generate position independent code (`PIC`).
+ Enable the use of _clang_ as the compiler when the generator is "Visual Studio."
+ Allow detection of _doxygen_, _mscgen_ and _graphviz(dot)_ when running _cmake_ on Windows.
Code cleanup:
+ In some cases, collapse multiple line commands into a single line.
+ Remove `DLL_PUBLIC_x` in a few places where it is no longer needed.
+ Remove redundant include directives in a few places.
+ Remove the keyword `static` from functions declared in `cc` files. For C++ this keyword didn't do …
=> WIP: General code cleanup

regression/scripts/cts-env.sh
* Corrected cts-env.sh
* [Fixes Redmine Issue #1301](https://rtt.lanl.gov/redmine/issues/1301)
* Added a break for draco-7_0_0 section.
* Reference:
* Checks
=> Corrected the release script for cts machines.

config/compilerEnv.cmake
*  Fix fortran compiler config issues on mac
* Reference:
* Checks
=>  Fix fortran compiler config issues on mac

regression/ccscs-job-launch.sh, regression/ccscs-regress.msub, regression/ccscs2-crontab, regression/ccscs3-crontab, regression/ccscs6-crontab, regression/cts1-regress.msub, regression/draco_regression_macros.cmake, regression/regression-master.sh, regression/sn-crontab, regression/tt-crontab, regression/tt-regress.msub
* Teach the regression system about trt and npt.
* Reference:
* Checks
=> Setup for trt regressions

src/ds++/FMA.hh
* Jayenne is still struggling with round off issues.  Provide another way to toggle FMA functionality.
+ Provide a way to force the use of `fma` or `a*b+c` via CPP macros.
+ Update the `fma_with_diagnostics` function to be more flexible with floating point types.
* Reference:
* Checks
=> Another tweak to FMA.hh

config/UseLATEX.cmake
* Update the version of our LaTeX macro.
=> Update the version of our LaTeX macro.

.travis.yml, regression/check_style.sh, regression/darwin-regress.msub, src/c4/test/tstofpstream.cc
* Alternate solution for #593.
* Reference:
* Checks
=> Attempt to fix style check when target merge is not 'develop'.

src/c4/test/tstQueryEnv.cc
* Provide CPP macro wrapper for `setenv/unsetenv` and use native functions when compiling under MSVC.
* Reference:
* Checks
=> Fix setenv/unsetenv for MSVC.

environment/bashrc/.bashrc_darwin_fe, regression/darwin-regress.msub, regression/scripts/common.sh, regression/scripts/darwin-env.sh, regression/scripts/release.msub, regression/scripts/release_darwin.sh
* this is Draco-7_2_0 with a few environment (modules) and release script changes to support this system.
* Reference:
* Checks
=> Add environment and release scripts to support Darwin

tools/parse_draco_pr.py, tools/parse_jayenne_pr.py
* Added python Draco and Jayenne PR parsers.
=> + python PR parsers

environment/bashrc/.bashrc_cray
Draco should be working on Capulin for friendly-users.
* Reference:
* Checks
=> WIP: Tweak environments for Capulin support.

CMakeLists.txt, ChangeLog, src/ds++/Release.cc, tools/ats1-env.sh, tools/ats2-env.sh, tools/ats2-release.sh, tools/common.sh, tools/cray-env.sh, tools/cts1-env.sh, tools/cts1-release.sh, tools/darwin-arm-env.sh, tools/darwin-power9-env.sh, tools/darwin-release.sh, tools/darwin-x86_64-env.sh, tools/github.api.py, tools/redmine-release-note-template.txt, tools/release.msub, tools/release.sh
* Updates to release scripts, metrics, and notes were made during the release of Draco-7_3_0.  
* For more details see https://rtt.lanl.gov/redmine/versions/70.
* Reference:
* Checks
=> Merge the Draco-7_3_0 release branch back to develop

src/ds++/Release.cc, src/ds++/ScalarUnitTest.cc, src/ds++/ScalarUnitTest.hh, src/ds++/UnitTest.hh, src/ds++/test/tstRelease.cc
* Minor cleanup for some items that I noticed while working on unrelated PRs.
* Fix spelling errors.
* Make use of white space more consistent.
* Remove some DLL_PUBLIC decoration that is no longer needed.
* Remove an empty file.
* Reference:
* Checks
=> Minor cleanup of comments, decorators, spelling, etc.

src/c4/QuoWrapper.cc, src/c4/QuoWrapper.hh
* Some of the documentation was wrong.  Clean up on isle one!
* Reference:
* Checks
=> Fix inline comments for QuoWrapper.

.github/PULL_REQUEST_TEMPLATE, environment/bashrc/.bashrc, environment/bashrc/.bashrc_cray, tools/common.sh
* After the CLE7 update on trinitite, some modules have new names.  Make these corrections in Draco's `bashrc` files.
+ Provide minor updates for Draco developer environments that target trinitite. These may be necessary after the CLE7 update (`.bashrc` and `.bashrc_cray`)
- Specify versions for some modulefiles.
- General cleanup in the scripts.
+ Minor tweak to the Github new PR template.
+ Fix broken bash function `selectscratchdir`.
* Reference:
* Checks
=> Update developer environment (tt)

config/vendor_libraries.cmake
* #172 broke cta.
* Reference:
* Checks
=> Revert pr172.

CMakeLists.txt, ChangeLog, environment/bashrc/.bashrc_ats2, src/ds++/Release.cc, tools/README, tools/ats1-env.sh, tools/ats2-env.sh, tools/cray-env.sh, tools/cts1-env.sh, tools/darwin-arm-env.sh, tools/darwin-power9-env.sh, tools/darwin-x86_64-env.sh, tools/github.api.py
* The Draco-7_5_0 is done,
* Merge branch updates back to `develop`
* Reference:
* Checks
=> Merge Draco-7_5_0 branch back to develop

.gitignore
* Tiny update to ignore Sublime Text IDE files
* That ^^^
* Add two lines to .gitignore
* Reference:
* Checks
=> Add more to ignore (Sublime IDE type files)

environment/bashrc/.bashrc, environment/bashrc/.bashrc_vm
* Add .bashrc for LAP Virtual Machine
* Initial effort to use LAP Virtual Machine for offline development
* Reference:
* Checks
=> Add .bashrc for LAP VM

environment/bashrc/.bashrc, environment/bashrc/.bashrc_ats2, environment/bashrc/bash_functions.sh
* Ensure bash variables are set before first use.
* Reference:
* Checks
=> Fix bash environment for rzansel.

CMakeLists.txt, ChangeLog, tools/ats1-env.sh, tools/ats2-env.sh, tools/common.sh, tools/cts1-env.sh, tools/darwin-arm-env.sh, tools/darwin-power9-env.sh, tools/darwin-x86_64-env.sh
* Merge Draco-7_7_0 back to develop
* Reference:
* Checks
=> Merge Draco-7_7_0 back to develop

environment/bashrc/.bashrc_cray, environment/bashrc/.bashrc_cts1
=> Bump cmake version to 3.17.2 on HPC.

environment/lmod/README.lmod, environment/lmod/admin.list
* There are three files that are useful for modifying the behavior of LMOD modules.  These samples provide basic examples for developer who wish to use these customizations in their local `$HOME`.
* Reference:
* Checks
=> Provide sample lmod module settings files.

environment/elisp/README.elisp, environment/elisp/draco-config-modes.el, environment/elisp/draco-global-keys.el, environment/elisp/draco-mode.el, environment/elisp/draco-setup.el, environment/elisp/sample.emacs
* Import some useful settings.
* Sample Melpa setup and use.
* Add cmake and yaml modes
* F12 -> clang-format for the current select (or whole buffer)
* Require final newline at end of file.
* Reference:
* Checks
=> Provide some updates to the Draco emacs sample scripts.

CMakeLists.txt, ChangeLog, src/diagnostics/draco_info.cc, src/ds++/Release.cc, tools/ats1-env.sh, tools/ats2-env.sh, tools/common.sh, tools/cts1-env.sh, tools/darwin-arm-env.sh, tools/darwin-power9-env.sh, tools/darwin-x86_64-env.sh, tools/release.msub, tools/release.sh
* See https://github.com/lanl/Draco/releases/tag/draco-7_8_0
* Reference:
* Checks
=> Merge Draco-7_8_0 back to develop

.github/workflows/linter.yml, CMakeLists.txt, config/compilerEnv.cmake, config/windows-msvc.cmake, src/cdi/CDI.hh, src/ds++/Assert.cc, src/ds++/Assert.hh
+ Plus clang-format fixes.
* Reference:
* Checks
=> Comment only changes for 100 col format.

.github/workflows/linter.yml, config/capture_lcov.sh
* Address warnings flagged by the shell script linter.
* fixes #918
* Reference:
* Checks
=> Fix linter warnings in capture_lcov.sh

config/setupMPI.cmake, src/c4/ParallelUnitTest.cc, src/c4/test/tstQuoWrapper.cc
* Working with Howard to diagnose openmpi-4 issues.
* [Fixes Redmine Issue #2163](https://rtt.lanl.gov/redmine/issues/2163)
* add diagnostics to help us debug some test failures.
* Reference:
* Checks
=> WIP: Add diagnostics to debug issues with openmpi-4.

CMakeSettings.json, config/CMakeAddFortranSubdirectory.cmake, config/unix-g++.cmake
=> Fix msvc default settings.

src/rng/test/ut_ars.c
+ Attempting to fix a dashboard issue.
* [Fixes Redmine Issue #2208](https://rtt.lanl.gov/redmine/issues/2208)
* Reference:
* Checks
=> Suppress an MSVC warning

config/query_gpu.cu, environment/bashrc/.bashrc_cray, environment/bashrc/bash_aliases.sh, environment/bashrc/bash_functions.sh, environment/bashrc/bash_functions2.sh, environment/bashrc/bashrc_slurm
* These tweaks were in my `$HOME` for a while.  I think these are worth holding onto.
* I've also updated the scripts to pass the *super-linter* CI.
* Reference:
* Checks
=> Minor cleanup of HPC bash scripts

environment/git/pre-commit-clang-format
+ Fixes #811
* Reference:
* Checks
=> Avoid running git commit hooks if git version is old.

environment/bashrc/bashrc_slurm, src/device/test/Dual_Call.cu, src/device/test/basic_kernels.cu, src/device/test/gpu_device_info.cu, src/device/test/gpu_dual_call_test.cu, src/device/test/gpu_hello_rt_api.cu, tools/check_style.sh
* Fix broken bash alias commands.  These were modified recently as I tried to clean up bash scripts flagged by the lint CI.
* Remove quotes that caused issues.
* Reference:
* Checks
=> Fix an alias after overzealous use of quotes were added.

environment/bashrc/.bashrc_cts1, environment/bin/xfpull
* Initial testing shows that `module load` and `module unload` work as expected now.
* I might still have an issue with `module swap`.
* Reference:
* Checks
=> Use new module system for CTS-1 machines

src/ds++/Assert.hh
=> Remove some dead code

config/setupMPI.cmake, config/unix-xl.cmake, environment/bashrc/.bashrc_darwin_fe
* Try to eliminate build warnings related to XL
* Try to make the CI faster for spectrum-mpi.
* Reference:
* Checks
=> WIP: Tweak mpirun and compile options for P9 with XL and SMPI.

environment/elisp/draco-mode.el, tools/github.api.py
* Improve the behavior of this script before the upcoming release.
* Only include PRs merged to `develop`.
* Print the label associated with issues.
* [Fixes Redmine Issue #2181](https://rtt.lanl.gov/redmine/issues/2181)
+ Apply flake8 style changes.
+ Update Emacs template for python divider line to conform to flake8 recommendations (add a space between `#` and `-`). 
+ In the generated report, only include Pull Requests that were merged to the `develop` branch.
+ In the generated report, use the label assigned to the issue ('bug', 'feature', etc.) instead of the generic 'issue' (when information is available).
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters …
=> Updates for github.api.py.
