.travis.yml
src/FortranChecks/CMakeLists.txt

Initial commit to enable Travis CI, some tests still fail.

Enable travis CI

---

regression/ccscs-regress.msub
regression/draco_regression_macros.cmake
regression/regression-master.sh

- For all draco regressions, use github by default. There is no need to specify  '-g' when calling regression-master.sh.  Jayenne and Capsaicin still default to svn.
- Change the directory name for the build directory created by the regression system when source code is checked out from github. The top level directory now uses the following pattern (e.g.: `Nightly_gcc-develop`): `<dashboard_type>_<compiler>-<git branch>`
- Teach the regression system to find the draco installation directory when building Jayenne or Capsaicin. This directory now has '-develop' appended (the git branch name).

In the regression system, make github the default location for draco

---

.clang-format
.travis.yml
regression/check_style.sh

This is WIP...
- Relax some of the checks set by .clang-format.
- Add a new 'style' test to the travisCI matrix.
- The new test uses the provided shell script check_style.sh to ensure new or modified lines of code conform to the style specified by .clang-format.
- Load clang-format-3.8 in the travisCI environment.
- There are several changes recommended by junghans that need to be implemented before this PR is merged. These updates will be added in a separate commit based on the comments that were inadvertantly purged from github when the repo was replaced, but are in a set of emails sent to KT.
To do (comments from junghans)
- yes, direct control over `-j`, targets, control parameters, etc.

Add a code style check to travisCI

---

ChangeLog
config/compilerEnv.cmake
config/component_macros.cmake
regression/scripts/common.sh
regression/scripts/release_cray.sh

+ Add a brief entry to the ChangLog concerning draco-6_19_1.
+ Switch to using shared libraries instead of static on Cray platforms (compilerEnv.cmake).
+ Update release scripts to point to new files/locations used by HPC to identify the current system (e.g.: /usr/projects/hpcsoft/utilities/bin/sys_name).
+ Add case statements for tt-* and tr-* (trinitite and trinity).
+ No longer use '-C config/CrayConfig.cmake' since cmake/3.5.0+ no longer requires this bootstrapping.
+ Update the list of modulefiles loaded for the release.
+ Replace multiple if statements that match Trinity, Trinitite, etc. with conditional on CRAY_PE.
+ Update list of scratch disk locations.
+ No longer limit ppn on Cray since the test system restricts testing to 1 job per node at any given time.
fixes #13

Updates for releasing draco-6_19_1 on trinitite and trinity.

---

environment/vim/.vimrc

This .vimrc file sets tabs to spaces, uses the appropriate number of
spaces and automatically removes trailing white spaces when a file is
saved. Users can copy it to their home directory or source it in their
.vimrc file.

Added a simple .vimrc file to conform to style guide

---

config/vendor_libraries.cmake
environment/bashrc/.bashrc_darwin_fe
regression/darwin-job-launch.sh
regression/darwin-regress.msub

+ Default `USE_CUDA=OFF,` even if the cuda libraries are found.
+ Change module system to load `intel/16.0.3` by default.  This also brings in Intel MPI 5.1.3 and MKL.
+ Fix the regression system so that it uses the scripts found in the same directory as `regression_master.sh` instead of looking for scripts at `/usr/projects/draco/regress/draco.`
If merged before #34, then #34 will need to be rebased and tested before it can be merged.

On Darwin, update draco dev env and regression system to use intel/16

---

config/vendor_libraries.cmake
regression/ccscs-regress.msub
regression/darwin-regress.msub
regression/ml-regress.msub
regression/sync_repository.sh
regression/tt-regress.msub

+ Recent changes uncovered a couple of older issues in the regression system.
+ Because `USE_CUDA` now defaults to `OFF`, we need an extra check in `setupCuda` to turn it on in Jayenne if it is turned on in the version of Draco that we are linking to.
+ Fix a problem that could occur if `USE_GITHUB` was never set.
+ Load a newer version of git before trying to rebase from within the nightly regression system.

Fix a couple of recently discovered issues with the regression system.

---

environment/bashrc/.bashrc_tt
environment/cshrc/.cshrc
regression/tt-regress.msub

+ Begin using cmake/3.6.1 (was 3.5.2)
+ Load the git module.
+ The new default compiler is intel/16.0.3 (but unload gcc/6.1.0 that is automatically loaded with PrgEnv-intel).
+ Retire CI/CT case from .cshrc
+ I cannot compile capsaicin yet. I may need to rebuild trilinos.
+ Regressions are only working for draco.

Update development environment for Trinitite with Redwood UP01.

---

regression/draco_regression_macros.cmake
regression/regression-master.sh
regression/tt-crontab
regression/tt-job-launch.sh
regression/tt-regress.msub

* Begin adding options to support knl-based regressions:
* Regression master will now accept '`-e knl`'
* Provide a sample crontab for knl-based regression on trinitite.
* For trinitite, move the moab allocation parameters from `tt-regress.msub` to command line arguments in `tt-job-launch.sh`. This allows the regression system to swap between `-lnodes=8:knl:ppn=68` and `-lnodes=8:haswell:ppn=32`. The addition of 'knl' or 'haswell' ensures that the allocation doesn't mix knl and haswells in the granted allocation.
* Add a partition report to the "t" logfile. For example (512 haswell cores)
```
Allocation configuration:
512 model name : Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
```
* When the regression system is looking for a Draco install from a previous regression run (i.e. Jayenne needs …

Regression updates for improved support of trinitite (knl vs. haswell)

---

environment/bin/bash_functions.sh
regression/Draco_Linux64.cmake
regression/ccscs-crontab
regression/ccscs-job-launch.sh
regression/ccscs-regress.msub
regression/draco_regression_macros.cmake
regression/fetch_co.sh
regression/ml-crontab
regression/ml-job-launch.sh
regression/ml-regress.msub
regression/regression-master.sh
regression/sync_repository.sh
regression/tt-crontab
regression/tt-job-launch.sh
regression/tt-regress.msub
regression/update_regression_scripts.sh
src/cdi_analytic/nGray_Analytic_Odfmg_Opacity.hh

First cut at updating the regression system to pull jayenne from gitlab.  This should fix regressions on ccscs7, Moonlight and Trinitite.  I will use a 2nd iteration to patch the regression system for darwin and win32.
* Provide additional documention about proxy variables found in the draco environment.
* Update sample crontab for ccscs-net servers.  Show commands for integrating gitlab and github repositories with redmine.  We must have a local checkout to allow redmine integration.  These directories are stored at `/ccs/codes/radtran/git.`
* Update the regression system to respect multiple values provided to option `-f`. These are featurebranch values like pr numbers.  By default these are set to `develop`.
* Provide extra logic to set the compiler version as part of the build name …

Updates to the regression and script system to support Jayenne at gitlab

---

regression/draco_regression_macros.cmake
regression/update_regression_scripts.sh

* Remove a reference to Cielito/Cielo.
* Quote local variables that might be empty to avoid parse issues.
* Remove some extraneous debug prints.
* If we don't recognize the compiler, set the identifing string to 'unknown.'
* The valgrind and coverage processing in the regression system is triggered by the string identifier of the current compiler and the build name. I recently changed these identifiers so that the compiler's version is appended (e.g.: gcc -> gcc-4.8.5). This commit updates the regex pattern used to enable valgrind and coverage checks so that these checks are still performed.
* darwin and sunergos are not working with gitlab just yet.

Cleanup for regression scripts (targeting ccscs7, ml and tt).

---

regression/ml-crontab
regression/ml-regress.msub
regression/sync_repository.sh
regression/tt-regress.msub
regression/update_regression_scripts.sh

* These ran successfully last night.
* De-tangle the reponsibilities of `sync_repository.sh` and `update_regression_scripts.sh`.
* `sync_repository.sh` only touches copies of repositories that are mirrored to local file systems.
* `update_regression_scripts.sh` only updates the regression scripts on each machine that are located at `$regdir` (`/scratch/regress,` `/usr/projects/jayenne/regress,` etc.).
* Add keychain setup to `tt-regress.msub` and `ml-regress.msub.` This allows the crontab to access `gitlab.lanl.gov:jayenne/jayenne.git.`
* Fix a bug in ml-regress that set the `VENDOR_DIR` to the wrong location (cut & paste error).

Merging regression script changes required for ML and TT.

---

regression/draco_regression_macros.cmake
regression/update_regression_dir.bat
regression/win32-regress.bat
regression/win32-regression-master.bat

+ Add some double quotes around variables that contain paths that might have spaces.
+ Add header comment block to DOS batch files.
+ Use the regression-master.bat to kick off the update_regression_dir.bat.  This makes it easier to capture the output to a log file.

Minor cleanup of regression scripts for Win32 platforms.

---

regression/update_regression_scripts.sh

+ The default svn on Moonlight is too old to work with the Capsaicin repository. Use subversion-1.9.1 when updating the regression scripts.

Point to a newer svn when running on Moonlight.

---

regression/sync_repository.sh
regression/update_regression_scripts.sh

+ In addition to mirroring the Jayenne gitlab repository to the local file system (/ccs/codes/radtran/git/jayenne), download all PR branches. This serves as a local backup of the gitlab repository and allows us to easily copy a PR to the red network. Ditto for Draco on github.
+ Set the path to keychain for ccs machines.
+ Minor formatting changes.

Download jayenne PRs to the local filesystem nightly.

---

regression/draco_regression_macros.cmake

+ We only run `git clone` for never-before-run regression configurations. Most regressions will run `git pull`.
+ This change significantly reduces the time it takes to clone the project. Only the most up-to-date version of the repository is downloaded -- but this is all that the regression system needs.
+ fixes losalamos/Draco#54

Regressions: use '--depth 1' for initial git clone operation.

---

config/setupMPI.cmake
regression/metrics_report.sh

+ Gitlab CI uses a docker on darwin. CI sessions run as root, but openmpi refuses to run as root w/o the mpirun option '--allow-run-as-root'. Add this option on unit tests if the environment variable GITLAB_CI is defined.

Mods needed for gitlab CI

---

regression/Draco_Linux64.cmake
regression/ccscs-crontab
regression/ccscs-regress.msub
regression/darwin-regress.msub
regression/draco_regression_macros.cmake
regression/ml-regress.msub
regression/regression-master.sh

+ Use option `-e valgrind` to trigger a Dynamic Analysis dashboard entry.
+ Default all regression runs to Experimental builds. The crontab explicitly set the dashboard type to Nightly.
+ fixes losalamos/draco#53
+ fixes losalamos/draco#52

Make DynamicAnalysis an explicit option for the regression system.

---

regression/ml-regress.msub
regression/sync_repository.sh

+ Also fix a spelling error in the sync_repository.sh script.

On ML, begin using scratch1 instead of missing scratch3.

---

environment/elisp/draco-global-keys.el

+ Add lines to draco-global-keys.el to use clang-format with
f12 key binding for Windows and C-M-tab binding for Mac

Global key bindings for clang-format through emacs (from KT).

---

regression/fetch_co.sh

+ If the regression system (draco/regression/regression-master.sh) is used to test a pull request, it might not test to most up-to-date version of the PR due to an improper git pull command.
+ This change updates the script so that it saves some debug information to a log file.
+ This change also checks to see if the current PR is already cloned and checked out. If it is, then use `git pull origin pull/#/head` instead of a bare `git pull.` This ensures that the most recent version of the PR is downloaded from github before the regressions are performed.

Fix a bug that prevented testing the most up-to-date version of a PR.

---

environment/elisp/draco-config-modes.el

This is a minor change to one line in elisp file draco-config-modes.el to appropriately tab in emacs.

Patch indentation in draco mode for emacs (very minor).

---

environment/bashrc/.bashrc
environment/git/pre-commit-clang-format

Add a version check to the pre-commit hook to ensure clang-format is new enough. Older clang-format version will not apply the rules correctly.

Add a version check for clang-format

---

environment/bashrc/.bashrc_linux64
regression/valgrind_suppress.txt

+ Add another valgrind suppression for openmpi (new for 1.10.3).
+ Do not specify the python version to load from the default `.bashrc_linux64`. Use a `.modulerc` file instead.

Minor tweaks after vendor-dir changes on ccs-net servers.

---

config/CMakeLists.txt
src/rng/CMakeLists.txt

* Disable for `USE_CUDA=ON`
* Disable for Win32 (MSVC 2013 doesn't like it - this pr should fix the 43 compile failures reported by [cdash](rtt.lanl.gov/cdash/index.php?project=Draco&date=2016-09-27))
* Check the features provided by the current compiler before turning this option on
* Retire some build system logic related to KNC.

Use better logic to determine if R123_USE_CXX11=1 should be used.

---

regression/ccscs-crontab
regression/ccscs-regress.msub
regression/sync_vendors.sh

+ The gcc-4.8.5 Debug regression on ccscs7 enables bounds-checking in the STL. Update the list of modulefiles loaded to allow this regression to work correctly with trilinos-12.8.1.
+ Provide a script that is run by cron, that will push the ccscs7 vendor directory to all other ccs-net machines nightly.

Fix bounds-checking regression and provide sync_vendors script.

---

config/component_macros.cmake
regression/ccscs-regress.msub
regression/draco_regression_macros.cmake

+ The regression system wasn't using valgrind suppression file from the current source directory. It used the file found in the master regression script directory (e.g. /scratch/regress/jayenne/regression/valgrind_suppress.txt). This logic change will point future regressions to the suppression file found in the current checkout.
+ This commit is releated to [jayenne merge-request 21](https://gitlab.lanl.gov/jayenne/jayenne/merge_requests/21).
+ Also remove a deprecated regression feature (gcc-5.3.0 with bounds-checking)

[WIP] Use the valgrind suppression file found in the current source directory.

---

environment/bashrc/.bashrc_toss22
regression/ml-regress.msub

+ Openmpi/1.10.1 has been removed from toss2 systems.
+ Vendors have been built with openmpi/1.10.3.
+ Increment trilinos to 12.8.1 (since I needed to build it from scratch to work with openmpi/1.10.3.)

On Toss2 systems, begin using openmpi/1.10.3 and trilinos/12.8.1.

---

src/VendorChecks/CMakeLists.txt
src/VendorChecks/test/CMakeLists.txt
src/c4/config.h.in

+ Only test parmetis and superlu-dist libraries if current build links to MPI.
+ Clean up the comment block in `c4/config.h`.

Provide better support for DRACO_C4=SCALAR.

---

config/setupMPI.cmake
config/unix-intel.cmake

* When packing multiple tests onto a Cray node, we must reserve memory for each PE.  I originally set this to 2 GB.  This value is too high for the KNL partition and would oversubscribe the node's memory. This PR reduces the value to 1.4 GB/PE.
* This commit also removes on obsolete check that ensures that MKL is new enough for the selected Intel compiler.  Newer modulefiles for Intel compilers automatically select the MKL version so this check is no longer needed. 

Reduce memory reserved for aprun/mapn to support KNL.

---

regression/fetch_co.sh

* For gitlab-based repositories (jayenne), if a PR was updated after the initial regression tests were run, the `fetch_co.sh` script would fail to update the checked-out source directory due to a bug in the script.  The bug was a hard coded path to `pull/[0-9]+/head` that works for github, but not gitlab. the command should have used `$prdir/[0-9]/head`.

Fix a bug in the regression script that is used to checkout PRs.

---

environment/cshrc/.cshrc

* Updated cshrc file to load new modules on toss22 machines, refs #821 (redmine number)
* Also, set DRACO_AUTO_CLANG_FORMAT variable to ON
* Fixes #821 (redmine number)

Bringing loaded modules up to date for toss22 machines fixes #821

---

regression/draco_regression_macros.cmake
regression/fetch_co.sh
regression/ml-crontab
regression/sync_repository.sh
regression/sync_vendors.sh
regression/tt-crontab

+ We already mirror the github repository to ccscs7 every 15 min.
+ Add some logic to scan the output of this synchronization process that will allow us to discover when a new PR is created.
+ If a new PR is found, start a regression build (coverage).
+ There appaer to be at least two types of PRs: 'head' and 'merge'. I'm not sure how this differ so run the regression on both for now.  We can fix the script later.
+ refs #815

Create a CI on ccscs7 based on discovered github PRs.

---

regression/ccscs-crontab
regression/ccscs-regress.msub
regression/draco_regression_macros.cmake
regression/regression-master.sh

+ Teach regression-master.sh about the option `-e belosmods`
+ Teach ccs-regress.msub about the `belosmods` option:
- swap trilinos module with trilinos/12.8.1-belosmods
- append `belosmods` to the build name that shows up on CDash.
+ refs #823

Teach the regression-system to run a 'belosmods' flavor.

---

config/application_unit_test.py

+ Make a list of arguments that do not have trailing whitespace or empty strings to pass to subprocess
+ Remove the shell=True option from all subprocess calls
+ Use subprocess.Popen call to avoid output files for the simple `draco_info` call

Improve Windows compatibility and file creation in Python application unit test driver

---

regression/alist.sh
regression/sync_repository.sh

+ We haven't been mirroring the capsaicin svn repository to moonlight.  This means that nightly regressions are checking an out-of-date version of capsaicin on Moonlight and trinitite. Fixed.
+ Provide a small tweak to alist.sh that should have been committed with the draco-6_20_0 merge.

Regression fix for Capsaicin and minor script change.

---

regression/fetch_co.sh

+ Change the logic flow for cloning/updating the source associated with a PR.
+ The regression always starts from a clone of `develop` for a new PR.
+ If this is the first attempt at testing the PR, the updated files are fetched in a new local branch with the name `pr999` and the regression system uses this source tree.
```
git fetch origin pull/999/head:pr999
```
+ If this is not the first regression attempt for the PR, then we will switch back to `develop` and delete the `pr999` branch before fetching it again.
```
git checkout develop
git branch -D pr999
git fetch origin pull/999/head:pr999
```
+ There is probably a more elagant solution (like `git pull origin pull/999/head`) but I can't get that to work in a robust way.  Suggestions are welcome.
+ refs #815 …

Another attempt to fix fetch_co.sh.

---

environment/git/install-hooks.sh

+ The script now takes an optional argument that is the path to top level directory of a git project. To setup a pre-commit hook that runs clang-format during a local commit, run this script:
```
/path/to/draco/environment/git/install-hooks.sh /path/to/jayenne
```

Update script that sets up clang-format as a pre-commit hook for git.

---

.travis-install-dependencies.sh
.travis.yml

* Change some of the tools and setup used by travis (CI system for Draco). I am addressing two issues with this change: (1) We are using clang-format-3.9 on our local systems to check formatting requirements.  We should use the same version when running the checks under Travis, and (2) Recent changes to c4 require OpenMPI 1.10+ but Ubuntu 12 and 14 only know about version 1.6.
+ Modify the script that provides vendors to the build environment on travis to provide clang-format-3.9 and git-clang-format-3.9.  Travis's Ubuntu environment doesn't allow installing these versions via apt-get so do it via this script. Also download, build and install openmpi-1.10.3.  Building MPI takes about 10 minutes, so this will make the checks run much slower.
+ Change the travis environment from Ubuntu 12 …

Update Travis CI runner scripts

---

environment/bashrc/.bashrc
environment/bashrc/.bashrc_toss3

+ Do not load module 'hsi' by default.
+ Teach .bashrc about fi-fe and ic-fe.

Minor updates for environment on Fire/Ice:

---

src/c4/Invert_Comm_Map.cc
src/c4/Invert_Comm_Map.hh
src/c4/test/tstInvert_Comm_Map.cc

Rob's ICM fix with file merged

---

regression/ml-crontab
regression/ml-regress.msub
regression/regression-master.sh

+ Remove cuda-based regressions from example crontab.
+ Remove 'cuda' option for Moonlight from regression-master.sh.
+ Print an error message if 'cuda' regressions are attempted from Moonlight.

Discontinue support/regressions for GPU kernels on Moonlight.

---

config/unix-intel.cmake

Disable intel compiler option that flushes denormal results to zero.

add -no-ftz compile option for intel compiler

---

.travis-install-dependencies.sh
ChangeLog
config/setupMPI.cmake
config/unix-ifort.cmake
environment/cshrc/.cshrc
regression/scripts/common.sh
regression/scripts/release_bgq.msub
regression/scripts/release_bgq.sh
regression/scripts/release_cray.sh
regression/scripts/release_toss2.sh
src/c4/config.h.in

The Draco-6_20_1 release is done except for merging these changes back to `develop`.  
+ Provide a release summary in ChangeLog.
+ For the Intel compiler, disable 'ip' warnings that originate from the MPI libraries. This change targets Snow, Fire and Ice.
+ Update release scripts to use the correct vendors and draco version numbers.
+ Update the BGQ release scripts to clean up the local environment so as to keep the environment below the 8192 max size.
+ Update the cray release scripts to specifically target the haswell architecture.
+ Tweak `c4/config.h` and `config/setupMPI.cmake` to define `MPICH2_CONST` correctly when compiling on Sequoia with gcc-4.8.4.

Update release scripts and environments for the release of Draco-6_20_1.

---

environment/git/pre-commit-clang-format

Previously, setting `DRACO_CLANG_FORMAT=AUTO` would automatically fix style issues in files included in the current change set.  However, these style changes were only applied after the commit - leaving modified files in your working directory. This commit changes the behavior of the pre-commit-hook so that the commit is _aborted_ and instructions are issued to (1) check/test the modified files; (2) git-add the files that were modified to meet style requirements into the current change set; and (3) try the commit again.

Address undesired behavior for the clang-format pre-commit hook.

---

config/doxygen_config.in
environment/bashrc/.bashrc
environment/bashrc/.bashrc_toss22
environment/bashrc/.bashrc_toss3
environment/bashrc/.bashrc_tt
environment/bin/bash_functions.sh
environment/bin/xfpull
environment/bin/xfpush
environment/cshrc/.cshrc

+ `clang-format/3.9.0` is now available on all HPC machines and will be loaded with the default Draco environment. Please consider installing the git pre-commit hook (`draco/environment/git/install-hooks.sh`) for all of your CCS-2 git repositories.
- `.bashrc` files updated
- `.cshrc` file updated
+ Add snow, fire and ice to the `.cshrc`.
+ Cosmetic changes
- Add header blocks to some bash scripts.
- Fix a filename typo in `doxygen_config`.

On HPC machines, add clang-format to the default Draco environment

---

regression/regression-master.sh
regression/sync_repository.sh

+ Build _Experimental_  _draco-develop_ once per day per machine and special build type (coverage, valgrind, fulldiagnostics, etc.)
+ Use the file `$regdir/logs/last-draco-develop.log` to establish the time of the last draco build.  If this file hasn't been touched since midnight, then build draco before attempting to build a Jayenne PR.
+ If we need to build draco, don't start any jayenne builds until the draco build is complete.

Only build Draco once per day for the Jayenne CI system.

---

autodoc/mainpage.dcc.in
regression/draco_regression_macros.cmake
regression/pull_repositories_xf.sh
regression/push_repositories_xf.sh
regression/regression-master.sh
regression/scripts/common.sh
regression/sync_repository.sh
regression/update_regression_scripts.sh
src/ds++/Release.cc

+ In `draco_regression_macros.cmake`, remove special code used to find Draco from the Capsaicin regression scripts.  Both Jayenne and Capsaicin will use the same logic now.
+ In `push_repositories_xf.sh`, remove the svn-specific coding. We only need to work with git repositories now.
+ In `sync_repository.sh` and `update_regression_scripts.sh` remove code related to subversion. Copy jayenne blocks and repurpose them for capsaicin.
+ Cosmetic changes to `Release.cc` and `mainpage.dcc.in`.
+ refs [#834](https://rtt.lanl.gov/redmine/issues/834)

Modify scripts to find capsaicin on gitlab instead of subversion.

---

src/diagnostics/qt/CMakeLists.txt

* Fix a bad command (too many closing parenthesis) that only impacts win32 builds that link to qt.

Fix a bad command (too many closing parenthesis) 

---

autodoc/CMakeLists.txt
config/doxygen_config.in
regression/pull_repositories_xf.sh
src/cdi_ipcress/IpcressMultigroupOpacity.hh

+ Instead of using the Draco logo image for Jayenne and Capsaicin autodoc pages, let each project set its own image.
+ Fix a small bug in the `pull_repository_xf.sh` script that prevented the Capsaicin repository from being mirrored to the red network.
+ Cosmetic-only cleanup in cdi_ipcress.

Tweaks to autodoc and repo mirroring systems.

---

src/parser/Class_Parse_Table.hh
src/parser/test/tstClass_Parser.cc
src/parser/utilities.hh

A second signature of the parse_class template function has been added that takes a second argument of type `Class_Parse_Table::Context_Type const &`. This allows a context object of class-dependent type to be passed to the parser which may provide context to change its behavior.
In a similar fashion, a second version of the parse_class_from_table template function has been added that takes a second `Class_Parse_Table::Context_Type &` argument and passes it as an argument to the `Class_Parse_Table` constructor.
A test has been added to exercise this option and ensure that it works. It also illustrates how this capability is used.

Add optional context argument to parse_class template function.

---

src/c4/ParallelUnitTest.cc

+ Any unit test that is based on c4's ParallelUnitTest can now be given the command line argument '-p'.  This option will pause the program after MPI_Init to allow the developer to attach a debugger to the process before the program continues. This can be useful when debugging code on platforms that do not have a MPI-aware debugger.

Add new 'pause' command line option for ParallelUnitTest.

---

config/application_unit_test.py
config/compilerEnv.cmake
config/component_macros.cmake
config/windows-cl.cmake
src/viz/test/tstEnsight_Translator.py
src/viz/test/tstViz_Traits.cc

+ On Windows platforms, if `diff` is not available use `fc`.
+ Remove another reference to Cielito and Cielo.
+ Teach the build system to find the 64-bit version of winsock.dll when building 64-bit targets.
+ Explicitly cast data types.

Tweaks for Windows platforms (VS2017 and MSYS2).

---

environment/bin/bash_functions.sh
regression/draco_regression_macros.cmake

+ This will reduce the load on ccscs7 when many PRs are being tested simultaneously.
+ Also sneak in a new bash function 'parse_git_branch'.  This allows developers to include the git branch name in their user command prompt for directories that contain a git repository.  For example:
```
export PS1="\[\033[34m\]\h:\[\033[32m\]\$(npwd)\[\033[35m\]\$(parse_git_branch)\[\033[00m\] [\!] % "
cd $HOME/draco
ccscs7:~/draco (regress-scripts) [1007] % 
```

Restrict how many valgrind jobs are run simultaneously by regress

---

src/roots/fdjac.hh

The fdjac function template has a Require check, but the ds++/Assert.hh header is not included in the file.

Add missing header for DBC check.

---

.travis-install-dependencies.sh
.travis-run-tests.sh
.travis.yml
config/unix-intel.cmake
src/ds++/test/test_fpe_trap.py

+ For Intel compilers, revert fp-model to precise instead of fast. There will be a small performance hit, but this makes the KNL's behave more like the Haswell chipset.
+ For the CI on Travis, if ctest returns non-zero (if one or more tests failes), rerun the failed tests with full verbosity (`-VV`).
+ refs #835

One more attempt at fixing fpe_trap on KNL (optimized) and Travis.

---

config/setupMPI.cmake
environment/bashrc/.bashrc
environment/bin/bash_functions.sh

+ Revert flags passed to mpirun for OpenMPI 1.10.  Recent fixes found in openmpi/1.10.5 make these flags unnecessary.
+ Change developer environment to prevent the creation of core files.
+ Add a new bash function, `qrm` (quick remove).  On Lustre scratch filesystems, use this function to move directories to a _trash_ folder instead of using `rm -rf`.  The recursive remove operation is very slow on Lustre, the new function is very fast and it let's the system's garbage collection system complete the remove operation.

Cleanup development environment

---

config/unix-intel.cmake

+ Except for KNL, where we use `-fp-model precise` to preserve numerical behavior that produces consistent results with Haswell.
+ refs #835

Revert to '-fp-model fast' for Release builds that use Intel C++.

---

config/setupMPI.cmake

+ For our testing system, begin using the `-F shared` option for aprun. Recent changes to aprun require this new flag to continue allowing multiple concurrent jobs to run on a shared node.
+ Notes from HPC email:
+ Ticket Link: https://itsm.sandia.gov/arsys/servlet/ViewFormServlet?form=HPD%3aHelp%20Desk&server=itsm-ars-prod&eid=INC000001311624
+ Rob Cunningham: _I believe the workaround was to grab two nodes and then it worked.  Led to the MAPN assumption; lots of things started working when going from 1 node to 2 (leaving the second unused):  CCM, thread placement, rank placement, apps crashing, etc.  Anyone remember this one, the Ptag issue, is there a ticket number?_
+ Mike Berry:
> We finally got the patch that …

Update options provided to aprun on Cray machines.

---

CMakeLists.txt
config/platform_checks.cmake
config/query_fma.cc
config/unix-g++.cmake
config/windows-cl.cmake
src/diagnostics/draco_info.cc
src/diagnostics/draco_info.hh
src/ds++/FMA.hh
src/ds++/config.h.in
src/ds++/test/tstFMA.cc
src/ds++/test/tstFMA2.cc

+ Add a cmake function, query_fma_on_hardware (called by `CMakeLists.txt`) that will determine if the local hardware supports fused multiply-add.  This function uses CMake's try_run commands to compile and run a program that derives from an example provided by Intel (`config/query_fma.cc`). The program returns 1 if FMA is supported on the hardware. 
+ Add an FMA macro that controls fma behavior. This is used in Jayenne to improve numerical reproducibility between machines. In general, new machines use hardware provided FMA that is more accurate than math performed on older hardware. To improve numerical reproducibility, this macro can be used to call a high precision multiply+add operation.  The downside, is that this higher precision call can be very expensive.
+ The behavior of the new …

Provide FMA macro to simulate more accurate math on older machines.

---

config/windows-cl.cmake

+ The `/arch:AVX2` compile option was generating 'invalid instructions' from within RNG.
+ Move option `/Gm` from the general flags to Debug builds. It is typically used alongside `/Zi`.

For now, disable AVX2 instructions for Win32 builds.

---

config/unix-g++.cmake

+ `CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` only works with Intel, so we still need to manually add the `-lfto` compile flag for GNU-based Release builds.
+ Because this options doesn't work correctly with GNU 4.8.5, restrict its use to GNU 5+.
+ Shuffle some assignment operations around to simplify the code logic.
+ Remove the use of `-std=` compile flags. Use the CMake options `CMAKE_C[XX]_STANDARD` instead.
+ Make use of `string(APPEND ...)` to simplify logic.
+ [Redmine #872](https://rtt.lanl.gov/redmine/issues/872)
+ This change should resolve the 24 failing tests on ccscs2 and ccscs7 (Release builds).

GCC's -flto doesn't work correctly with GNU 4.X compilers.

---

config/unix-intel.cmake

+ The Intel compilers only generate FMA hardware instructions if the compiler is told to generate AVX2 or later features. `-xHost` chooses the correct architecture based on the current machine.
+ This flag will not be enabled on Cray machines. The Cray compile wrappers will set this flag based on the currently loaded modules. Also using `-xHost` breaks cross compiling for KNL.
+ This change addresses the two dozen Jayenne tests that are failing on snow.

Re-enable Intel compiler flag '-xHost'.

---

src/ds++/Packing_Utils.hh
src/ds++/test/tstPacking_Utils.cc

+ An integer overflow bug was discovered in this header when used by Jayenne.  When packing enough IMC particles, the `end_ptr` could exceed 2^31-1 causing a integer overflow and eventually a software crash.
+ This change is based on a patch provided by Matt Cleveland.  All pointer arithmetic will now use `uint64_t` data types.  In most existing cases, regular C 'int' types will be promoted to `uint64_t` without issues.

Change Packing_Utils to use 64-bit integers to prevent overflow.

---

src/c4/ParallelUnitTest.cc
src/c4/ParallelUnitTest.hh
src/ds++/ScalarUnitTest.cc
src/ds++/ScalarUnitTest.hh
src/ds++/UnitTest.cc
src/ds++/UnitTest.hh
src/ds++/test/tstScalarUnitTest.cc

This new feature addresses the problem of finding the one failing test among a slew of pass messsages for a test code that does many checks. 
By default this option is off, so existing behavior is unchanged. When this option is turned on, messages are generated by UnitTest::check only if the bool argument is false (meaning the test failed.) This can be extremely useful for debugging a test executable that has many check calls in it.

Add option to UnitTest to suppress pass messages in UnitTest::check

---

regression/ccscs-crontab
regression/push_repositories_xf.sh
regression/regression-master.sh
regression/sn-crontab
regression/sn-job-launch.sh
regression/sn-regress.msub
regression/sync_repository.sh
regression/sync_vendors.sh
regression/tt-crontab
regression/tt-job-launch.sh
regression/tt-regress.msub
regression/update_regression_scripts.sh

The initial goal of this work was to prevent two simultaneous CI instances of the same PR.  However, after working through several potential solutions it has resulted in a bigger set of changes as detailed below. refs #841
+ Begin running nightly tests and PRs on snow. Also teach the snow regression scripts to use qos=dev and to use all 36 cores on each node.
+ Use `flock` to prevent some scripts from having more than one concurrent instance. Also add some job control cleanup to the end of these scripts. `flock` doesn't seem to work well with if the log file (on a NFS mount) is used as the locking file.  Instead I create an empty file at /var/tmp. This mechanism now is used in these files:
+ regression-master.sh
+ sync_repository.sh
+ sync_vendors.sh
+ Teach some scripts to capture and …

Significant update to regression scripts.

---

src/parser/test/tstutilities.cc
src/parser/utilities.cc
src/parser/utilities.hh
src/quadrature/Quadrature__parser.cc
src/quadrature/Quadrature__parser.hh

Ensure that destructor of `Class_Parse_Table<Quadrature>` releases the parsed quadrature in a timely manner. Previously the parsed quadrature would not be released until general end of execution cleanups or until another quadrature was parsed.
Provide a way to free the global pointer to the internal unit system. I'm not sure why this is implemented as a raw pointer rather than a `shared_ptr,` but the ability to free this storage manually would be useful even if it were implemented as a` shared_ptr.`

Ensure timely deallocation of parser resources.

---

config/query_fma.cc

GCC on Mac does not recognize xgetbv.
Executable with updated query_fma (compiled with clang) produced no difference with original.
The patch was found here: https://github.com/asmjit/asmjit/issues/78

Convert xgetbv to equivalent machine code in query_fma.

---

src/cdi/CDI.hh

* This pull request changes how Planck2Rosseland factor is calculated, using a std::expm1(x) which is accurate even for small (x), refs #2 (882)

Use std::expm1() in conversion from Planck to Rosseland.

---

src/quadrature/Product_Chebyshev_Legendre__Parser.cc

Quadratures with an odd number of azimuthal angles should cause a parser error.
Previously, error only occurred in DBC check, which is often turned off in
release.
* Increase robustness when no DBC checks are used by adding parser check

Adding parser check to ensure even azimuthal order

---

src/c4/C4_Functions.hh
src/c4/C4_MPI.t.hh
src/c4/C4_MPI_blocking_pt.cc
src/c4/C4_Serial.hh
src/c4/test/tstPingPong.cc

I have run into situations in my code where this seems the best operation for what I want to accomplish.

Add C4 interface for MPI_Sendrecv function.

---

src/compton/Compton.cc
src/compton/test/tCompton.cc

* This pull request should increase test coverage for Compton.hh to 100%. It also removes an unneeded include from Compton.cc.

Compton: Remove an unneeded include and improve test coverage

---

environment/bashrc/.bashrc_linux64
regression/ccscs-regress.msub

This pull request adds "module load csk" to the ccscs[1-9] bashrc file (.bashrc_linux64) and the regression launch script (ccscs-regress.msub).
Right now, csk is built for four compiler versions: gcc-4.8.5, -5.3.0, -6.1.0, and clang-3.9.0.
* Add automatic loading of csk module on ccscs machines
* If all goes well, this should close Jayenne redmine task #869 

Update bashrc and regression launch scripts for ccscs machines 

---

src/c4/Processor_Group.hh
src/c4/Processor_Group.i.hh

The random access container must conform to the C++11 conventions for such a container. In particular, the value_type must be defined and &x[0] must return a pointer to T pointing to the beginning of the raw storage underlying the container.
This is needed to support use of Teuchos::ArrayView and Teuchos::ArrayRCP in the Capsaicin project.

Extend c4::Processor_Group::sum to any random access container.

---

environment/elisp/draco-mode.el

+ For some reason the divider lines were one character shorter than the
clang-format line length (80 chars). Fix it.

For Draco's Emacs mode, make divider lines one char longer.

---

config/compilerEnv.cmake

+ Only tested on ccs-net machines.
+ `ccache` is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again.
+ Currently, we recommend the following content for `~/.ccache/ccache.conf`
```
max_size = 30.0G
cache_dir = /scratch/ccache
umask = 0002
```
+ This PR also adds code to set SITENAME to a pretty string for Snow, Fire and Ice and removes a reference to Cielito.

Add support for ccache.

---

environment/git/pre-commit-clang-format

Exclude Fortran header files (ending in _f.h, _f77.h, _f90.h) from
pre-commit-clang-format hook's scrutiny.
Fortran header files in dependent projects get bad formatting recommendations from the clang formatting requirements.  According to @jhchang-lanl, these files should be excluded from the list of valid extensions for pre-commit hook parsing. 

Exclude Fortran header files (ending in  _f.h, _f77.h, _f90.h) from clang formatting.

---

config/setupMPI.cmake
config/unix-g++.cmake
src/RTT_Format_Reader/test/TestRTTFormatReader.cc
src/ds++/test/tstFMA.cc
src/norms/L2norm.i.hh
src/norms/L2norm_pt.cc

+ For KNL, set
```
MPI_CORES_PER_CPU = 17
MPI_PHYSICAL_CORES = 4
MPIEXEC_MAX_NUMPROCS 68
```
+ For g++, test if option -Wunused-macros is available.
- If so, use it.
- Clean up some code that had unused CPP macros.

Provide MPI information for KNL and some new GCC compile flags.

---

config/application_unit_test.py

+ Use Popen call to capture stderr instead of piping to stdout
+ Label and print stderr and stdout in the event of test failure
* I was getting test failures and the application unit tester in python had an error and did not print the error stream correctly

Capture stderr correctly in python unit tester

---

environment/bashrc/.bashrc
environment/bashrc/.bashrc_toss3

+ Load all modules as a single module command instead of loading each separately.
+ Do not create core files by default. Uncomment the 'ulimit' command or run it on the command line to allow core files to be created for specific cases (e.g. to allow debugging of a core file).

Make processing of .bashrc faster for LMOD.

---

config/application_unit_test.py

+ PR #193 changed the way Application Unit Test parsed line-endings.
+ This change didn't account for the different formats used for Linux, '\n' and Windows, '\r\n'.
+ Add an optional parameter for subprocess.Popen to tell Python to do the right thing.
+ Ref: https://docs.python.org/2/library/subprocess.html

Fix a bug that caused python to use wrong line-endings on Windows.

---

config/unix-g++.cmake
environment/bashrc/.bashrc
environment/bashrc/.bashrc_linux64
src/ds++/CMakeLists.txt
src/rng/Rnd_Control_Inline.hh

* Add draco developer environment for toolbox (VENDOR_DIR, modulefiles, etc.)  This commit is specifically for toolbox, but should also work for other Linux machines on the XCP network.

Environment and build system changes to support XCP machine 'toolbox.'

---

config/buildEnv.cmake
config/compilerEnv.cmake
src/CMakeLists.txt

+ When running cmake, developers can now specify:
```
-D C_FLAGS="whatever"
-D CXX_FLAGS="whatever"
-D Fortran_FLAGS="whatever"
-D EXE_LINKER_FLAGS="whatever"
```
+ Or, before running cmake, developers can set these variables in the local environment:
```
export C_FLAGS="whatever"
export CXX_FLAGS="whatever"
export Fortran_FLAGS="whatever"
export EXE_LINKER_FLAGS="whatever"
```
+ With this PR, the Draco build system will look for both of the above add these flags to the default set.
+ Default to `DRACO_DBC_LEVEL=15` for `RelWithDebInfo` builds.
+ [Refs #896](https://rtt.lanl.gov/redmine/issues/896)

Make it easier to set compile and link flags.

---

.travis.yml
src/c4/C4_Functions.hh
src/c4/C4_MPI.t.hh
src/c4/C4_MPI_blocking_pt.cc
src/c4/C4_Serial.hh
src/c4/Invert_Comm_Map.cc
src/c4/c4_mpi.h
src/c4/config.h.in
src/c4/test/tstReduction.cc

+ The MPI scan function calculates a prefix sum (often used in determining offsets in parallel problems) without forming a n_proc length array on every node.
+ Templated prefix_sum function was added to the "blocking" section of the C4 library
+ A section for prefix_sum was added to the "tstReduction" test
* Address Jayenne #892 (https://rtt.lanl.gov/redmine/issues/892)

Add prefix sum function to C4 library

---

README.draco
config/compilerEnv.cmake
environment/bashrc/.bashrc
environment/bashrc/.bashrc_linux64
regression/alist.sh
regression/ccscs-crontab
regression/ccscs-job-launch.sh
regression/ccscs-regress.msub
regression/checkpr.sh
regression/draco_regression_macros.cmake
regression/ml-job-launch.sh
regression/ml-regress.msub
regression/pull_repositories_xf.sh
regression/regression-master.sh
regression/scripts/common.sh
regression/scripts/common_slurm.sh
regression/sn-regress.msub
regression/sync_repository.sh
regression/tt-job-launch.sh
regression/tt-regress.msub
src/parser/Debug_Options.cc

+ Update README with basic instructions for building draco.
+ Require that C++11 features be availble.
+ Fix typo in .bashrc (extra '2' as the first character in the file).
+ Rework the alist.sh function to be more representative of the way we did things under subversion. This script provides a list of code authors based on who most recently touched each line of code.
+ No longer run nightly testing on ccscs7 for belosmods, gcc530 or bounds-checking.
+ Use the 'fn_exists' bash function in the scripts to simplify some logic.
+ Simplify some bash logic (especially if-tests).
+ Fix a bug in sync_repository.sh that prevented CI tests from starting for Jayenne and Capsaicin.
+ Modify Debug_Options.cc to prevent a build warning about an unused local-file-scope function. …

General clean up in Draco (mostly bash scripts).

---

src/c4/C4_Functions.hh
src/c4/C4_MPI.t.hh
src/c4/C4_MPI_blocking_pt.cc
src/c4/test/tstReduction.cc

* I need unsigned longs for Jayenne and I forgot to add those in the last commit
* The type signature needs to accept const variables and does not need to be a reference so I changed the signature
* Added a test for unsigned long in tstReduction.cc
* Fix Jayenne issue #892 (https://rtt.lanl.gov/redmine/issues/892)

Add prefix sums for unsigned longs

---

environment/bashrc/.bashrc

+ Things work better if we set the environment variable `DRACO_ENV_DIR` before we try to use it.  Kodos to Jae for finding this bug.
+ [Ticket-913](Refs https://rtt.lanl.gov/redmine/issues/913)

Fix a bug in Draco's .bashrc.

---

config/component_macros.cmake
config/setupMPI.cmake
regression/draco_regression_macros.cmake
regression/tt-job-launch.sh
regression/tt-regress.msub

+ Remove some code that was specific to aprun.
+ Update commands used when registering tests.  On Cray machines, we will now use: `${MPIEXEC} ${MPIEXEC_POSTFLAGS} -n <num_tasks>`, where
`MPIEXEC = srun`, and 
`MPIEXEC_POSTFLAGS` is set by setupMPI.cmake.
We are still trying to establish the correct options list provided by `MPIEXEC_POSTFLAGS`. Currently, we use `--exclusive`, but we might want to consider `-N 1 -c 1 --mem=1400m`.
+ Add some additional setup and checks in the regression system for trinitite.  It seems that shell scripts started by cron aren't getting the default set of Cray modules unless extra work is done (source /etc/bash.bashrc.local)
+ For LANL HPC, use sys_name to fill the sitename string.
+ [Refs Redmine #903](https://rtt.lanl.gov/redmine/issues/903)
* [Pre-Merge …

Second update to provide support for slurm on Cray machines (trinitite).

---

CTestCustom.cmake
README.md
config/buildEnv.cmake
config/setupMPI.cmake
config/unix-clang.cmake
environment/bin/bash_functions.sh
regression/valgrind_suppress.txt
src/compton/test/CMakeLists.txt
src/parser/Debug_Options.cc
src/parser/Debug_Options.hh
src/plot2D/test/CMakeLists.txt

**Motivation**:
+ New Lmod modules will provide gcc/6.3.0 and openmpi/2.1.0 as defaults. We also have a new version of valgrind. This update eliminates some warnings that show up with the new tools.
+ Other unrelated cleanup is also included in this change set.
**Implementation**:
+ Significant change to `valgrind_suppress.txt` to address false positives reported by newer versions of gcc, openmpi, python, etc.
+ Register Draco's `valgrind_suppress.txt` file with cmake.    This allows developers to easily obtain valgrind test results from their build directories.
*Example:* `ctest -D ExperimentalMemCheck [-j 8 -R c4]`
+ Update author list shown on Draco's github page.
+ Retire some build system code designed for older versions of OpenMPI.  The minimum required version of OpenMPI is now 1.8 …

Cleanup to allow Draco to build cleanly with new tools.

---

config/buildEnv.cmake
config/compilerEnv.cmake

+ This change will allow developers to run the valgrind checks with the same suppression file that the nightly DA checks use.  For example:
```
ctest -D ExperimentalMemCheck [-j 12 -R c4]
```
+ Fixes #216

Make it easier to run valgrind checks.

---

config/setupMPI.cmake
regression/draco_regression_macros.cmake

Along with the transition of MOAB to Slurm on trinitite, the consultants have also changed the way jobs are bound to KNL processors and have turned on hyperthreading on the KNL nodes.  This was causing our regressions to crash because 272 MPI ranks worth of tests were starting simultaneously.  Too many jobs running simultaneously and the fact that srun is not distributing the work correctly is causing many tests to time out.
This commit does not fix the underlying problem but it does provide a temporary work around.
1. Avoid a possible hang during the configure step related to 'discovering' MPI.
2. When on the KNL, only run 8 MPI ranks worth of tests simultaneously.
[Refs #903 (Redmine)](https://rtt.lanl.gov/redmine/issues/903) …

Modify regression settings to support slurm on knl.

---

environment/bashrc/.bashrc_linux64
environment/bin/bash_functions.sh

**Motivation**.
* All third party libraries and support vendors were regenerated using spack. This change simplifies the maintenance of vendor libraries and tools and allow spack to generate modulefiles instead of writing them by hand. See https://rtt.lanl.gov/redmine/projects/draco/wiki/Spack.
**Implementation**:
* The new developer environment uses
- Lmod modulefiles, https://lmod.readthedocs.io/en/latest/
- Defaults to gcc@6.3.0 and openmpi@2.1.0
- A vendor stack based on LLVM 4.0 is also available.
- Provides many additional/updated tools for developers to use.
* We no longer support 'belosmods' or '-bc' modules or regression testing.
**Checks**:

New developer environment for CCS-NET machines:

---

config/unix-g++.cmake
environment/bashrc/.bashrc_linux64
environment/bin/bash_functions.sh
src/c4/c4_mpi.h
src/diagnostics/Procmon.cc
src/diagnostics/draco_info.cc
src/ds++/DracoMath.hh
src/ds++/Homogeneous_New.cc
src/ds++/Homogeneous_New.hh
src/ds++/Soft_Equivalence.hh
src/ds++/SortPermutation.hh
src/ds++/SystemCall.cc
src/ds++/test/tstEndian.cc
src/ds++/test/tstFMA.cc
src/ds++/test/tstPacking_Utils.cc
src/ds++/test/tstSortPermutation.cc
src/ds++/test/tstdbc.cc
src/rng/Counter_RNG.hh
src/rng/Random_Inline.cc
src/rng/Random_Inline.hh
src/rng/test/time_initkeyctr.h
src/rng/test/time_misc.h
src/rng/test/time_random123.h
src/rng/test/time_serial.c
src/rng/test/ut_M128.cpp
src/rng/test/util.h
src/rng/test/util_expandtpl.h
src/rng/uniform.hpp

**Motivation**:
To improve code quality, it may be useful to increase the degree of warnings issued by the GNU compiler.  This commit updates Draco by improving the use of CPP macros.
+ Clean up CPP statements to pass new warning checks.  Change
```
if SYMBOL
to
if defined(SYMBOL)
```
+ In draco_info.cc, change
```
if DRACO_UNAME == Linux
to
ifdef draco_isLinux
```
+ Elminate a few cases where a double value is compared directly to another double w/o a soft_equiv.
+ Use a static cast to eliminate a warning about type conversion when using 'sizeof'.

Turn on GCC Warning '-Wundef'

---

src/ds++/test/cxx11example_move_semantics.cc
src/ds++/test/tstXGetopt.cc

This example shows how to use move semantics in object construction to avoid deep copies. Jayenne is adopting this type of coding to help us remove the use of smart_pointers and still avoid deep copies.

Add Tim's move semantics example.

---

src/ds++/ScalarUnitTest.hh
src/ds++/UnitTest.hh
src/ds++/fpe_trap.cc
src/ds++/test/CMakeLists.txt
src/ds++/test/cxx11example_move_semantics.cc
src/ds++/test/tstAssert.cc

Motivation:
+ Previously, we tested with VS2013.  However, the older version didn't have complete C++11 support.
+ Moving to the newer version requires a few tweaks to existing code and I haven't worked through issues related to linking against libraries generated with gfortran yet.
Implementation:
+ `fpe_trap.cc` needs a new include directive to ensure that `_ReturnAddress` is defined.
+ Update the `dsxx/test/CMakeLists.txt` to ensure that the build target for `do_exception` is associated with the `dsxx_test` solution folder.
+ In `cxx11example_move_semantics.cc`, eliminate the use of `&v[0]` for empty vectors.  Also, update the memory location function to eliminate the trailing comma that was printed at the end of a list of a vector's values.
+ Refs #225 (GitHub) …

Updates to allow compilation under Visual Studio 2017

---

src/c4/Invert_Comm_Map.cc
src/c4/test/tstC4_Status.cc

* Cleanup of Invert_Comm_Map PR to get rid of warnings under optimization.
* tstC4_Status now uses any_source (Alex's suggestion)

Invert_Comm_Map cleanup of warnings under optimization

---

regression/win32-regress.bat
regression/win32-regression-master.bat

**Motivation:**
+ We previously used Visual Studio 2013 for this testing.  However, VS2013 did not provide complete support for C++11 and our codes would no longer compile w/o better C++11 support.
**Implementation:**
+ Installed Visual Studio 2017 Community Edition (free for non-commercial software).
+ Update regression scripts to use the new tool set. Source the vcvarsall.bat provided by VS2017 from win32-regress.bat.
+ fixes #225

Begin using Visual Studio 2017 for Win32 nightly regression testing.

---

config/setupMPI.cmake
environment/bashrc/.bashrc_tt
src/ds++/UnitTest.hh

+ Unit tests will be run on the back-end under srun with these options:  ```srun -n 4 -N 1 --cpu_bind=cores --gres=craynetwork:0 --exclusive <app>```
+ Set `OMP_NUM_THREADS` to 16 for Trinitite/Haswell and 17 for Trinitite/KNL.
+ Fix formatting issues related to comment blocks in `UnitTest.hh.`

Update srun parameters for Cray+Slurm environments at LANL.

---

regression/valgrind_suppress.txt

* Suppress errors that occur in thread initialization with the OpenMPI library
* This valgrind suppression is specifically for PR 99 of the Jayenne project (https://gitlab.lanl.gov/jayenne/jayenne/merge_requests/99)

Updated Valgrind suppressions

---

regression/checkpr.sh
regression/draco_regression_macros.cmake
regression/ml-job-launch.sh
regression/sn-job-launch.sh
regression/tt-job-launch.sh
src/ds++/UnitTest.hh

+ Add a knl build to the CI testing system.
+ Change how the number of processors available for running tests is set when using a Cray system.  We now use `lscpu` to look at the number of sockets and the number of cores per socket.
+ Set the slurm job name to be representative of project name and the pr number.
+ Clean up indentation of documentation in UnitTest.hh.
+ This PR captures code that is already _live_ at `/usr/projects/jayenne/regress`.

A few small changes to the regression/CI scripts.

---

environment/vim/.vimrc

* This pull requests adds an 80 column warning line to the vim format file
* Technically the line is set at 81 columns so you can write all the way to the line

vim formatting to set a warning line at 80 columns

---

src/rng/test/tstCounter_RNG.cc
src/rng/test/tstRnd_Control_Inline.cc

+ There were two rng tests that were failing if `DBC=15` (Design-by-Contract is on, but no exceptions are thrown). `DBC=15` is the default setting for `RelWithDebInfo` builds.
+ I corrected the logic in these two tests for this special case.
+ fixes #877 (Redmine)

Fix test logic in the rng package for DBC=15 builds.

---

regression/ccscs-crontab
regression/ccscs-job-launch.sh
regression/ccscs-options.sh
regression/ccscs-regress.msub
regression/checkpr.sh
regression/darwin-job-launch.sh
regression/metrics_report.sh
regression/ml-job-launch.sh
regression/ml-options.sh
regression/regression-master.sh
regression/scripts/common.sh
regression/sn-job-launch.sh
regression/sn-options.sh
regression/sync_repository.sh
regression/sync_vendors.sh
regression/tt-job-launch.sh
regression/tt-options.sh

This pull request consists of code that is currently active in the active regression script directory on ccscs7.  These changes focus on reducing code duplication and simplifying maintenance.
+ Update crontab that runs the `metric_report.sh` monthly to fix a bug (a missing escape). Also update the comments that indicate to whom the report should be delivered.
+ Delay the start of the coverage and valgrind regressions to provide more time for the Release regressions to finish.
+ Create two new bash functions in scripts/common.sh: `job_launch_sanity_checks` and `print_job_launch_banner`.  Call these functions from the `<machine>-job-launch.sh` scripts instead of maintaining identical coding in several files.
+ Abstract out some information previously found in `regresssion-master.sh` so that …

Implement improvements for the CI system on ccscs7

---

src/compton/test/CMakeLists.txt
src/compton/test/tCompton.cc

+ No need to copy the files to the build directory.
libcompton only exists on ccs-net machines so don't require testing on toss2, toss3 or cray.

Update Compton test to use input files found in the source directory.

---

config/buildEnv.cmake
environment/bashrc/.bashrc_rfta
environment/bashrc/.bashrc_tt
regression/alist.sh
regression/scripts/common.sh

+ Fix issue related to RelWithDebInfo builds (`buildEnv.cmake`).
- inconsistent use of case (`RelWithDebInfo != RELWITHDEBINFO`) was causing some confusion.  Change build system logic to force this string to all upper case before using its value in a conditional.
+ On redcap and cray machines, add `$VENDOR_DIR/bin` to the `PATH`.
+ On redcap, if available, use `~/modulefiles` instead of `user_contrib`.
+ Minor cleanup in `alist.sh`.  No changes to logic.
+ Update the bash function `selectscratchdir` function defined in `common.sh` and used by the release scripts.
- When trying to locate a valid scratch directory, don't use *netscratch* unless all other scratch spaces fail the checks.
- When trying to locate a valid scratch directory, ensure the directory isn't read-only. …

Miscellaneous improvements to environment, build system and scripts.

---

regression/mcovdir.cfg
regression/metrics_report.sh

+ This script is used to generate a monthly email report of LOC and code coverage. With the addition of subdirectories under main package directories (not including test/, which is excluded from code coverage reports).
+ The format of the report has been off for packagas that have subdirectories (e.g. diagnostics/qt). Additionally, the coverage numbers of these subdirectories are already included by their parent and shouldn't be reported again on their own.
+ Update the script to remove these extra lines from the final report.
+ Also change the sort order to be alphabetic instead of by percent covered. This makes it easier to update the historical per-release data that we collect.
+ Also update the module system to use Lmod-based modules on ccscs7.
+ fixes #964
+ [Pre-Merge Code …

Cleanup the output from Draco's metric_report.sh script.

---

config/ApplicationUnitTest.cmake
environment/bashrc/.bashrc_tt
regression/tt-job-launch.sh
src/cdi_eospac/CMakeLists.txt
src/cdi_eospac/test/CMakeLists.txt
src/diagnostics/CMakeLists.txt
src/diagnostics/test/CMakeLists.txt
src/diagnostics/test/tDracoInfo.py

**The problem:**
When unit tests are executed on Trinitite/Trinity, all tests (including scalar) tests must be run under srun.  To enable packing multiple parallel running jobs onto a single node extra options must be provided to srun (i.e.: `--cpu_bind=cores --gres=craynetwork:0 --exclusive`).  These extra flags were not being used by auxillary programs (like numdiff) for ApplicationUnitTests.
**The fix:**
Replace logic that triggered on `$MPIEXEC == aprun` with logic that turns on for `$MPIEXEC == srun`.  Currently, this logic only applies to Trinity and Trinitite.  This new conditional code block adds $MPIEXEC_POSTFLAGS to the run command.
* Also clean up documentation in some CMakeLists.txt files and in `DracoInfo.py.`
* Refs Github #236 and [Redmine …

On Cray systems, ensure that ApplicationUnitTest uses correct srun options.

---

src/cdi/CDI.cc
src/cdi/CDI_Integrate_Rosseland_Planckian_Spectrum.cc
src/cdi/CDI_integratePlanckSpectrum.cc
src/cdi/test/tCDI.cc
src/cdi_analytic/Pseudo_Line_Base.cc

I inadvertantly introduced a bug into CDI when I replaced:
```
if (T == 0.0 )
```
with
```
if (soft_equiv(T,0.0,numeric_limits<double>::epsilon())
```
This check is needed to avoid a division by zero.  However, in CDI `T` is almost always < epsilon() because of the unit system. Thus, the Planck and Rosseland integrator functions were returning earlier than they should have.  The fix in this PR is to use the conditional
```
if ( T < max(nu) * numeric_limits<double>::min() )
```
which should guarantee that `nu/T < numeric_limits<double>::max()`.  Also add a test for very small values of T.
* Fixes #252

Fix a bug introduced in #252 (early return if T==0).

---

src/c4/Global_Timer.cc
src/c4/Global_Timer.hh
src/c4/Timer.cc
src/c4/Timer.hh

The existing implementation returned statistics only for processor 0 unless you went through gyrations that pretty much missed the whole reason for using Global_Timer rather than just Timer. The new implementation returns means and deviations for all non-PAPI statistics across processors.
The new implementation also produces a warning message if timers you request to be active are never found during the run. The warning message tells you what timers were found that were not active, which can be very useful for figuring out what timer you really wanted, or where a new timer should be inserted in the code.

Rework Global_Timer to be more useful in parallel runs.

---

src/rng/test/CMakeLists.txt
src/rng/test/time_serial.h
src/rng/test/util.h

+ Mark another file taken from Random123 as a "GCC system_header".  We are not interested in warnings emanating from code that we did not write.
+ Fixes #259.

Eliminate warnings reported by ccscs7, gcc-coverage builds.

---

src/ds++/Soft_Equivalence.hh
src/ds++/test/tstSoft_Equiv.cc

+ Use `std::enable_if` to prevent the definition of `soft_equiv` for integral types.
+ Eliminate template specializations for integral types.  These are signatures are no longer allowed.
+ Allow the check to pass if the difference is subnormal.
+ Eliminate tests that try to use soft_equiv on integral types.  This code will no longer compile.
+ Eliminate some ifdefs that were checking for C++11 features.  We now assume that these features are always available.

Improve soft_equiv by using C++11.

---

src/compton/Compton.cc

This DBC check is flawed -- it was checking the 'base' filename, when the actual library files have suffixes appended. Thus, it throws an assertion even if the library files exist.
I should add that the CSK library will still throw an assertion if the file doesn't exist, and that this is tested in tCompton.
(Thanks @attom for pointing this out! :))
* Fix a DBC bug preventing draco Compton class from working properly

Remove a bad DBC check in the Compton class

---

config/unix-clang.cmake
environment/bashrc/.bashrc_linux64
regression/valgrind_suppress.txt
src/c4/Timer.cc
src/plot2D/Plot2D.cc
src/plot2D/test/tstPlot2D.cc

+ On ccs-net machines, force the default draco developer environment to load `superlu-dist/4.3-netlib` instead of the default `superlu-dist`.
+ Add a valgrind suppression related to OpenMPI 2.1.0.
+ In c4's `Timer.cc`, use `static_cast` to convert from `double` to `unsigned`.  Also add DbC checks to ensure the conversion is valid.
+ In `Plot2D.cc`, collect and check the return code from `fgets` and `system`.
+ Clean up comment blocks.

Cleanup some warnings that have crept into some of the non-CI builds.

---

regression/ccscs-regress.msub
regression/checkpr.sh
regression/regression-master.sh
regression/scripts/common.sh
regression/sn-job-launch.sh
regression/sync_repository.sh

+ `ccscs-regress.msub`:
- On ccscs7, set `OMP_NUM_THREADS=8`
- Force loading superlu-dist/4.3.to avoid loading 5.X.
- Add `$featurebranch` to the build name.
+ Prevent `checkpr.sh` from running on ccscs7 unless run by the regress account. This should reduce the load on ccscs7.
+ Move *fulldiagnostics* CI build from moonlight to snow.
+ Begin running a *Release* CI build on snow.
+ Improve how `selectscratchdir` works.
+ Reactivate the repository synchronization used by Redmine.

Commit changes that are *hot* in the current regress directories.

---

environment/bashrc/.bashrc_linux64
regression/scripts/common.sh
src/ds++/UnitTest.hh
src/ds++/config.h.in

+ Update `.bashrc_linux64` to take advantage of the fact that LMOD modulefiles are now the default on ccs-net machines (thanks to Dan Pruitt). This simplifies the logic needed to make available the tools available at `/scratch/vendors` via the module system.
+ Update the install scripts to use the group `ccsrad` when installing Jayenne and Capsaicin. Only members of this group will be able to access installed sources and libraries. If `ccsrad` isn't available, the script will try to use the group `dacodes` and then `jayenne`. Draco will still be installed as group `draco` with world read permissions.
+ Provide new CPP macro helpers that can be used in our Unit Tests:
- `FAIL_IF(c)`
- `FAIL_IF_NOT(c)`
+ When building on Win32, define `__PRETTY_FUNCTION__` in a way that produces similar …

Here are four small tweaks to Draco.

---

src/CMakeLists.txt
src/ds++/test/tstFMA2.cc
src/quadrature/Galerkin_Ordinate_Space.cc

+ For GCC 5.0 or later, Debug builds, enforce the compiler options `-Wfloat-equal -Wunused-macros` to prevent reintroduction of direct floating point number comparisons or unused macros.
+ These flags will only apply to Draco.  They will not be inherited by Jayenne or Capsaicin.
+ Remove an unused macro from `tstFMA.cc` and some direct comparisons of floating point numbers in a quadrature test (also fix formatting of comment blocks).

Enable compiler flags `-Wfloat-equal -Wunused-macros`

---

src/VendorChecks/test/tstSuperludist.cc

* The API in SuperLU-DIST changed between version 4 and 5.  Update the Draco unit test `tstSuperludist.cc` to work with either version of SuperLU-DIST.
* Also tell git to ignore `.nfs*` files found in the source tree.
* Fixes #275

Allow tstSuperludist.cc to link to superlu-dist-5+

---

.gitignore
environment/bashrc/.bashrc_linux64
environment/elisp/draco-mode.el

+ Tell git to ignore temporary `.nfs*` files.
+ Add new keywords `FAIL_IF` and `FAIL_IF_NOT` to emacs colorization list.
+ Make use of ccs-net's `user_contrib` module to point to `/scratch/vendors/Modules.lmod` and `/scratch/vendors/Modules.core`.

Minor tweaks to the developer environment for ccs-net machines.

---

.travis-install-dependencies.sh
.travis-run-tests.sh
.travis.yml

* Update the travis control scripts to use newer tools like gcc-6 and openmpi-1.10.5.
* Fixes #282 
* Fixes #281

Update Travis to use newer tools.

---

.clang-format
config/FindCOMPTON.cmake
config/vendor_libraries.cmake
src/compton/CMakeLists.txt
src/compton/Compton.cc
src/compton/Compton.hh
src/compton/config.h.in

This change set upgrades CSK to a full Draco TPL and publishes it via the installed `draco-config.cmake` file.
+ Add the compton package to the `.clang-format` list of Draco packages (for sorting of header files).
+ Complete rewrite of `FindCOMPTON.cmake` makes use of target properties instead of environment and cmake variables.
+ Move the discovery of compton from `src/compton/CMakeLists.txt` to `config/vendor_libraries.cmake`
+ Always install a *compton* package when building Draco.  If the CSK library is not found, the installation will be a stubbed out `Compton.hh` file and no library.
+ A `compton/config.h` file has been added to capture the CPP macro `COMPTON_FOUND`. Include directives for CSK files were moved to this new file. This mimics the way we treat other TPLs like Random123 …

Upgrade how the Compton TPL is discovered, presented and used.

---

.travis.yml

+ Disable upgrading setuptools as possible bug workaround.
+ Increase wait time for building openmpi.
+ Fixes #293 

Tweak Travis CI settings

---

regression/ccscs-crontab
regression/ccscs-job-launch.sh
regression/ccscs-regress.msub
regression/ccscs6-crontab
regression/checkpr.sh
regression/ml-crontab
regression/ml-job-launch.sh
regression/ml-regress.msub
regression/push_repositories_xf.sh
regression/regression-master.sh
regression/sn-job-launch.sh
regression/sync_repository.sh
regression/sync_vendors.sh
regression/tt-regress.msub
regression/update_regression_scripts.sh
src/CMakeLists.txt

+ Update `push_repositories_xf.sh` to force its output to go to a specific log file.
+ Begin marking source code with group 'ccsrad'
+ Start running valgrind on ccscs6 and coverage on ccscs7 to distribute the test load.
+ Allow anyone to run `checkpr.sh` on ccscs7.  This was blocked to reserve the machine for `checkpr.sh` testing. Fixes #281 (github).
+ Force the scripts to 'newgrp ccsrad' since I can no longer 'chgrp ccsrad'  (18th group).
+ Use new ssh keys for regression.
+ Reduce some code duplication.

Clean up the scripts that run on ccs-net machines.

---

src/parser/Token.cc
src/parser/Token.hh

Use return by const reference for access functions. This is more efficient and, in this context, quite safe.
Change check_class_invariants to check_class_invariant. A class really only has one invariant (the logical AND of all constraints on the internal state of the class object.)

Tweak parser code.

---

config/CMakeAddFortranSubdirectory.cmake
src/FortranChecks/CMakeLists.txt
src/FortranChecks/f90sub/CMakeLists.txt
src/ds++/DracoStrings.hh
src/parser/Parallel_File_Token_Stream.cc

+ Fix `DLL_PUBLIC` decoration of functions in `DracoStrings.hh`.
+ Fix invalid comparison of a bool: `if (b > 0)` in `Parallel_File_Token_Stream.cc`.
+ Provide better error reporting for Visual Studio builds that link to a MINGW version of the MPI library.
+ Documentation cleanup.

Fix build errors and warnings reported by VS 2017.

---

config/compilerEnv.cmake
config/unix-g++.cmake
environment/bashrc/.bashrc_linux64
regression/ccscs-regress.msub
src/cdi_ipcress/test/ReadOdfIpcressFile.cc
src/ds++/Assert.hh
src/parser/utilities.cc
src/rng/Counter_RNG.hh
src/rng/test/time_initkeyctr.h
src/rng/test/util_expandtpl.h
src/rng/uniform.hpp

+ Disable IPO for some CMake generators.
+ Add notes about new compiler flags and behaviors.  If GCC > 7.0, then
- Enable `-fsanitize=signed-integer-overflow` for Debug builds.
- Disable `-Wno-expansion-to-defined` that is now part of `-Wextra`.  These
warnings show up in Random123 and cannot be disabled by pragmas.
+ Update `.bashrc` and regression scripts to use gcc/7.2.0.
+ Add 'break;' to case statements where control flow could fall through.

Prepare code for gcc-7.2.0.

---

config/unix-g++.cmake
regression/ccscs-regress.msub
regression/checkpr.sh

+ Fix a bug that was introduced into the nightly regression suite (ref #301) that manifests as 'no modules' available.
+ Add a '-t' option to checkpr.sh (used by the regression and PR testing scripts). Adding this option will force draco to rebuild and will be invoked when a draco PR is merged.
+ A compiler option for gcc/7.2.0 used to suppress warnings about possible CPP macro issues is moved from the C_FLAGS_DEBUG to C_FLAGS.
+ Fixes #302 

Fix broken nightly regressions.

---

regression/sync_repository.sh
regression/valgrind_suppress.txt

+ Suppress a new valgrind warning issued by openmpi/2.1.1.
+ Do a better job of detecting when draco/develop is updated and force draco to rebuild before the next jayenne or capsaicin PR testing.

More regression fixes.

---

regression/valgrind_suppress.txt
src/rng/Counter_RNG.hh
src/rng/uniform.hpp

+ When using LLVM clang to compile Draco on ccs-net machines, the CPP macro `#ifdef __GNUC__` was true (in addition to `#ifdef __clang__`).  This caused a logic error for the CPP macros that push, suppress warnings and pop for GCC and clang.  This problem was fixed by changing the `#ifdef __GNUC__` checks to `#if defined(__GNUC__) && !defined(__clang__)`.
+ Also suppress another valgrind warning for a TPL.
+ References #306
+ Fixes #309

Fix LLVM build warnings.

---

src/compton/test/CMakeLists.txt

* Quick fix -- I updated the Compton test in my last PR so I could query the MPI rank ID, but forgot to change the test registration to be parallel (the test has somehow been running/passing anyway).

Update Compton test registration from serial to one-proc parallel.

---

src/c4/Global_Timer.cc
src/c4/Global_Timer.hh

Minor tweaks to design by contract for Global Timer.
Eliminate use of NULL in favor of nullptr.
Turn an assertion back on that really ought to be satisfied.

Global timer

---

src/c4/C4_MPI_blocking_pt.cc
src/c4/C4_Req.cc
src/c4/C4_Req.hh
src/c4/C4_Serial.hh
src/c4/test/tstReduction.cc
src/c4/test/tstScalar.cc

+ While reviewing #280, I discovered that Draco no-MPI builds were broken.  This PR fixes `develop` for no-MPI builds and should be merged before #280.
+ Update function signature for `T prefix_sum` found in `C4_Serial.hh` to use the same argument types as the function of the same name found in `C4_MPI.hh`. This fixes the build error `call of overloaded function is ambiguous`.
+ Update `tstScalar.cc` to check the value of `request.complete()` instead of `request.count()` since the later member function no longer exists.
+ Clean up comments.

Allow c4 to build when DRACO_C4=SCALAR.

---

environment/bashrc/.bashrc_toss22
environment/bashrc/.bashrc_toss3
environment/bashrc/.bashrc_tt
regression/ml-regress.msub
regression/sn-regress.msub
regression/tt-regress.msub

+ Regression scripts updated to load csk.
+ Developer's `.bashrc` files updated to load csk:
```
module use --append ${VENDOR_DIR}-ec/modulefiles
module load csk
```
+ No longer load hugepages modulefile when developing on trinitite/trinity.

For HPC machines, add CSK to the dev env and regression system on HPC.

---

config/setupMPI.cmake
regression/ml-regress.msub
regression/sn-regress.msub
regression/tt-job-launch.sh
regression/tt-regress.msub

+ Updated ssh-keys used by the regression system since old keys were no longer valid.
+ Update sbatch and srun options for trinitite based on recommendations from ic-platforms team. Only use `--exclusive` on the srun command and only use `--gres=craynetwork:0` for the sbatch command.
+ Update some documentation.

Minor cleanup for HPC regression scripts.

---

src/parser/Token_Stream.hh

Remove a /bug note requesting a change that has now long been implemented.
Tweak some spelling while I'm in the neighborhood.

Remove old comments regarding change that has now long been implemented

---

src/c4/C4_MPI.t.hh

This is an important use case for Capsaicin. We fail numerous tests with the current checks.

Modify DBC checks to allow nullptr buffer arguments when size is zero.

---

src/VendorChecks/test/tstMetis.cc

+ This PR provides the metis portion of #320.  This should fix the failing tstMetis test when Metis expects 64-bit integers.
+ PR #320 is showing some MPI related failures, so I decided to provide the metis portion of it in this PR.

Fix for 64-bit metis.

---

src/parser/Parse_Table.cc
src/parser/Parse_Table.hh
src/parser/String_Token_Stream.cc
src/parser/Text_Token_Stream.cc
src/parser/Token.hh
src/parser/Token_Stream.cc
src/parser/Token_Stream.hh
src/parser/utilities.cc
src/quadrature/Gauss_Legendre__Parser.cc

This merge tightens up some of the parser code in Draco.
* Strings are reserved to their expected length before being constructed.
* A move constructor is provided for Token.
* A swap function is provided for Token, so that a Token can take over another Token's storage.
* The lookahead function for Token_Stream is changed to return a reference to const Token. This is safe: Token_Stream is built on std::deque, which preserves references until the referred element is popped. Thus a reference to lookahead tokens is safe until the token is shifted.
* Various parser code is modified to avoid unnecessary copies of Token or of Token::text or Token::lookahead.
* make_shared<T> is used in place of shared_ptr<T>(new T), which saves a memory allocation.
Some functions are flagged for their noexcept …

Tighten up the Draco parser code.

---

src/ds++/Thread_Wrapper.hh
src/ds++/test/tstThread_Wrapper.cc

+ This new class is based on Item 317 from Scott Meyers, "Effective Modern C++"
+ This PR replaces #317.
* PR #317 was pushed from Tim's `develop` branch and had some unwanted history and files, so I cherry picked the two *real* changes into a new feature branch to create this PR.
+  [Refs #982](https://rtt.lanl.gov/redmine/issues/982)

Add a thread_wrapper (work done by T. Kelley).

---

src/VendorChecks/test/tstMetis.cc

* Fix a memory error I introduced by making one array too long.

Fix a memory error in the metis test

---

config/vendor_libraries.cmake

* The name of the MKL thread library should be `mkl_gnu_thread` instead of`mkl_intel_thread`.
* Fixes [Redmine 1024](https://rtt.lanl.gov/redmine/issues/1024).

Fix compiling against MKL when using g++.

---

src/c4/C4_Serial.hh
src/c4/Invert_Comm_Map.cc

* An overload of the `prefix_sum` (`mpi_scan` wrapper) was missing from C4_Serial.
* The serial version of `get_num_recv` in Invert_Comm_Map had unused arguments.

Fix error and warning for scalar (or serial) builds.

---

src/ds++/Assert.hh
src/ds++/test/tstAssert.cc

Added the [[noreturn]] attribute to insist, insist_ptr, toss_cookies, and toss_cookies_ptr.
This potentially eliminates spurious warnings. See tstAssert.cc for an example of a function where a spurious "return with no value" warning is eliminated.

Add [[noreturn]] attribute to non-returning Assert.hh functions.

---

src/compton/Compton.cc
src/compton/test/tCompton.cc

* This PR adds a useful check to the data passed into Compton::Compton() to be sure that the set of multigroup build parameters is sensible.
* It also modifies the Compton test slightly to explicitly specify all of the variables (rather than relying on the defaults). 

Minor Compton DBC and test updates

---

regression/ccscs-crontab
regression/ccscs-regress.msub
regression/ccscs2-crontab
regression/ccscs6-crontab
regression/ml-crontab
regression/regression-master.sh
regression/sn-crontab
regression/tt-crontab

+ At the top of `regression_master.sh`, force the current group to be `ccscsrad`.
+ Update all crontabs to allow the above trick to work.  That is, double quotes must be escaped.
+ Simplify logic used to setup modules for regressions running on ccs-net machines.

Update regression scripts so they run as group ccsrad.

---

src/parser/Expression.cc

When a variable is not recognized, include the variable name in the message.
Change the rather obscure "unit incompatibility for -" to "unit incompatibility for - operator" since '-' has so many meanings.
These came up when I was trying to diagnose a bad input file, and I found the diagnostic messages less useful than I would have liked for determining what was going on.

Tweak diagnostics in expression parser.

---

config/component_macros.cmake
src/meshReaders/test/CMakeLists.txt

**Background**:
+ This cmake function is used to copy files from the source directory to the build directory. It can rename files during the copy and replace @VAR@ type variables with values specified in the build system.
+ Capsaicin has requested a new build system feature that will rebuild applications like serrano or anaheim when `make` is run from the `test` subdirectory.
**Solution**:
+ The `provide_aux_files` cmake function can now take a new optional parameter `TARGETS` that the build system will ensure are up-to-date when `make` is executed.  An example of using this new feature can be found in `anaheim/test/CMakeLists.txt`
```
provide_aux_files(
FILES "${aux_files}"
TARGETS Exe_anaheim )
```
+ I also simplified some code in the function.
+ Relates to …

Extend the functionality of the cmake function provide_aux_files.

---

config/compilerEnv.cmake

* I think IPO is causing link-time issues when an executable created with Visual Studio attempts to link to a library created by MinGW gfortran. Disable IPO on Win32 platforms for now.  Even if this doesn't fix the compilation issue, it will make the failure easier to track down.

Disable IPO for Win32 builds.

---

CTestCustom.cmake
regression/Draco_Linux64.cmake
regression/Draco_Win32.cmake
regression/draco_regression_macros.cmake
regression/win32-regress.bat
regression/win32-regression-master.bat

**Purpose:**
+ MSBuild is faster and easier to debug with Visual Studio.
+ MSBuild works better with libraries created with MinGW's gfortran.
**Details:**
+ In `CTestCustom.cmake`, set hard limits on how much data is collected for CDash.
+ Synchronize `Draco_Linux64.cmake` and `Draco_Win32.cmake`.
+ In `draco_regression_macros.cmake`, for Win32 platforms:
- use the *Visual Studio 15 2017* project generator instead of *NMake Makefiles*.
- do a better job of setting the compiler name and version.
- ensure that `CTEST_CONFIGURATION_TYPE` is set.  Because *Visual Studio 15 2017* projects don't specify the build type (multi-config builds), this value must be specified when running ctest: `ctest -j 4 -C ${CTEST_CONFIGURATION_TYPE}`
- Ensure that `MAKECOMMAND` is not set.
+ Dump the regression …

Convert Win32 nightly testing from NMake to MSBuild.

---

config/unix-clang.cmake

Tell clang to use its own STL instead of gcc's.

---

regression/Draco_Linux64.cmake
regression/ccscs-crontab
regression/ccscs-options.sh
regression/ccscs-regress.msub
regression/ccscs2-crontab
regression/checkpr.sh
regression/draco_regression_macros.cmake
regression/ml-crontab
regression/ml-options.sh
regression/ml-regress.msub
regression/scripts/release_toss.sh
regression/sn-crontab
regression/sn-options.sh
regression/sn-regress.msub
regression/tt-crontab
regression/tt-options.sh
regression/tt-regress.msub

**Background**
Previously, *Release* regressions included long running verification tests (`RUN_VERIFICATION_TESTS=ON`). However, these regression suites were generating too much data to upload to CDash resulting in partial reports (no test results).  It also meant that *Release* regressions would take a long time to run.
This change splits the running of these long running tests into a separate regression suite (*vtest*).
**Changes**
+ Run these tests in a new regression suite 'vtest'
+ Add new 'vtest' regressions in crontab files that already run 'Release' regressions.
+ Register new 'extra_param' option 'vtest' in the regression system.
+ Ensure that the 'extra_param' string is appended to the build name.
+ [Refs #1052 (Redmine)](https://rtt.lanl.gov/redmine/issues/1052).
* [Pre-Merge …

Split RUN_VERIFICATION_TESTS away from Release regressions

---

regression/sn-crontab
regression/update_regression_scripts.sh

+ Add Capsaicin to the `newtools` regression. The `newtools` regression only runs on Snow.  It currently uses `intel/18.0.1` and `openmpi/2.1.2`.
+ For trinitite regressions, only keep build directories for 2 days.  This change is needed to prevent us from exceeding our disk quota at `/usr/projects/ccsrad`.  On trinitite, we must run the regressions in NFS space to work around srun defects. Regressions for other systems use lustre scratch space and we keep old build directories for 2 weeks.

Update the 'newtools' nightly regression and reduce disk space usage.

---

regression/draco_regression_macros.cmake

+ Fix a bug that prevented `ENABLE_PERFBENCH:BOOL=ON` from being added to the CMakeCache.txt file.
+ Add support for multiple line entries in `CUSTOM_VARS`.

Minor tweak to support new Capsaicin perfbench regression.

---

environment/bashrc/.bashrc
environment/bashrc/.bashrc_toss3
environment/bashrc/.bashrc_tt
environment/bashrc/bash_functions2.sh
environment/elisp/draco-config-modes.el

+ Teach the bashrc files about badger (ba-fey).
+ Move the bash functions from `bashrc/.bashrc` into a `bash_functions_2.sh`.  Bash functions are not inherited by subshells, so change the environment logic to define bash functions like `dracoenv` everytime a new shell is started.
+ Fixes [Redmine 1061](https://rtt.lanl.gov/redmine/issues/1061)
Somewhat unrelated:
+ For the Draco Emacs modes: For f90-mode (a) enable abbrev-mode, (b) disable beginning ampersand (except for strings), and (c) colorize more keywords.

Update draco environment to support Badger.

---

.codecov.yml
.github/PULL_REQUEST_TEMPLATE

+ Reduce codecoverage precision to 1 decimal.
+ Update the new-PR template by removing entry for Moonlight (Toss2) and adding headers for recommended sections.

WIP: Tweak Github settings.

---

config/unix-clang.cmake
config/unix-g++.cmake
environment/bashrc/.bashrc_linux64
regression/sn-crontab
regression/tt-crontab

+ No longer load _ccache_ automatically on ccs-net machines.  _ccache_ has been causing trouble for a couple of developers.  You can always load it in your own `.bashrc` or manually.
+ Remove error check for _gcc_ version < 4.8.  This is no longer needed since we require c++14 and CMake will fire an assertion if _gcc_ is too old.
+ Clean up some comment blocks.

Minor Dev/Regression environment updates.

---

src/rng/test/util_cpu.h

* An unused variable warning occurs with gcc 6.4 for the return variable of `warmupCPU`.
* `warmupCPU` merely iterates a logistic map function and appears to not need to return a double.
* Change `warmupCPU` function return type from static double to static void.
* Apply clang formatting to `util_cpu.h`.
* Reference:
* (CDash Status)[https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=-pr]
* Checks

Make cpu warm-up function static void to avoid gcc6.4 warning.

---

regression/ccscs-options.sh
regression/cts1-job-launch.sh
regression/cts1-options.sh
regression/cts1-regress.msub
regression/draco_regression_macros.cmake
regression/metrics_report.sh
regression/regression-master.sh
regression/tt-options.sh
regression/tt-regress.msub

* The scripts for snow work equally well for Badger.  Because snow was down for 2 days, I made the scripts more generic so I could run them on Badger.
* Updates allow the renamed _cts1_ regression scripts to run on either snow or badger (and probably fire and ice, but this hasn't been tested).
* The `*-job-launch.sh` scripts are more generic now. They use more information found in the `*-options.sh` files.
* Regression scripts for trinitite were updated to look more like the cts1 scripts.
* Reference:
* Checks

Updates to regression scripts

---

src/c4/CMakeLists.txt
src/c4/Invert_Comm_Map.cc
src/c4/Invert_Comm_Map.hh
src/c4/MPI_Traits.hh
src/c4/c4_mpi.h

* Draco fails to compile if `<mpi.h>` isn't found, even when `C4_SCALAR` is enabled.
+ Add some ifdefs to allow configure and compile of Draco on a
system that does not have MPI installed.
+ Also tweak ds++'s CMakeLists.txt.
* Reference:
* Checks

Tweaks to fix broken builds for C4_SCALAR.

---

config/draco-config-install.cmake.in

* #362 changed the order that some cmake macros are called.  This inadvertently broke MPI detection and setup.
* [Fixes Redmine Issue #1095](https://rtt.lanl.gov/redmine/issue/1095)
* Save the cmake variable `CRAY_PE` to `draco-config.cmake` to eliminate the order dependency for calling cmake macros.
* Reference:
* Checks

Fix build post pr362 build failures on cray.

---

src/VendorChecks/test/CMakeLists.txt
src/c4/CMakeLists.txt
src/quadrature/ftest/CMakeLists.txt

+ #362 changed the way MPI dependencies are expressed by the build system, but didn't take into account our `SCALAR` build mode.
* SCALAR builds are failing, as tracked by [Redmine Issue #1096](https://rtt.lanl.gov/redmine/issue/1096). This PR fixes this failure mode.
+ No longer link to `MPI::MPI_C` targets if `DRACO_C4=SCALAR.`
* Reference:
* Checks

Fix broken scalar builds (post pr362)

---

config/setupMPI.cmake

* The underlying issue is that CMake treats the MinGW build environment as vanilla Linux, but we are actually using _MS-MPI_.  _MS-MPI_ has a slightly different installation structure for Fortran where some MPI header files are in the directory `$MPI_INCLUDE_DIRS/$arch` where `$arch` is either `x86` or `x64`.  
* Rework checks and fixes for the MPI environment discovered by CMake for Fortran-based CMake subdirectories processed with MinGW as a subproject under a Visual Studio build. This change is required for Jayenne's `ftest` subprojects.
* The new new logic looks for the extra include directory and adds it to the `INTERFACE_INCLUDE_DIRECTORIES` property of the `MPI::MPI_Fortran` imported build target.
* Reference: …

Fix MPI logic for CAFS (Visual Studio + gfortran)

---

src/parser/Debug_Options.cc
src/parser/Debug_Options.hh
src/parser/test/tstDebug_Options.cc

I am planning to experiment with expert system/machine learning approaches to picking a strategy for solving a problem. For example, if I'm doing transport sweeps, I have the options of whether to use parallel block Jacobi, Gauss-Seidel, or full sweeps, and whether (and which!) preconditioners to apply. The best choice depends on the characteristics of the posed problem. I want a debug option that prints some diagnostics about the relevant characteristics of a problem as deduced by the program.
This adds a DEBUG_PROBLEM option to the Debug_Options enumeration.
Add a DEBUG_PROBLEM option, which turns on code that calculates characteristics of the problem specification itself *other* than whether the problem is well-posed. For example (and this is the application I need this for) the code …

Extend Debug_Options

---

src/ds++/fpe_trap.cc
src/ds++/test/do_exception.cc
src/ds++/test/test_fpe_trap.py

* fpe_trap is failing to work on some systems.
+ In a few places, replace newline with `std::endl` to force the buffer to flush to screen before continuing. For the previous implementation, on some systems messages that the python test is looking for don't print before the exception is thrown.
+ Cleanup python logic a bit
+ Clean up documentation and formatting a bit.
+ On WLS with gcc-5.4.0, fpe_trap cases 2 and 3 still fail and case 3 is still failing on KNL.  I think these failures are limitations of the underlying environment but more investigation is needed.
* Reference:
* **NOTE**: This PR accidentally includes changes found in #359.  Those changes need to be merged and then this must be rebased before it is merged. …

Minor cleanup for the fpe-trap feature

---

src/c4/ParallelUnitTest.cc
src/c4/ParallelUnitTest.hh
src/c4/test/tstParallelUnitTest.cc
src/ds++/UnitTest.hh
src/ds++/test/tstScalarUnitTest.cc

When a condition is checked on all processors, one gets multiple success/failure messages for that test. The test is also not handled very gracefully if only *some* processors fail, particularly in the fatal failure case.
Provide less vebose output for parallel tests and make sure failure on only some processor is handled gracefully.
Added a check_all function to the UnitTest class tree. This is used for a test that must pass on all processors and is checked synchronously. Only one pass/fail message will be generated rather than one per processor. The failing processors will be listed if the test fails. This makes for cleaner recovery if a test fails on only some processors, particularly for the fatal failure case.
This is simply a redirect to check() for ScalarUnitTest.
Note: I can't …

Add a check_all function to the UnitTest class tree.

---

environment/bashrc/.bashrc_slurm

* CPU-hr usage by account by user may be useful for generating reports or prioritizing resources.
* Add slurm function `usercpuhrs`, in .bashrc_slurm, to print total cpu-hr usage, which takes optional inputs: user, start date, and end date.
* Reference:
* Checks

Add slurm function to print total cpu-hr usage.

---

src/parser/Console_Token_Stream.cc
src/parser/Console_Token_Stream.hh
src/parser/File_Token_Stream.cc
src/parser/File_Token_Stream.hh
src/parser/Parallel_File_Token_Stream.cc
src/parser/Parallel_File_Token_Stream.hh
src/parser/Parse_Table.cc
src/parser/Parse_Table.hh
src/parser/String_Token_Stream.cc
src/parser/String_Token_Stream.hh
src/parser/Token_Stream.hh
src/parser/test/tstConsole_Token_Stream.cc
src/parser/test/tstFile_Token_Stream.cc
src/parser/test/tstParallel_File_Token_Stream.cc
src/parser/test/tstParse_Table.cc
src/parser/test/tstString_Token_Stream.cc

No one ever reads the users' manual, which is rarely updated in a timely way anyway. The result is that even experienced users are unaware of which keywords are present in a parse table.
Add diagnostic capability to Parse_Table that lets a user know what keywords are available when the parser sees something it doesn't recognize.
Add code such that a Parse_Table will list the known keywords for the client whenever it encounters an unknown keyword. The keyword may optionally be followed by a description. This is more likely to be useful than the users' manual that no one ever reads.
In support of this capability, add a description member to the Keyword struct. Add a default constructor for Keyword and a constructor compatible with the usual brace initializers we have been using. The latter …

Improve error diagnostics for Parse_Table.

---

src/cdi/CDI.hh
src/quadrature/Octant_Quadrature.cc

Some minor tweaks that nevertheless improve efficiency.
Use make_shared in preference to initializing shared_ptr with a new expression. This reduces two allocation calls to one allocation call.
Eliminate an unnecessary extra call to exp when calculating Planck and Rosseland integrals for a set of groups.
* Checks

Tweak some code for efficiency.

---

.travis.yml

* Travis began failing on March 19, 2018 (possibly sooner) with an error about failing to upgrade pip.
* The Travis log reports the following:
```
$ pip install --upgrade pip
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: …
```

WIP: Try to fix pip upgrade failure in Travis.

---

regression/valgrind_suppress.txt

+ Kent's recent addition of an [MPI-aware runtime_check](https://github.com/lanl/Draco/pull/378) introduced new logic paths through the MPI call stack that trigger valgrind warnings that we have no control over. Suppress these warnings since they aren't valuable to us.
* Ref: https://rtt.lanl.gov/cdash/viewDynamicAnalysisFile.php?id=83954
* Reference:
* Checks

Add more valgrind suppression rules.

---

autodoc/README.autodoc
environment/bashrc/.bashrc
environment/bashrc/.bashrc_slurm
regression/ccscs-regress.msub

+ No longer disable the generation of core files. Let the developer set this in his or her own `.bashrc` file.
+ Add a new bash helper function `myusage` to report slurm account use. This feature was provided by Ryan.
+ Enable the use of **mscgen** with **doxygen** when the autodoc pages are generated nightly on ccscs2.
* Reference:
* Checks

Minor tweaks to the draco developer environment.

---

autodoc/CMakeLists.txt
config/vendor_libraries.cmake

+ Python has become a significantly more important requirement for Draco (see `ApplicationUnitTest.py`, and the ipcress data viewer, etc.). This PR tells CMake that
python is now an essential requirement.  Draco will no longer configure if python is missing.
+ Also move the detection of doxygen from autodoc/CMakeLists.txt to `vendor_libraries.cmake`.
* [Fixes Redmine Issue #1130](https://rtt.lanl.gov/redmine/issue/1130)
* Reference:
* Checks

Promote python requirement to 'always required'

---

regression/cts1-job-launch.sh
regression/cts1-regress.msub
regression/draco_regression_macros.cmake
regression/regression-master.sh
regression/tt-crontab
regression/tt-job-launch.sh
regression/tt-options.sh
regression/tt-regress.msub
regression/update_regression_scripts.sh

* Until recently, the regression system has only allowed (and only needed) single values for "extra_params" (`-e` option).
* Capsaicin now requires `-e "knl perfbench"`, so an upgrade to the existing scripts was required.
* Allow Capsaicin to run `perfbench` regressions on the knl nodes of trinitite.
* [Fixes Redmine Issue #1142](https://rtt.lanl.gov/redmine/issue/1142)
+ Modify the `-e` option to allow multiple words.  For example:  `regression-master.sh -e "knl perfbench"`
+ Update logic in regressions scripts to expect multiple values for `$extra_params`. Create new variable `$extra_params_sort_safe` that contains a single string whose value is a sorted list of `$extra_params` where spaces are replaced by underscores.  This variable will be used for regression directory names. For …

Allow multiple values for extra_params in the regression system.

---

config/FindEOSPAC.cmake
config/print_target_properties.cmake
config/vendor_libraries.cmake
src/cdi_eospac/CMakeLists.txt

* eospac is now published by spack, so we need to upgrade the `FindEOSPAC.cmake` module to find eospac installed in a _normal_ way.  Previously, we relied on hand rolled environment variables to help the build system find `libeospac.a`.
+ Teach `FindEOSPAC.cmake` to find eospac that is provided via spack and without environment variables like `EOSPAC_LIB_DIR`.
+ Update the `FindEOSPAC.cmake` script to use modern CMake recommendations, including a populated link target `EOSPAC::eospac`.
+ Move eospac discovery from `cdi_eospac/CMakeLists.txt` to `config/vendor_libraries.cmake`.
+ In `cdi_eospac/CMakeLists.txt` use the new `EOSPAC::eospac` build target as a link dependency instead of cmake variables like `${EOSPAC_LIBRARY}`.
* Reference: …

Improve FindEOSPAC.cmake

---

regression/checkpr.sh
regression/draco_regression_macros.cmake
regression/tt-crontab
regression/tt-job-launch.sh

+ When running the 'vtest' (long running verification problems) tests for Capsaicin and Jayenne, there is not reason to build a special 'vtest' version of Draco. Use the regular 'Release' build of Draco.
+ Capsaicin has requested a 'knl-perfbench'  nightly regression on trinitite.
+ Jayenne has requested a 'knl-vtest  nightly regression on trinitite.
+ Jayenne has requested that a clang CI be completed on ccscs2 for all new PRs. The current clang-based toolchain is unable to build Capsaicin, so do not add a clang based CI for them.
+ After pull request #386, regression runs that did not set any value for the '-e' option to `regression-master.sh` has poorly formed build names.  Modify `draco_regression_macros.cmake` to create better build names.
+ `checkpr.sh` modified to skip 'vtest' …

Add new CI testing (checkpr.sh)

---

config/buildEnv.cmake
config/compilerEnv.cmake
config/dracoTesting.cmake
config/setupMPI.cmake
config/unix-clang.cmake
config/unix-pgi.cmake
config/vendor_libraries.cmake

* While trying to stand up builds with _clang@6.0.0 + gfortran@4.8.5_, CMake's MPI detection was failing for _gfortran_.  This turned out to be a result of a clang-only option to enable OpenMP that was added to the link line for programs that use _gfortran_ for the final link.
* [Fixes Redmine Issue #1147](https://rtt.lanl.gov/redmine/issue/1147) for clang@6.0.0
+ In `unix_clang.cmake`, do not add the `OpenMP_C_FLAGS` value to the `CMAKE_EXE_LINKER` flags.
+ Eliminate some unused or deprecated variables from the build system:
- `DBS_CXX_COMPILER_VER*`
- `DRACO_LIBEXT`
- `DBS_MPI_VER` (only removed from the OpenMPI section of `setupMPI.cmake`). Use `MPI_C_VERSION` instead as it is provided by `FindMPI.cmake`.
* WIP
* Reference: …

Fix OpenMPI detection when using clang++/clang/gfortran combination.

---

environment/bashrc/bash_functions2.sh

* When a module isn't found on linux64 system, the module load command in the `dracoenv` function in bash_functions2 might not be able to load any modules.
* Load all possible modules.
* Change module load of list to a loop loading modules 1-by-1.
* Reference:
* Checks

Load modules 1-by-1 in bash_functions2 version of dracoenv.

---

config/vendor_libraries.cmake
regression/valgrind_suppress.txt

+ Also make `find_package(doxygen)` less verbose.
* Reference:
* Checks

Fix a bad entry in valgrind_suppress.txt.

---

config/compilerEnv.cmake

+ The old logic breaks for gcc-8.1.0 on ccs-net because the spack hash in the path to gfortran includes the string "xl" (as in IBM XL Fortran).
+ New logic uses [CMake provided Compiler ID strings](https://cmake.org/cmake/help/v3.10/variable/CMAKE_LANG_COMPILER_ID.html?highlight=compiler_id#variable:CMAKE_%3CLANG%3E_COMPILER_ID). 
* Reference:
* Checks

Patch logic used to identify the Fortran compiler flavor.

---

regression/valgrind_suppress.txt
src/RTT_Format_Reader/RTT_Format_Reader.cc
src/cdi_eospac/Eospac.cc

+ Minor cleanup to silence warnings that appeared when switching regressions to gcc-8.1.0.
* Reference:
* Checks

Cleanup some code to eliminate build/run warnings.

---

src/c4/Timer.cc

Fairly brain-dead typo bug: User time was being reported as system and wall time as well.
Kris Garrett noticed that the exact same time was being reported for user, system, and wall, though the reported variance varied.
Inspection showed the Timer::print_mean function was printing the mean user time in each case rather than the user time, system time, and wall time. Ironically, the variances were being done correctly and so were, ah, varying.
Fix the bug
Change "mu" to "ms" and "mww" in the appropriate points.
* Reference:
* Checks

Fix bug in Timer::printline_mean

---

README.draco
config/CMakeAddFortranSubdirectory.cmake
config/compilerEnv.cmake

* Recent changes to the build system were not checked against Windows/Visual Studio configurations.  Small tweak are required to keep the Visual Studio builds working.
+ Add a conditional that checks if `CMAKE_CXX_COMPILER_ID == MSVC`.  Change conditional for pgc++ by putting the '+' in brackets.
+ Add additional debug output from `CMakeAddFortranSubdirectory.cmake` when `VERBOSE` is set.
* Reference:
* Checks

Fix bug in compilerEnv.cmake wrt MSVC builds.

---

config/compilerEnv.cmake
config/unix-g++.cmake

+ These changes are needed to allow the CMakeAddFortranSubdirectory feature to work correctly after #408 and #409.
+ In `compilerEnv.cmake`, add quotes around some CMake variables to account for spaces in paths and empty strings.
+ When identifying the compiler ID, check both CXX and C compilers.
+ In `unix-g++.cmake`, only perform `check_cxx_compiler_flag` operations when a C++ compiler is defined. This is almost always true -- except for some test directories that only require Fortran and C.
* Reference:
* Checks

Fix broken Jayenne-win32 builds (CMakeAddFortranSubdirectory failures)

---

.codecov.yml
config/compilerEnv.cmake
config/dracoVersion.cmake
config/vendor_libraries.cmake
regression/check_style.sh

* On glitlab for Capsaicin and Jayenne, the style CI check has been broken for a while.  One of the issues is that the application names for `git-clang-format` and `clang-format` might have a version suffix and Draco's `style_check.sh` script wasn't flexible enough to find and use the alternate names.
* Update the regression scripts in Draco that are used by Capsaicin and Jayenne's gitlab 'style' checker.
* [Fixes Redmine Issue #1154](https://rtt.lanl.gov/redmine/issue/1154)
* When trying to find clang-format and git-clang-format allow optional `-X.X` version number. 
* Allow clang-format to use the suffix, and git-clang-format to be bare.
* Reference:
* [CDash …

Fixes for gitlab style runner

---

src/ds++/CMakeLists.txt
src/mesh/Draco_Mesh.hh

* New package `mesh` requires a couple of extra instructions to allow it to compile under Visual Studio 2017. 
* Modify scripts that generate CPP macro for `DLL_PUBLIC_imc`.
* Use the new decoration for the `Draco_Mesh` constructor.
* Reference:
* Checks

Minor tweaks to enable new package 'mesh' to build under VS2017.

---

.travis-install-dependencies.sh
.travis-run-tests.sh
.travis.yml
autodoc/ci-testing.dcc

+ The Travis configure/build/test runner has been failing for some time.   Disable it until we can bring it back online.
+ Comment out all of the Travis runner scripting that runs to regular configure/build/test sequence.
+ The style checker will remain active, but we will begin using clang-format-6.0.
* Reference:
* Checks

Disable Travis config/build/test builds.

---

config/FindCOMPTON.cmake
config/setupMPI.cmake
environment/bashrc/.bashrc

+ Modify `FindCOMPTON.cmake` so that two possible names for the CSK library are considered suitable.  Also, ensure that the `COMPTON_VERSION` variable is set.
+ If `setupMPI.cmake` fails, add the `CRAY_PE` value to the diagnostic message.
+ Re-enable bashrc setup for Luna.
* Reference:
* Checks

Minor tweaks to the configure process.

---

environment/bashrc/.bashrc_linux64
environment/bashrc/.bashrc_toss22
environment/bashrc/.bashrc_toss3
environment/bashrc/.bashrc_tt
environment/elisp/draco-config-modes.el
regression/ccscs-regress.msub
regression/ccscs3-crontab
regression/checkpr.sh
regression/cts1-regress.msub
regression/scripts/common.sh
regression/sn-crontab
regression/update_regression_scripts.sh

* It seems that we are always tweaking the developer environment and the regression scripts.  Here is another set of small changes...
* [Related to #1178](https://rtt.lanl.gov/redmine/issue/1178)
+ When loading modules via Draco's .bashrc files, only load ndi and csk modules if the those installation directories are accessible.
+ On ccs-net machines, the regression script will now use `top` to print the current machine load and list active jobs before the regressions start.
+ For ccs-net machines, the vtest, scalar, static and clang regressions have been moved from ccscs2 to ccscs3.
+ Begin loading clang-format/6.0 when available.
+ On ccs-net machines, the regressions system was updated to make it less likely that multiple regressions are running simultaneously. Also move some PR testing …

Update environments and regression scripts.

---

src/c4/Timer.cc

The variances whose sqrt are taken in the timer output code are formally positive indefinite, but roundof will sometimes make them very slightly negative and trigger a floating point exception. Wrapping in fabs is a perfectly adequate fix, since the result printed will be zero, which is the right printed value.
* Reference:
* Checks

Safe a call to sqrt by wrapping its argument in fabs.

---

README.md
appveyor.yml
config/windows-cl.cmake
src/CMakeLists.txt

* We run nightly regressions for Visual Studio 2017, but most developer's don't have access to VS2017 for testing purposes.
* [Appveyor](https://www.appveyor.com/) provides a capability similar to [Travis](https://travis-ci.org), but targets Visual Studio builds.
* We will start with a basic build (ds++ only). If successful, we will add other Draco packages to this CI testing framework.
+ For now, only build and test ds++. Limit included directories by querying for `ENV{APPVEYOR}` from `src\CMakeLists.txt`. 
+ There were some link issues in c4 related to `DLL_PUBLIC_c4`.  Once those are fixed, we can activate the build for all but 3 packages.  
+ The remaining packages are trying to use a 64-bit Fortran compiler with a 32-bit CXX compiler.  It will take some digging to fix these.
+ …

Add an Appveyor (win32) build to the CI.

---

appveyor.yml
config/component_macros.cmake
environment/bashrc/.bashrc
regression/draco_regression_macros.cmake
regression/sync_vendors.sh
src/CMakeLists.txt

* I am still trying to stand up the _Travis_ and _Appveyor_ CI systems on github.com. In a previous commit, I activated the _Appveyor_ CI for `ds++` only.  The _Travis_ based system was building and testing `ds++`, `c4` and `rng`.
* This PR add many of the remaining packages, but still omits packages that need other third party libraries (e.g.: lapack, cuda, metis, parmetis, superlu-dist, csk, etc.) that are not provided in the current CI image.  These will be added, one at a time, in future work.
* I also omitted packages that need Fortran, but these will be added for the _Travis_ subsystem very soon.
* Also note that the CI systems are still limited to `DRACO_C4=SCALAR` since no MPI is installed.
* Update `src/CMakeLists.txt` to restrict when specific packages should be included. …

Enable more tests in the CI systems.

---

src/CMakeLists.txt
src/RTT_Format_Reader/test/rttpolyhedron.2.mesh.in
src/RTT_Format_Reader/test/rttpolyhedron.2o.mesh.in
src/RTT_Format_Reader/test/rttpolyhedron.3.mesh.in
src/RTT_Format_Reader/test/rttpolyhedron.4.mesh.in
src/RTT_Format_Reader/test/rttpolyhedron.mesh.in
src/RTT_Format_Reader/test/rttquad.mesh.in
src/RTT_Format_Reader/test/rttquad5.mesh.in
src/RTT_Format_Reader/test/rttquad9.mesh.in
src/mesh/CMakeLists.txt
src/mesh/Draco_Mesh.hh
src/mesh/Draco_Mesh_Builder.hh
src/mesh/Draco_Mesh_Builder.t.hh
src/mesh/Draco_Mesh_Builder_pt.cc
src/mesh/test/CMakeLists.txt
src/mesh/test/Test_Mesh_Interface.hh
src/mesh/test/rttquad_2cell.mesh.in
src/mesh/test/tstDraco_Mesh.cc
src/mesh/test/tstDraco_Mesh_Builder.cc

* In order to test Draco_Mesh on more complicated meshes, some parsing capability is needed.
* There is already mesh parsing functionality in Draco for RTT mesh formats.
* A mesh builder can act as an intermediary between parser and mesh constructor, ensuring all parsers provide the same sort of data to the constructor.
* Create Draco_Mesh_Builder, with reader/parser type as template parameter.
* Demonstrate parsing capability for Draco_Mesh with RTT mesh file format.
* Note the builder is currently assuming a non-decomposed mesh is being read (i.e. global_node_number = proc-local node indices).
* [See Redmine Issue #1182](https://rtt.lanl.gov/redmine/issues/1182)
+ Add Draco_Mesh_Builder, templated on reader/parser type.
+ Add unit test with 2-cell RTT mesh input file.
+ Add side flag …

Complete preliminary Draco_Mesh builder, using RTT mesh parser.

---

src/CMakeLists.txt
src/mesh/CMakeLists.txt
src/mesh/Draco_Mesh_Builder.t.hh
src/mesh/Draco_Mesh_Builder_pt.cc
src/mesh/Draco_Mesh_Reader.hh
src/mesh/RTT_Draco_Mesh_Reader.cc
src/mesh/RTT_Draco_Mesh_Reader.hh
src/mesh/X3D_Draco_Mesh_Reader.cc
src/mesh/X3D_Draco_Mesh_Reader.hh
src/mesh/X3D_Draco_Mesh_Reader.i.hh
src/mesh/test/CMakeLists.txt
src/mesh/test/tstDraco_Mesh_Builder.cc
src/mesh/test/tstX3D_Draco_Mesh_Reader.cc
src/mesh/test/x3d.mesh.in

* X3D is an alternative file parsing format to RTT.
* It is useful to have a framework that easily permits new mesh parsers.
* It may be worthwhile to replace this or augment with Class_Parse_Table parsing to X3D mesh.
* Enable preliminary X3D parsing, excluding X3D boundary files (which supply side data), using a file-block-delimiter based formalism (parse into maps, following work by @keadyk ).
* [Addresses Redmine Issue #1182](https://rtt.lanl.gov/redmine/issues/1182)
* Add abstract base class for `Draco_Mesh` readers (`Draco_Mesh_Reader`) with pure virtual functions, so that derived reader classes can always supply the `Draco_Mesh` builder class the correct accessors. 
* Add wrapper for `RTT_Format_Reader` (`RTT_Draco_Mesh_Reader`) that inherits from new abstract base class.
* Add …

Add preliminary X3D Draco_Mesh parser.

---

.github/PULL_REQUEST_TEMPLATE

* This is a very minor fix to the redmine url.
* Reference:
* Checks

Fix url in pull request template.

---

config/ApplicationUnitTest.cmake
config/component_macros.cmake
config/setupMPI.cmake
src/c4/test/tstProcessor_Group.cc
src/c4/test/tstTime.cc
src/ds++/Release.hh
src/rng/test/ut_gsl.c

* On my new system, I'm standing up regressions for 64-bit compiles under Visual Studio.  There are  a few new warnings that I'm dealing with.
* I'm also being more careful about setting up TPLs for VS2017.
* https://gitlab.kitware.com/cmake/cmake/merge_requests/2236
* https://github.com/ampl/gsl/pull/31
+ `ApplicationUnitTest.cmake`: Replace local variables `PYTHON_COMMAND` with CMake global variable `PYTHON_EXECUTABLE` and make use of PYTHONINTERP_FOUND.
+ `component_macros.cmake`: Add more optional debugging output for cmake function `copy_dll_link_libraries_to_build_dir`.  This is used to help debug issues related to missing dll libraries on Win32 platforms.
+ `setupMPI.cmake`: On Windows do a better job of querying and setting `MPI_CORES_PER_CPU`, `MPIEXEC_MAX_NUMPROCS`, and …

Tweaks to eliminate build warnings for 64-bit builds under VS2017.

---

config/CMakeAddFortranSubdirectory.cmake
config/compilerEnv.cmake
config/windows-cl.cmake
regression/draco_regression_macros.cmake
regression/update_regression_dir.bat
regression/win32-regress.bat
regression/win32-regression-master.bat

* I'm migrating support for Visual Studio regressions (and builds in general) from my old desktop to my new desktop.  Since I'm recreating all of the regression setup for Visual Studio, I've chosen to also migrate to 64-bit builds at the same time.
* [Fixes Redmine Issue #1218](https://rtt.lanl.gov/redmine/issues/1218)
+ Add support for msys64/mingw64 gfortran (64-bit gfortran) under Visual Studio. Look for gfortran at the standard install location (`c:/msys64/mingw64/bin`).
+ Disable IPO for Visual Studio.  In theory this should work but fails for hybrid VS+gfortran linking.
+ Tweak Visual Studio builds by assuming AVX2 is available.
+ Update regression scripts.
- Default to 64-bit builds: `-G "Visual Studio 15 2017 Win64"`
- Update run scripts to point to new locations for files, tools, …

More extensions to support 64-bit builds under VS 2017.

---

src/ds++/CMakeLists.txt
src/ds++/config.h.in
src/rng/Counter_RNG.hh
src/rng/config.h.in
src/rng/test/CMakeLists.txt
src/rng/test/kat_cpp.cpp
src/rng/test/time_initkeyctr.h
src/rng/test/ut_Engine.cpp
src/rng/test/ut_uniform.cpp
src/rng/test/util_expandtpl.h
src/rng/uniform.hpp

+ Kent needs KNL specific CPP macros to control when prefetch commands are injected into the code.
* [Fixes Redmine Issue #1245](https://rtt.lanl.gov/redmine/issues/1245)
+ Use *CRAYPE* specific environments to detect if we are targeting a *mic-knl* node.  If so, set `draco_isKNL` and save this value in `ds++/config.h`.
+ Also save `CMAKE_C_COMPILER_ID` to `ds++/config.h`.
+ Move `DBS_GNUC_VERSION` from `rng/config.h` to `ds++/config.h` and update sources in *rng* to use the new definition.
+ on ccs-net, the generated `ds++/config.h` will look something like this:
```cxx
#define CMAKE_C_COMPILER_ID GNU
/* #undef MSVC */
/* #undef MSVC_IDE */
/* #undef MSVC_VERSION */
#define UNIX 1
#define draco_isLinux
/* #undef draco_isOSF1 */
/* #undef draco_isDarwin */
/* #undef draco_isAIX */
/* …
```

Update ds++/config.h to provide draco_isKNL.

---

.travis.yml
config/FindCOMPTON.cmake
config/component_macros.cmake
config/vendor_libraries.cmake
environment/bashrc/.bashrc
environment/bashrc/.bashrc_slurm
environment/bashrc/.bashrc_tt
regression/ccscs2-crontab
regression/travis-run-tests.sh

Misc:
+ Fix spelling errors
+ Update copyright dates.
Build System:
+ In `FindCOMPTON.cmake`, fix how `COMPTON_VERSION` is discovered and set.
+ Raise a fatal error if an incompatable version of superlu-dist is found. An API change introduced in versin 5.3 breaks our code.
Developer environment:
+ Do not set `shopt -s direxpand` on toss2 machines.
+ Make the `sq` alias more useful by allowing pass through of options like `-A <account>`, `-j <jobname>`, etc.
+ We have started mirroring the git repositories to the red twice per day.  Update the archived crontab that controls this schedule.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compa …

Small tweaks and fixes.

---

src/viz/Ensight_Translator.i.hh

* Fix ambiguous type conversion issue when compiling on a MAC
* Fix ambiguous type conversion issue when compiling on a MAC
* Fix ambiguous type conversion issue when compiling on a MAC
* Reference:
* Checks

Fix ambiguous type conversion issue when compiling on a MAC

---

regression/draco_regression_macros.cmake
regression/win32-regression-master.bat
src/VendorChecks/test/tstParmetis.cc
src/ds++/test/do_exception.cc

* We are seeing a few build warnings on CDash for the nightly Visual Studio regression suite.  This PR attempts to eliminate those build warnings.
+ Update `tstParmetis.cc` to eliminate warnings about type conversion.
+ Update `do_exception.cc` to eliminate warning about division by zero.
Also:
+ Update `draco_regression_macros.cmake` to enable parallel compiles for the Win32 regression system.
+ Fix some environment variables used by the regression system on Win32.
+ Fix some spelling errors.
* Reference:
* Checks

Clean up build warnings reported by VS and fix some regression scripts

---

config/unix-crayCC.cmake
environment/bashrc/.bashrc_slurm
regression/Dockerfile
src/RTT_Format_Reader/RTT_Mesh_Reader.hh
src/mesh_element/Element_Definition.cc
src/mesh_element/Element_Definition.hh
src/mesh_element/Geometry.hh

* A few minor changes had accumulated in my draco checkout on HPC systems.  They are provided here.
+ CMake doesn't know how to toggle C++14 language standard support for the Cray compiler.  This is fixed in upstream cmake, but as of cmake-3.12.1 it is missing.  Provide a work-around.
+ Fix an error (missing dash) in the alias definition for `sq`.
+ Update the `Dockerfile` to include `flex` and `bison` installations.  This is needed by Capsaicin.
+ Re-indent and format comment blocks in 4 source files.
* Reference:
* Checks

A few misc. updates.

---

.gitignore
environment/elisp/format-f90.el
environment/elisp/format-f90.sh
environment/vim/.vimrc
src/CMakeLists.txt
src/ds++/DracoStrings.cc
src/ds++/DracoStrings.hh
src/ds++/test/tstDracoStrings.cc
src/ds++/test/tstPrefetch.cc
src/mesh/CMakeLists.txt

* We require C/C++ code to conform to the style enforced by `clang-format`, but until now we didn't provide an easy way for _vi(m)_ users to automatically apply the style to files that are being edited.  This PR demonstrates how to use an _optional_ add-in for _vi(m)_ that provides this capability.  `<control>-i` can be used to format the current line.  A hook can also be added that will reformat the whole file upon write.
* We are evaluating tools that will help us enforce a common style for F90 code. An Emacs based solution is provided for early testing
* We would like the Appveyor CI to run more tests (begin testing the _mesh_ package).
* [Related to Redmine Issue #1250](https://rtt.lanl.gov/redmine/issues/1250) - f90 formatter
* [Related to Redmine Issue …

Provide helper scripts for checking code style.

---

config/application_unit_test.py
config/unix-g++.cmake
config/unix-ifort.cmake
config/windows-cl.cmake
environment/elisp/format-f90.el

* The default developer environment on ccs-net machines started using Python3 instead of Python2 about a week ago.  Capsaicin tests that use python to run `gdiff` are failing due to a Python 2->3 compatibility oversight.  This PR attempts to fix this issue.
+ The `run_gdiff` function from `application_unit_test.py` wasn't working correctly with Python3 because `subprocess.communicate()` was returning a byte array instead of a character string. This is related to Python3's support for unicode character sets. A `decode('UTF-8')` operation was added convert the data stream to a set of strings.  The new code was tested with both Python2 and Python3.
+ The `capsaicin_output_check` function from `application_unit_test.py` was updated to simplify how false-positives are detected.  The new …

Fix a compatibility issue related to Python3

---

src/mesh_element/Element_Definition.cc
src/mesh_element/Element_Definition.hh
src/norms/Norms_Index.hh
src/norms/Norms_Index.t.cc
src/norms/Norms_Index.t.hh

* Improve code coverage of the mesh_element and norms packages by adding tests or removing features.
* Related to #465 
+ In `Element_Definition.cc`, comment out `construct_pentagon()` as it is not tested and apparently not used.
+ In `Norms_Index`, comment out `reset()` as it is not tested and apparently not used.
* Reference:
* Checks

Improve mesh_element and norms code coverage

---

src/quadrature/Galerkin_Ordinate_Space.cc
src/quadrature/Galerkin_Ordinate_Space.hh
src/quadrature/Ordinate_Set_Mapper.hh
src/quadrature/Ordinate_Space.cc
src/quadrature/Ordinate_Space.hh
src/quadrature/QIM.hh
src/quadrature/QIM__Parser.cc
src/quadrature/test/quadrature_test.hh
src/quadrature/test/tstDouble_Gauss.cc

* While preparing to review McGrid, I ran into some issues with the code coverage in Draco.  This PR attempts to improve the code coverage statistics for the quadrature package.
* Partial replacement for #465
* [Related to Redmine Issue #1265](https://rtt.lanl.gov/redmine/issues/1265)
* I've commented out chuncks of code in `Galerkin_Ordinate_Space.cc` because they are untested and replaced that code with an `Insist`.  If this code is needed in the future, it can be reactivated and a unit test should be added.
+ In `Ordinate_Set_Mapper.hh`, I commented out member function `ordinate_set()` as it is untested and unused.
+ While I left this untested code active, we should return to it and add appropriate unit tests (see Redmine issue 1265).
- compute_n2lk_2Da_
- compute_n2lk_1Da_
+ In …

Improve quadrature coverage by adding tests or removing features.

---

src/quadrature/Galerkin_Ordinate_Space.hh
src/quadrature/Ordinate_Space.cc
src/quadrature/Ordinate_Space.hh
src/quadrature/test/quadrature_test.cc

The prune function of Ordinate_Space always returns true, and on this basis it was removed from the class. However, this is a virtual function that is nontrivially overridden by Galerkin_Ordinate_Space, and its removal changes the solution slightly in one of the Capsaicin benchmarks.
The difference is quite small, but until I can better recall why this was done in the first place, I suggest we restore the Ordinate_Space::prune function and restore the if-test using prune.
* Reference:
* Checks

Restore the prune function to Ordinate_Space.

---

src/ds++/UnitTest.hh
src/units/MathConstants.hh
src/viz/Ensight_Translator.cc
src/viz/Ensight_Translator.i.hh
src/viz/test/tstEnsight_Translator.cc

* Jayenne requires extended functionality of the _viz_ package. 
+ Allow the `ensight_dump` function to accept `vector<unsigned>` containers in addition to `vector<int>`. This required a little bit of cleanup in the function to keep all of the data types compatible.
+ Add a unit test for the new `ensight_dump` signature.
* Reference:
* Checks

Extend rtt_viz::Ensight_Translator's ensight_dump function.

---

src/c4/Compare.cc
src/c4/ofpstream.cc
src/c4/opstream.cc
src/c4/opstream.hh
src/ds++/DracoStrings.hh

* While working through runtime issues in McGrid, I realized that some issues were caused by out-of-range array access in `ofpstream` and `opstream`.  
+ Provide logic to avoid `&vector[0]` dereference operations when the vector has zero length.
+ Fix comment blocks, spelling errors, etc.
* Reference:
* Checks

Fix some issues in ofpstream that were causing McGrid to fail.

---

config/vendor_libraries.cmake

+ Newer _GSL_ installs on Windows provide `gsl-config.cmake` that should be used to create the _GSL_ import targets instead of attempting to use the CMake _Module_ mode, `FindGSL.cmake`, method of finding _GSL_.
+ Change the order in which we call various GSL-discovery modes.
1. Try CMake's `CONFIG` mode (looks for `gsl-config.cmake` in `CMAKE_PREFIX_PATH`).
2. Try to find `gsl-config.sh` (Linux's package-config mode) and use this script to identify `GSL_ROOT_DIR` before calling (3).
3. Try CMake's `FindGSL.cmake` (`MODULE` mode).
* Reference:
* Checks

Fix GSL discovery.

---

src/diagnostics/draco_info.cc
src/ds++/CMakeLists.txt
src/ds++/Release.cc
src/ds++/Release.hh
src/ds++/bin/CMakeLists.txt
src/ds++/config.h.in
src/ds++/test/tstPacking_Utils.cc
src/quadrature/test/tstTri_Chebyshev_Legendre.cc

+ The `draco_info` executable had become disconnected from the build system. Several fields were printing blank or incomplete information.  This PR attempts to update `draco_info` so it works properly.
+ Replaces a portion of #479
+ Use `CMAKE_SYSTEM_NAME` for the *system type* field.
+ When printing compiler flags, ensure that the current flags are printed when the build type is `RelWithDebInfo`.
+ When printing the Design-by-Contract level, also print a string to indicate enabled modes.
+ When printing paths to compilers and the list of compiler flags, format the text to have a maximum width and use a hanging-indent.
+ Add support for Multi-config build systems (Xcode, VS) by adding a compile definition `$<CONFIG>`.
+ Use renamed CPP macros for `build_type` and `build_date`.
+ Since I'm …

Fix broken draco_info tool.

---

appveyor.yml
config/platform_checks.cmake
config/query_fma.cc
config/windows-cl.cmake
environment/bashrc/.bashrc_slurm
environment/bashrc/.bashrc_tt
src/FortranChecks/f90sub/drel.f90

+ The compile option `/arch:AVX2` was always enabled for Visual Studio, but pre-Haswell hardware does not support AVX2.  While the compiler could still create code, it would fail to run properly. To avoid this, we add a platform check for AVX2 capabilities -- actually the check already existed in `config/query_fma.cc` but it needed a small change to narrow the check to AVX2 only.
+ Modify `query_fma.cc` to take command line arguments `-f` and `-a`, which limit the check to fma-availability or avx2-availablity only. This code will return `1` if those features are found.
+ Update `platform_checks.cmake` to compile and run `query_fma.cc` and then set the build variables `HAVE_HARDWARE_AVX2` and `HAVE_HARDWARE_FMA`. These values are saved to `ds++/config.h` and are also available when the …

Avoid compiling for AVX2 instructions on older hardware.

---

environment/bashrc/.bashrc_tt

* Fix bug reported by Kent.
* While csk and ndi were loaded for regression tests, they were not automatically loaded for developers. This PR fixes the problem.
* Reference:
* Checks

Ensure csk and ndi are loaded by default on trinity/trinitite.

---

config/CMakeAddFortranSubdirectory.cmake
config/compilerEnv.cmake
config/setupMPI.cmake
src/FortranChecks/f90sub/CMakeLists.txt
src/quadrature/ftest/CMakeLists.txt

+ Our build system support for MSYS2 gfortran subprojects underneath a Visual Studio configuration is still a bit fragile.  This PR slightly improves this situation be consolidating the configuration of Microsoft MPI when used by a CMakeAddFortranSubdirectory subproject.
+ Add a new function to `CMakeAddFortranSubdirectory.cmake` to ensure `gfortran` configuration is compatible with Microsoft MPI for both x86 and x64 configurations.  This replaces code blocks that were duplicated in `FortranChecks/f90sub/CMakeLists.txt` and `quadrature/ftest/CMakeLists.txt`.
+ Fix comment blocks.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&v …

WIP: Clean up CAFS portion of build system to support x86 and x64.

---

src/ds++/DracoStrings.cc
src/ds++/DracoStrings.hh

* Fix build failure on Mac's associated with parse_number_impl
* Reference:
* Checks

Fix build failure on Mac's associated with parse_number_impl

---

src/mesh/X3D_Draco_Mesh_Reader.cc
src/mesh/X3D_Draco_Mesh_Reader.hh
src/mesh/test/tstX3D_Draco_Mesh_Reader.cc

* X3D format does not appear to permit specification of side flags, for boundary condition (B.C.).
* The X3D `Draco_Mesh` reader set the side flag to 0, for only one B.C in `Draco_Mesh`.
* It can be useful to have the B.C.s specified in the `Draco_Mesh` container.
* Permit `Draco_Mesh` to obtain non-trivial side flags from the X3D parser.
* [Concerns Redmine Issue #1182](https://rtt.lanl.gov/redmine/issues/1182)
+ Add optional side flag index vector to X3D reader constructor.
+ Map of side index to flag index for parsed boundary (bdy) files.
+ Update X3D parser test.
* Reference:
* …

Generalize X3D boundary condition specification.

---

config/CMakeAddFortranSubdirectory.cmake
src/rng/test/kat_c.c
src/rng/test/time_serial.h
src/rng/test/ut_gsl.c
src/rng/test/ut_uniform.cpp

* A few build warnings were introduced into the Visual Studio regression builds after a recent merge.  These were not caught be CI because the CI doesn't link against MPI and because the CI does a 32-bit build instead instead of 64-bit like the nightly regression testing.
+ Ensure that gfortran uses `-fno-range-check` compiler options to avoid a problem with MS MPI.
+ Suppress build warnings in Random123 headers and related to rng unit tests.
* Reference:
* Checks

Fix warnings/errors reported in Visual Studio regressions.

---

environment/bashrc/.bashrc_slurm

* A bug was introduced into the draco dev environment for trinitite.  This one-char delta fixes the problem.

Remove extraneous paren in .bash_slurm

---

src/parser/Expression.cc
src/parser/test/tstConsole_Token_Stream.cc
src/parser/test/tstFile_Token_Stream.cc
src/parser/test/tstParallel_File_Token_Stream.cc
src/parser/test/tstString_Token_Stream.cc
src/parser/utilities.cc

* PR #497 introduced a few build warnings that were not caught by existing CI. This PR addresses those Visual Studio build warnings.
* [Redmine #1207](https://rtt.lanl.gov/redmine/issues/1207) provides a better resolution, but that solution not ready yet.
+ Minor changes to code logic in `Expression.cc` and `utilities.cc` to eliminate "unreachable code" warnings. Instead of using return statements embedded in conditionals, allow the function to reach the final `return`.
+ Eliminate `unittest.failmsg` calls that appear after explicit calls to C++ `throw`. Instead, add a bool to ensure that the C++ assertion was thrown and caught.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filterco …

Minor code cleanup to eliminate build warnings from Visual Studio

---

src/rng/test/kat_c.c
src/rng/test/kat_cpp.cpp
src/rng/test/time_serial.h
src/rng/test/ut_Engine.cpp
src/rng/test/ut_aes.cpp
src/rng/test/ut_carray.cpp

* The Release builds had a few more warnings that I needed suppress.  These warnings are for unused or unset variables that are used in the Debug version by assert and DbC checks.
* Added `#pragma warning(disable: 4100)` to several unit tests in _rng_.
* Reference:
* Checks

Add more pragmas to suppress warnings found in R123 headers.

---

config/platform_checks.cmake
config/unix-xl.cmake
environment/bashrc/.bashrc
environment/bashrc/.bashrc_darwin_fe

* There is interest in trying to develop on the power9 and arm nodes of Darwin.  I've isntalled our TPLs  onto darwin for
* power9: gcc/7.3.0 + openmpi/3.1.2
* arm: gcc/8.2.0 + openmpi/3.1.2
* Update developer environment for darwin/arm and darwin/power9 nodes.
* Also update compiler flags for XLC.
* Reference:
* Checks

Update developer environment for Darwin.

---

environment/bashrc/.bashrc_slurm
regression/ccscs-regress.msub
regression/checkpr.sh
regression/sync_autodoc.sh

* Capsaicin team members have requested that the regressions that are run to check a pull request also generate and publish doxygen-based autodoc html.
* [Fixes Redmine Issue #1284](https://rtt.lanl.gov/redmine/issues/1284)
+ Teach the 'Release' PR regression to attempt to build autodoc (ccscs2 only).
+ Autodoc for PR will be created at /ccs/codes/radtran/autodoc/pr999 and will be published at https://rtt.lanl.gov/autodoc/pr999.
+ Autodoc directories will be removed after 3 days.
+ Add the `sync_autodoc.sh` script that rsyncs /ccs/codes/radtran to rtt.lanl.gov via crontab.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=- …

Teach the PR regression system to also build autodoc.

---

CMakeLists.txt
ChangeLog
regression/scripts/release_cray.sh
regression/scripts/release_toss.sh
src/ds++/Release.cc

Draco-6_25_0 is released
* Merge the Draco-6_25_0 back to the *develop* branch.
* Reference:
* Checks

Merge Draco-6_25_0 release back to develop

---

src/memory/memory.cc
src/memory/test/tstmemory.cc

Add delete with size to complement unsized delete. The former is a ne… C++14 feature that rightly generates a warning.
The memory package replaces new and delete with versions that are internally tracked to give superior diagnosis of memory usage when debugging code. This is done by replacing the system global operator new(size_t) and operator delete(void *) with versions that intercept memory allocation calls before passing on the requests to C malloc and free. The intercepting code keeps track of active allocations and the maximum total allocation and helps developers identify memory high water marks.
C++14 introduced operator delete(void *, size_t) for cases where the compiler can deduce the size of the original allocation  and pass this information on as a hint to the memory manager. …

Add delete with size to complement unsized delete. 

---

environment/bashrc/.bashrc_darwin_fe
environment/bashrc/.bashrc_slurm

We are trying to get basic builds and tests working on the ARM nodes of Darwin (at LANL).  After patching random123 to eliminate an `#error` macro the codes were building but may tests were crashing in openmpi.
We are using gcc-8.2.0 and openmpi/3.1.2.
+ Howard P., Nathan H. and David R. helped me with an environment-based work around for the openmpi failures.
+ When using the Draco developer environment, we also needed to purge the module environment before sourcing `.bashrc_darwin` to remove invalid x86 paths.
* Reference:
* Checks

A couple of tweaks to fix build/run on Darwin ARM nodes.

---

environment/git/f90-format.el
environment/git/install-hooks.sh
environment/git/pre-commit
environment/git/pre-commit-f90-format

* In an attempt to make our F90 code more stylistically consistent, provide a new style check that will be run as a pre-commit hook in git.  The new script will use emacs (if available, otherwise this check will be skipped) to ensure indentation is consistent (indentation style is controlled by `f90-format.el`).  The shell script will also ensure that all code lines are shorter than 80 columns.
* Provide a style check pre-commit hook for F90 code.
* [Fixes Redmine Issue #1250](https://rtt.lanl.gov/redmine/issues/1250)
+ Update the `install-hooks.sh` to provide the new scripts.
+ Provide a shell script `pre-commit-f90-format` and associated `f90-format.el` emacs lisp program.
+ When `git commit` is run, the `pre-commit-f90-format` shell script will be run.  If this script reterns a …

Provide new git commit hooks that test f90 code style.

---

src/ds++/CMakeLists.txt

* @clevelam reported that Xcode failed to configure draco due to a per file per configuration CPP define instruction. 
* Fixes #532
* Add special logic for Xcode in `ds++/CMakeLists.txt`.
* Reference:
* Checks

Fix a cmake logic error related to XCode.

---

regression/check_style.sh
regression/scripts/common.sh
src/FortranChecks/f90sub/Draco_MPI.F90
src/FortranChecks/f90sub/derived_types.f90

* The `check_style.sh` script is used by the Travis CI style check.  Currently, only C/C++ code is checked.  This PR extends style checks to include F90.  We will be adding flake8 based formatting checks for python soon, so this is a good opportunity to make ths script more extensible.
* Provide an interactive style check (`style_check.sh`) to report style issues in F90 files.  This script can be run be developers and will be run by Travis CI.
* [Fixes Redmine Issue #1250](https://rtt.lanl.gov/redmine/issues/1250)
+ Rework the `check_style.sh` script so that it has the following behavior.
- Normal mode:
1. Loop over all touched files, Print a fail message and a diff on failure.
2. Test each modified C/C++ file for clang-format conformance (no changes here). Print the patch file upon …

Add F90 style and line-length checks to check_style.sh

---

.travis.yml
config/autodoc_macros.cmake
config/compilerEnv.cmake
config/component_macros.cmake
regression/check_style.sh
src/cdi_analytic/Analytic_Models.cc
src/cdi_analytic/Analytic_Models.hh
src/cdi_analytic/Pseudo_Line_Analytic_MultigroupOpacity.hh
src/cdi_analytic/Pseudo_Line_Analytic_Odfmg_Opacity.cc
src/cdi_analytic/Pseudo_Line_Analytic_Odfmg_Opacity.hh
src/cdi_analytic/Pseudo_Line_Base.cc
src/cdi_analytic/Pseudo_Line_Base.hh
src/cdi_analytic/nGray_Analytic_Odfmg_Opacity.cc
src/cdi_analytic/nGray_Analytic_Odfmg_Opacity.hh
src/cdi_analytic/test/tstAnalytic_EoS.cc
src/cdi_analytic/test/tstAnalytic_Odfmg_Opacity.cc
src/memory/memory.cc
src/memory/memory.hh
src/memory/test/tstmemory.cc
src/timestep/test/tstTimeStep.cc
src/timestep/ts_advisor.cc
src/timestep/ts_advisor.hh

* #471 and #472 contain changes to improve code coverage.  They also include more general code cleanup for portions of the code base that we rarely edit.  Because these PRs might break Capsaicin, I've marked them as WIP, but the general changes should be merged soon.  Thus, the creation of this PR.
* I also discovered that the `make autodoc` target wasn't setting the doxygen option `WARN_AS_ERROR` as designed.  
* Mostly changes and additions to documentation blocks.
* Update how the Travis CI uses variables to fix this issue (export more variables to the docker image). Fixes #537.
* Add some notes to cmake files about how some build system related variables are set (language standards, PIC, etc.)
* Also fixes #538
* Reference: …

More cleanup

---

config/dracoVersion.cmake
config/unix-g++.cmake
regression/ccsnet3-crontab

+ The current cmake code thinks the minor version is not set if it is zero. Used  `DEFINED` in the check to fix this issue.
+ Sneak in two other minor changes.
- Update a comment about setting `-flto` when using g++.
- Archive the crontab used on ccsnet3.
* Reference:
* Checks

Fix a bug related to setting version numbers.

---

autodoc/CMakeLists.txt
config/autodoc_macros.cmake
config/doxygen_config.in
src/ds++/Safe_Divide.hh

* I'm trying to stand up a Jayenne gitlab runner CI that builds the autodoc target (Jayenne uses the Draco build system and links to Draco libraries). While working this feature, I needed to enhance the Draco build system's autodoc capabilities.
* [Related to Redmine Issue #1315](https://rtt.lanl.gov/redmine/issues/1315) and linked issues.
* [Related to Redmine Issue #1330](https://rtt.lanl.gov/redmine/issues/1330)
* Teach DBS how to set doxygen options `ENABLED_SECTIONS` and `INCLUDE_PATH` when configuring `doxygen_config`. Also re-enable the `TAGFILES` entry and set doxygen option `MACRO_EXPANSION=YES`.
- `ENABLED_SECTIONS` allows the use of the doxygen `\cond` command.
- `MACRO_EXPANSION=YES` allows Draco Design-by-Contract CPP macros to be understood by doxygen.  However, the …

Enhance autodoc features.

---

regression/covclass_cmake.cfg
regression/draco_regression_macros.cmake
regression/update_regression_scripts.sh

* While taking a closer look at the bullseye coverage report, I realized that the run scripts in the regression directory were not being updated as expected.  A quick triage of the issue revealed some script logic errors that were fixed.
* [Fixes Redmine Issue #1335](https://rtt.lanl.gov/redmine/issues/1335)
+ Rewrote portions of `update_regression_scripts.sh` that run 'git pull`.
+ Also remove some deprecated "NR" logic from the regression scripts.
+ Also update the bullseye coverage configuration file to exclude 'test_common' subdirectories that live in package directories.
+ Output looks something like this
```
Executing ./update_regression_scripts.sh ...
...
Updating /scratch/regress/draco...
==> cd /scratch/regress/draco; git pull
error: Your local changes to the following files …
```

Update regression environment to fix script-update bug.

---

config/FindCOMPTON.cmake
config/vendor_libraries.cmake
src/compton/test/tCompton.cc

* Previously, we had not attempted to build the compton package when building on Win32/VS2017.
* With a few tweaks, CSK was successfully and installed built under VS2017.
* This minor update enables finding, linking-to and running the compton tests.
* Reference:
* Checks

Add compton to VS2017 regressions.

---

regression/scripts/cray-env.sh
regression/scripts/cts-env.sh

* I forgot to do this in the last PR, when I removed the version specification for csk in other locations
* remove 0.4.0 version spec from regression environments
* see above :)
* Reference:
* Checks

Remove csk-0.4.0 version specification from regression scripts so 0.4.1 can be loaded

---

config/autodoc_macros.cmake
config/doxygen_config.in
environment/bashrc/.bashrc_tt
environment/elisp/draco-config-modes.el
regression/ccscs2-crontab
regression/cts1-regress.msub
src/c4/ParallelUnitTest.hh
src/c4/ParallelUnitTest.i.hh
src/ds++/Assert.hh
src/ds++/ScalarUnitTest.i.hh

* This change set includes a handful over very small changes to address minor issues and to adapt to changing environments.
* [Fixes Redmine Issue #1354](https://rtt.lanl.gov/redmine/issues/1354) (cyclic file deps)
+ Update the cmake `set_autodocdir` macro to do a better job of importing settings found in the developer's environment.
+ Modify the doxygen configuration file so that dot produces `png` image files instead of `svg` image files.  The `svg` files where causing link issues in published documents.
+ Eliminate two cyclic file dependencies:
- ScalarUnitTest.hh <--> ScalarUnitTest.i.hh
- ParallelUnitTest.hh <--> ParallelUnitTest.i.hh
+ In `Assert.hh`, add some logic that ensures that all Design-by-Contract CPP macros are defined for the current `DBC_LEVEL`.  Previously, if …

Misc updates to prepare for next release

---

src/mesh/Draco_Mesh.cc
src/mesh/Draco_Mesh.hh
src/mesh/X3D_Draco_Mesh_Reader.i.hh

* In 2D, it is simpler to assume rotation-ordered face-node pairing in `Draco_Mesh::Layout`.
* For instance, it is easier to determine orientation of a normal vector to a face.
* Since the `X3D` and `RTT` mesh file parsers preserve counterclockwise node ordering in 2D, the generation of the connectivity data (for instance, cell-to-cell linkage) can be made somewhat less computationally complex.  
* Keep node ordering in generation of [cell, side, ghost cell]-node vector pairs, where vector is subscripted by cell-local face index (which simplifies generation of mesh connectivity data in 2D).
* Add some missing comment documentation for functions arguments in `Draco_Mesh.cc` and `X3D_Draco_Mesh_Reader.i.hh` 
* Fixes Issue #524
+ Generate Draco_Mesh Layouts assuming rotation-ordered node …

Order nodes counterclockwise for each face in `Draco_Mesh::Layout`.

---

src/diagnostics/test/tstTiming.cc

* diagnostics/test/tstTiming.cc missing <iomanip> in seldom-compiled code path
* add #include <iomanip>
* see above
* Reference:
* Checks

Added missing header.

---

.clang-format
src/c4/CMakeLists.txt
src/c4/bin/CMakeLists.txt
src/c4/bin/xthi.cc
src/c4/bin/xthi.hh
src/c4/bin/ythi.cc
src/ds++/SystemCall.cc
src/ds++/config.h.in
src/ds++/path.hh

* These applications were excluded from the Visual Studio build because they used Linux kernel specific calls to obtain the affinity bitmask.
* I have added a Windows kernel equivalent of the non-portable code and moved these two code blocks into a new file, `xthi.hh`.
* I also updated some of the CPP macro logic used to select Windows vs. Linux kernel commands to deal with the half-Linux, half-Windows MinGW environment.
* Reference:
* Checks

Enable xthi and ythi builds/tests for Visual Studio.

---

src/parser/Class_Parse_Table.hh
src/parser/test/tstClass_Parser.cc
src/parser/utilities.hh

The Class_Parse_Table template is a useful idiom for writing parsers for class objects, but as presently formulated, it requires the developer to copy some tedious boilerplate. There is also presently  no way to propagate improvements to the boilerplate automatically. This is because the develop must explicitly specialize the template for every class for which a parser is needed, but the boilerplate must be included in the specialization to conform with the parse_class_from_table template function.
Simplify development and maintenance of Class_Parse_Table specializations.
Add a boilerplate base class template, Class_Parse_Table_Base, which automatically adds the boilerplate to the Class_Parse_Table which inherits it. 
Also, the current model of having separate parse_class templates with …

Add boilerplate base for Class_Parse_Table 

---

config/autodoc_macros.cmake
src/ds++/FMA.hh

* Jayenne uses the FMA macro to select accurate vs fast fused-multiply-add operations.  This allows us to use a high precision software version when hardware FMA are not available.
* [Related to Redmine Issue #1363](https://rtt.lanl.gov/redmine/issues/1363)
* [Related to Redmine Issue #1364](https://rtt.lanl.gov/redmine/issues/1364)
* Eliminate the `FP_ACCURATE_FMA` mode for machines w/o hardware FMA.  Replace this with the CPP macro `FMA_ACCURATE`.
* For machines with hardware FMA, use the software call if it is faster, otherwise send `a*b+c` to the compiler
* For machines w/o hardware FMA, only use the very slow software call when `FMA_ACCURATE` is requested.
* Provide a special developer toggle `FMA_FIND_DIFFS` that can be set to have every call to FMA compute values using the software …

Modify/Upgrade how the FMA CPP macro works.

---

environment/bashrc/.bashrc_toss3
environment/bashrc/.bashrc_tt
src/ds++/FMA.hh

* On machines where group 'ccsrad' doesn't exist, modules ndi and csk were not being loaded.  Update logic to do the right thing.
* Don't assume that ndi and csk live in directories marked with group 'ccsrad'.  Instead, just see if the directory can be read.
* Reference:
* Checks

Fix a module load error

---

src/cdi_analytic/Analytic_Models.cc
src/cdi_analytic/Analytic_Models.hh
src/cdi_analytic/nGray_Analytic_Odfmg_Opacity.cc
src/cdi_analytic/test/tstAnalytic_Gray_Opacity.cc

* Stimulated_Emission_Analytic_Opacity_Model was poorly tested.
* Code duplication was a problem in Polynomial_Analytic_Opacity_Model.
* There was no capability to model an analytic bound-free opacity (edge).
* Removed Stimulated_Emission_Analtyic_Opacity_Model by adding stimulated
emission as an option to Polynomial_Analytic_Opacity_Model that is off by
default.
* Added a bound-free component to Polynomial_Analytic_Opacity_Model that is off
by default. The bound-free component has the same energy, temperature, and
density scaling as the free-free component. Only the edge location and strength
of the edge need to be specified.
* Made the constant offset part of the analytic opacity truly constant. It no
longer scales with density.
* Reference: …

Simplifying and extending analytic opacity models

---

src/rng/Halton_Sequence.cc

* Make 1-line change to remove warning for an unused variable in Release, caught by Clang 6
* Upgrade assertion from `Require` to `Insist` when checking against `NUMBER_OF_KNOWN_PRIMES` in `Halton_Sequence` ctor.
* Reference:
* Checks

Upgrade Require to Insist to avoid unused variable warning (found in Clang Release build).

---

regression/ccscs-job-launch.sh
regression/ccscs-regress.msub
regression/checkpr.sh
regression/cts1-regress.msub
regression/darwin-regress.msub
regression/draco_regression_macros.cmake
regression/sync_repository.sh
regression/sync_vendors.sh
regression/tt-regress.msub

* The Transport teams use the scripts found in Draco's regression directory to control CI and nightly testing.  A code restructuring in one of these projects necessitates an update to the regression system.  This PR attempts to implement all the necessary changes.
* In reality, the non-draco, project specific scripts should probably be moved away from the Draco code repository.
* [Fixes Redmine Issue #1378](https://rtt.lanl.gov/redmine/issues/1378)
+ Many changes to scripts to improve how file and directory permissions are established.  The biggest change is to try and set the group sticky bit (GID) for newly created directories.
+ Remove references to capsaicin by replacing them with core, npt or trt.
+ Update `checkpr.sh` to teach it about trt and npt dependencies.  In particular, …

Updates to the regression system to support TRT and NPT

---

config/vendor_libraries.cmake
regression/Draco_Win32.cmake
regression/draco_regression_macros.cmake
src/VendorChecks/test/tstSuperludist.cc

+ These changes have been 'hot' in our regression system for several weeks.
+ Switch to parallel compiles for regressions.  Some of this is hard coded for now.
+ Incremental updates toward supporint SuperLU-DIST on win32/Visual Studio.
- Loook for the superlu-dist library during vendor discovery.
- Use proper CPP macros in `tstSuperludist.cc` to enable compiler specific pragmas.
* Reference:
* Checks

Updates for win32 regressions

---

src/ds++/config.h.in
src/ds++/test/CMakeLists.txt
src/ds++/test/tstData_Table.cc

+ An older test fails to compile for RelWithDebInfo build type. This is due to new sanitizer checks and is correct behavior.  Use CPP macros to remove this portion of the test for RelWithDebInfo build types.
* Reference:
* Checks

Fix RelWithDebInfo builds.

---

src/cdi/CDI.cc
src/cdi/CDI.hh
src/cdi/test/tCDI.cc

* There are several places within the Jayenne library where we use `collapseMultigroupOpacitiesPlanck` and `integrate_Planck_Spectrum` where the function call site is a bit cluttered by building vectors to pass to these functions. In the case of `collapseMultigroupOpacitiesPlanck` we rarely use the CDF it takes as an argument and populates. This PR simplifies these two functions.
* Provide a version of `collapseMultigroupOpacitiesPlanck` that does not require a vector of CDFs as an argument.
* Provide a version of `integrate_Planck_Spectrum` that returns a vector instead of setting a passed in vector.
* [Fixes Redmine Issue #1401](https://rtt.lanl.gov/redmine/issues/1401)
* Add a version of collapseMultigroupOpacitiesPlanck that doesn't calculate the groupwise CDF (this is not needed by …

Simplify some function signatures in CDI calls

---

src/VendorChecks/test/tstSuperludist.cc

+ There are 8 build warnings in `tstSuperludist` issued by Visual Studio:  `warning C4706: assignment within conditional expression`
* [Related to Redmine Issue #1227](https://rtt.lanl.gov/redmine/issues/1227)
+ This commit fixes the build warnings but the test is still failing for unknown reasons.  I will defer examining this failure due to its low priority.
* Reference:
* Checks

Eliminate 8 build warnings (Visual Studio)

---

config/unix-xl.cmake
config/unix-xlf.cmake
src/FortranChecks/test/CMakeLists.txt

* We were asked to evaluate the latest XL compilers on Darwin.  Bottom line is that the XL compilers don't seem to have support for C++14.  
* We still want to capture the updated compiler flags and options so more testing can be done on Sierra.
* [Fixes Redmine Issue #1126](https://rtt.lanl.gov/redmine/issues/1126)
+ Tested on Darwin/p9 (`module load ibm/xlc-16.1.1.2-xlf-16.1.1.2-gcc-7.3.0`)
+ This version of XL will not compile Draco.  It breaks when we use `std::unique` from `<algorithm>`.
+ This change set captures flags used while testing on Darwin.  This work will continue on Sierra.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&com …

Update compile flags for XL.

---

src/mesh/Draco_Mesh.cc
src/mesh/Draco_Mesh.hh
src/mesh/Draco_Mesh_Builder.hh
src/mesh/Draco_Mesh_Builder.t.hh
src/mesh/X3D_Draco_Mesh_Reader.cc
src/mesh/X3D_Draco_Mesh_Reader.hh
src/mesh/X3D_Draco_Mesh_Reader.i.hh

+ A compile warning showed up for VS2017 after a recent merge. Fixed.
+ Also fix some typo/spelling issues.
* Reference:
* Checks

Eliminate a compile warning

---

src/cdi_ipcress/python/demo_modify_ipcress_file.py
src/cdi_ipcress/python/demo_read_data.py
src/cdi_ipcress/python/ipcress_reader.py
src/cdi_ipcress/python/plot_ipcress_opacity.py

* The IPCRESS file reader was not working with Python 3.0, which is now loaded by the draco environment. This makes the reader and plotter compatible with python 2.7 and 3.0 (tested on snow). I've also added the ability to write opacity data to an IPCRESS file, this is useful for turning off absorption or scattering or manually limiting opacity values. I've added a new demo to the repository that shows how to use this feature (I wanted this feature specifically for testing the Compton spectrum instead of having to hard code absorption opacity to zero in my test code).
* [Fixes Redmine Issue #1416 ](https://rtt.lanl.gov/redmine/issues/1416)
* Encode the string values read from the binary file with UTF 8 for python 3.0 compatibility
* Add the ability to write data to an IPCRESS file for a …

Tweak IPCRESS reader for python 3.0

---

config/vendor_libraries.cmake
environment/bashrc/.bashrc_slurm
regression/cts1-regress.msub
regression/sync_repository.sh
regression/tt-regress.msub
regression/update_regression_scripts.sh

* Regression testing has had some issues lately with accessing the github and gitlab repositories.  Rework the authentication method used by these scripts to improve robustness.
* Also tweak a couple of other items like MKL discovery and linking and output formatting for the bash alias `slimits`.
+ Rework the way the regression system authenticates so that access to the code repositories is more robust.
+ Make the bash function 'slimits' a little more useful
+ Also tweak MKL discovery and link commands.
* Reference:
* Checks

Change authentication method for nightly regression.

---

src/c4/bin/xthi.hh

* Change output format of xthi/ythi so it's closer to the usual.
* See above
* As above
* Reference:
* Checks

Minor fix: xthi & ythi output formatting

---

src/viz/Ensight_Translator.hh
src/viz/Ensight_Translator.i.hh
src/viz/test/tstEnsight_Translator.cc

* Ensight file generation either appends existing ensight files or fully overwrites them.
* For better consistency with restart behavior, it may be worthwhile to permit partial rewriting of Ensight dump files: overwriting dumps after a time provided to the Ensight translator.
*  The implementation in this PR is supposed to be flexible enough to preserve old behavior, and even permit overwriting Ensight dumps some number of cycles after a restart.
* Permit partial overwriting of Ensight dumps when not fully overwriting.
* [Fixes Redmine Issue #1425](https://rtt.lanl.gov/redmine/issues/1425)
+ Add optional reset time parameter to ctor of Ensight_Translator.
+ Erase dump times after reset time from case file parsed in ctor.
+ Update Ensight_Translator unit test to test a partial overwrite.
* …

Add graphic dump reset time, to refine overwrite behavior.

---

config/unix-intel.cmake

* There was an additional C++ standard flag set in the Intel CMake file. As far as I can tell, it was being overridden by the actual C++ flag set through CMake commands but it's still confusing to see two `-std=c++XX` flags on a verbose compile line.
* Let CMake set the c++ standard
* Remove `-std=c++11` from `unix-intel.cmake`
* Reference:
* Checks

Use CMake  to set C++ standard flags for Intel

---

config/setupMPI.cmake

* We don't normally build with mpich as the MPI provider.  We commonly use OpenMPI, Spectrum, Cray-MPICH or Microsoft MPI.  A request was made to allow the use of mpich on Linux.
* Fixes #605 by providing support for mpich as the MPI provider on Linux machines.
* item+ Rework logic in `setupMPI.cmake` to discover `MPI_FLAVOR` and `MPI_VERSION` via a new cmake function `setMPIflavorVer`.  Store these variables in `CMakeCache.txt`.
+ Add very generic support for mpich.
* Reference:
* Checks

Teach the build system about mpich.

---

config/vendor_libraries.cmake

* I didn't fully test some of the CMake for the new `CUDA specific device code and I had a few syntax errors in CMake. This pull request corrects those errors and adds a language level to the `nvcc` compiler, set through the `CMAKE_CUDA_STANDARD` variable.
* Fixes bug in CUDA specific CMake code
* Fix `set` statements that were not terminated properly
* Add `FORCE` to the set statement for `CMAKE_CUDA_FLAGS`
* Set the `CMAKE_CUDA_STANDARD` to 14
* Reference:
* Checks

Fix errors in CMake CUDA flags and set the NVCC language level to 14

---

src/CMakeLists.txt

* PR #597 enabled `-fsanitize=address` options. The impact of testing this compiler option was not tested sufficiently by the automatic PR testing and it caused massive failure for the nightly regressions.
* Fixes #608 : compile/run failure when Draco is built with gcc in Debug mode.
* Comment out these gcc-only compiler flags and provide a note about why they
were removed
* Reference:
* Checks

Fix issues that appeared after PR597 was merged

---

environment/bashrc/.bashrc
environment/bashrc/.bashrc_cray
src/CMakeLists.txt

* LANL has two new HPC resources, Capulin and Thunder.  These are ARM machines with a Cray software stack.
* For now, we will only support the GNU toolchain on these systems.
* [Related to Redmine Issue #1229](https://rtt.lanl.gov/redmine/issues/1229)
- Rename `.bashrc_tt` to `.bashrc_cray`
- Update `.bashrc_cray` to query and setup different Cray systems in slightly different ways.
- Use PrgEnv-intel on Trinity/Trinitite
- Use PrgEnv-gnu on Capulin/Thunder (at least for now).
- A few TPLs aren't available on Capulin/Thunder just yet (csk, ndi, clang-format).
* Reference:
* Checks

Add support for Capulin and Thunder (LANL ARM systems)

---

src/memory/memory.cc
src/memory/memory.hh
src/memory/test/tstmemory.cc

Take another stab at a portable test of rtt_memory::out_of_memory_handler. Also, bring this function into conformance with the standard, by having it set the memory handler to null and return rather than directly throw a bad_alloc.
Issue 1268 is that rtt_memory::report_leaks is neither documented nor tested. Coverage analysis also shows that rtt_memory::out_of_memory_handler is not tested. The line to install this handler is commented out of the unit test program.
The current implementation of rtt_memory::out_of_memory_handler does not conform to the standard, since it throws a bad_alloc directly. The standard calls for this function to set the out of memory handler to nullptr if it cannot resolve the allocation failure, and then the new allocator knows to throw bad_alloc itself. 
* …

Fix issue 1268 by documenting and testing report_leaks.

---

src/VendorChecks/test/CMakeLists.txt
src/VendorChecks/test/superlu-dist-wrapper.h
src/VendorChecks/test/tstSuperludist.cc

+ Recently, gcc-8.1.0 regressions have started to generate the following compile warning:
```
superlu_dist_config.h:2:6: warning: "XSDK_INDEX_SIZE" is not defined, evaluates to 0 [-Wundef]
```
+ Since the issue isn't related to code that we own, I have created a
suppression as described below.
* Fixes #614
+ Wrap the inclusion of this header in a new file `superlu-dist-wrapper.h` and update the list of include directories to allow the build system to find the new file.
+ Tag `superlu_ddefs.h` with `pragma GCC system_header` to prevent GCC from creating warnings about code found in the TPL header.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildn …

Fix build warnings related to superlu_ddefs.h.

---

environment/bashrc/.bashrc_cray
regression/push_repositories_xf.sh
src/VendorChecks/test/CMakeLists.txt
src/memory/test/CMakeLists.txt
src/memory/test/tstmemory.cc

+ `VendorsChecks_tstSuperludist_4` has been failing for Win32 for a while.  There is a problem with the the Win32 build of superlu-dist.  I don't have time to fix this right now and this test isn't particularly important for Draco or Jayenne.
+ A new 'unused variable' warning showed up late last week (`tstmemory`).  This test also fails when `fpe_trap` is enabled.
+ Disable tstsuperludist for WIN32 platforms.
+ Comment out unused variable.
+ Disable `memory_tstmemory` when `DRACO_DIAGNOSTICS=7` (fpe_trap enabled).  This removes it from the _fulldiagnostics_ regression suite.
+ Also
- For Cray systems, force `KMP_AFFINITY=disabled` via the developer bashrc files to avoid a thread affinity issue identified by Tim.
- Add sanity checks to `push_repository_xf.sh` after Jae reported issues when …

Cleanup warnings/errors reported on CDash.

---

config/setupMPI.cmake

* Minor tweak in build system logic to [fix redmine issue 1242](https://rtt.lanl.gov/redmine/issues/1242)
* Reference:
* Checks

Teach DBS to find and use mpirun found at /usr/bin.

---

src/units/FundUnit.hh
src/units/MathConstants.hh
src/units/PhysicalConstants.hh
src/units/PhysicalConstantsSI.hh
src/units/UnitSystem.hh
src/units/UnitSystemEnums.cc
src/units/UnitSystemEnums.hh
src/units/UnitSystemType.cc
src/units/UnitSystemType.hh
src/units/test/tstFundUnit.cc

+ If client codes are built statically, they fail to run because portions of the unit package are initialized in the wrong order.  Some of the global static variables use other global static data during initialization and if the order is wrong, the code with generate a segmentation violation.
+ A discussion on this and the associated remedy is provided at https://isocpp.org/wiki/faq/ctors#static-init-order.
+ This fixes a long standing issue in our codes.
* [Fixes Redmine Issue #962](https://rtt.lanl.gov/redmine/issues/962)
+ Mark global static data `constexpr`.
+ In `UnitSystemEnums.hh`, also change the global static data types to `constexpr`.  This required transforming `std::string` data types to string literals (e.g.: `char constexpr foo[]`).  The array size for `double[]` was removed …

Attempt to fix a static initialization fiasco issue.

---

src/cdi_analytic/Compound_Analytic_MultigroupOpacity.cc
src/cdi_analytic/Compound_Analytic_MultigroupOpacity.hh
src/cdi_analytic/Compound_Analytic_Odfmg_Opacity.cc
src/cdi_analytic/Compound_Analytic_Odfmg_Opacity.hh
src/cdi_analytic/test/tstAnalytic_Gray_Opacity.cc
src/cdi_analytic/test/tstAnalytic_Odfmg_Opacity.cc
src/cdi_analytic/test/tstCompound_Analytic_MultigroupOpacity.cc

Likewise rename nGray_Analytic_Odfmg_Opacity to Compound_Analytic_Odfmg_Opacity.
Change Compound_Analytic_MultigroupOpacity to use group structure when calculating opacities, to make it consistent with Compound_Analytic_Odfmg_Opacity previously used in Capsaicin.
The Capsaicin project is, so far as we know, the only client for the OdfmgOpacity class hierarchy. This was written to support experiments on using opacity distribution functions for thermal transport calculations. The results were not encouraging and no further work has been done in this direction in years, nor do we foresee any further work in the future. Capsaicin has therefore abandoned support of opacity distribution functions.
This removes significant code bloat from Capsaicin, but falling back to MultigroupOpacity from …

nGray_Analytic_MultigroupOpacity to Compound_Analytic_MultigroupOpacity

---

src/cdi_ipcress/python/demo_read_data.py
src/cdi_ipcress/python/ipcress_reader.py

* @attom fixed some file reading errors in the python ipcress file reader. He added an ASCII decode step from the `UTF-8` read that fixed some parsing errors.  I've applied those fixes and tested them on several ipcress files.
* Better python 3.0 compatibility for python ipcress reader
* Decode utf-8 read to ascii in the dictionary build phase of ipcress_reader.py
* Change "has_key" in demo_read_data.py to python 3 style string in  dictionary
* Reference:
* Checks

More Python 3.0 changes for python ipcress reader

---

config/setupMPI.cmake
environment/bashrc/.bashrc_darwin_fe
environment/elisp/draco-config-modes.el
regression/darwin-regress.msub

* Supported TPLs and development environment continues to evolve on Darwin ARM, Power9 and Volta nodes.
+ Update default module sets for ARM, Power9+CUDA and x86+CUDA.
+ Update emacs python-mode defaults.
+ Update regression scripts to use newer TPLs.
+ Tweak setupMPI.cmake to support more versions of OpenMPI that are found on Darwin.
* Reference:
* Checks

Darwin environment updates.

---

.travis.yml
regression/Dockerfile
regression/packages.yaml
regression/travis-run-tests.sh

* I created a new docker container that can be used for Travis CI tests.
* The goal was to update the toolchains used for Travis builds.
* Begin using gcc-8.3.0.
* cmake 3.11.4 --> 3.14.4
* openmpi 3.1.1 --> 3.1.4
* superlu-dist 5.2.2 --> 5.4.0
* trilinos-12.12.1 --> 12.14.1
* gsl-2.3 --> 2.5
* python3 is provided in this container
* Build instructions:
```
cd /D f:\work\docker
docker build --rm --pull --tag draco-ci-2019may:latest .   
docker commit -m "blah" -a kinetictheory <container-name> \
kinetictheory/draco-ci-2019may:latest # queues for upload
docker login -u kinetictheory (and password)
docker tag draco-ci-2019may kinetictheory/draco-ci-2019may:latest
docker push kinetictheory/draco-ci-2019may
```
* Reference: …

New docker container for Travis

---

src/CMakeLists.txt
src/RTT_Format_Reader/CellDefs.cc
src/cdi/CDI.hh
src/cdi_ipcress/test/tIpcress_Interpreter.py
src/ds++/Assert.hh
src/parser/utilities.cc
src/parser/utilities.hh
src/units/PhysicalConstantsSI.hh

+ numdiff is [failing](https://rtt.lanl.gov/cdash/testDetails.php?test=9646521&build=28883) for `tIpcress_Interpreter` on Win32. 
+ Slightly loosen the comparison tolerance for `tIpcress_Interpreter` to allow the test to pass.
+ Remove deprecated `DLL_PUBLIC` decoration from a couple of files.
+ Add a note about packages dependencies in `src/CMakeLists.txt`.
* Reference:
* Checks

Loosen tolerance for cdi_ipcress test.

---

config/application_unit_test.py

+ The win32 version of `numdiff.exe` is sensitive to the order of arguments.  Specifically, optional arguments must be listed before the two file names.
* [Fixes Redmine Issue #1513](https://rtt.lanl.gov/redmine/issues/1513)
+ Update the python to fix argument order when there are optional arguments.
* Reference:
* Checks

In application_unit_test.py, fix numdiff argument order.

---

.travis.yml
appveyor.yml
regression/Dockerfile
regression/mirrors.yaml

* Alex noticed that the new docker image didn't have all of the autodoc tools needed to fully test this build mode.
* With this image in place, we now require cmake-3.14 or later due to python discovery patterns that not backward compatible with older cmake.  The new cmake is required for correct cuda discovery.
* fixes #628 
* Add mscgen, python3-sphinx, and  python3-sphinx-rtd-theme to the Docker image used by Travis
* Update standard version of tools, including cmake and python both Travis and Appveyor.
* Reference:
* Checks

Add mscgen and sphinx to the CI docker image.

---

src/units/PhysicalConstants.cc
src/units/PhysicalConstants.hh

* intel 17 fails to compile Draco 7.2.0
* The PhysicalConstants class was reorganized slightly so as to become literal, thereby accommodating the `constexpr` methods in that class.
* Fixed in coordination with @RyanWollaeger.
* [Fixes Redmine Issue #1551](https://rtt.lanl.gov/redmine/issues/1551)
* Default `PhysicalConstants` constructor definition moved to `PhysicalConstants.hh` and decorated with `constexpr` tag.
* Reference:
* Checks

Fix constexpr compilation error with intel 17

---

src/mesh/Draco_Mesh_Builder.t.hh
src/mesh/test/tstDraco_Mesh.cc

* There are some [build warnings](https://rtt.lanl.gov/cdash/index.php?project=Draco&date=2019-06-27) from MSVC in the current `develop` branch. 
* Minor tweaks to fix a few types.
* @RyanWollaeger The 'unreachable code' warning is another case of our need for C++17's `constexpr if`.  I decided to suppress the warning for now.  The suppression can be removed when we adopt C++17.
* Reference:
* Checks

Fix MSVC build warnings.

---

src/c4/test/tstQueryEnv.cc
src/ds++/SystemCall.hh

* We use a macro to wrap the set/unset environment calls since these are system dependent.  Move the definitions to an easily accessed location so other codes can make use of these CPP macros.
* Move these definitions of `draco_setenv` and `draco_unsetenv` from `test/tstQueryEnv.cc` to `ds++/SystemCall.hh` so it can also be used by other codes.
* Reference:
* Checks

Move draco_setenv to systemcall.hh

---

CMakeLists.txt
config/CMakeLists.txt
config/buildEnv.cmake

+ The previous install location (`<prefix>/cmake/draco/`) is no longer considered a standard location.
+ historical note: an even older location was `<prefix>/cmake/draco-X.X.X/` but this was difficult to maintain and the version number was dropped.
+ The current preferred location is `<prefix>/cmake`.
* [Fixes Redmine Issue #1573](https://rtt.lanl.gov/redmine/issues/1573)
* Reference:
* Checks

Relocate the installed cmake config directory.

---

config/unix-g++.cmake
config/windows-cl.cmake
src/c4/C4_MPI.t.hh
src/cdi/CDI.cc
src/cdi/CDI.hh
src/cdi/test/tCDI.cc
src/ds++/Constexpr_Functions.hh

* I've been looking into the cycle initialization and finalization times in Jayenne and Draco's various Planck and Rosseland integration functions show up as being fairly expensive in the profiler. I've tried to reduce the number of times they're called in Jayenne but I also noticed a few possible improvements to the integration routines themselves. The two main improvements are relaxing some input checking and making a comparison value `constexpr`. Currently, `sqrt(std::numeric_limits<double>::max()` is calculated every time a Planck integration routine is called. This value should be a `constexpr` but due to `sqrt` not being marked as `constexpr` the function is evaluated every time. I introduced a very simple version of `sqrt` for these kinds of cases into `ds++`.
* This PR also …

Performance tweaks for Planck and Rosseland integration

---

config/CMakeAddFortranSubdirectory.cmake
config/setupMPI.cmake
src/cdi_eospac/CMakeLists.txt

* CAFS stopped working recently for one client project.  The main issue is that FindMPI was failing for a MInGW Makefile project spawned from a MSVC project. It is unclear what changed to cause this UseCase to fail, but it is likely that updating the CMake version was the issue.
* A new warning `LNK4099` is also being issued when pdb files for TPLs aren't found.  I will suppress this warning as a link flag.
* When defining an import library as used by CAFS, look for the lib in the project build directory, but look for the dll in the `${CMAKE_RUNTIME_OUTPUT_DIRECTORY}`.
* When setting up C4 variables, allow MPI to remain active if *either* `MPI_CXX_FOUND` or `MPI_C_FOUND` are true.  This allows cmake projects that use C but not C++ to work properly. 
* Reference: …

Fix some Win32 issues related to CAFS.

---

config/windows-cl.cmake
src/cdi_eospac/CMakeLists.txt
src/cdi_eospac/test/tEospac.cc
src/compton/CMakeLists.txt

* Recent versions of MSVC have starting issuing warnings when the `.dbg` file associated with a library isn't found when linking Debug code.  I thought this issue was restricted to `libeospac.lib`, but it turns out other TPLs also cause this warning to be emitted.
* [Example of warnings](https://rtt.lanl.gov/cdash/viewBuildError.php?type=1&buildid=38735)
* I'm pulling the change to `cdi_eospac/CMakeLists.txt` that I made in #649 and replacing it by moving the `ignore` link flag to the global `LINK_OPTIONS` CMake variable.
* Minor tweaks to comments.
* Reference:
* Checks

MSVC: Suppress link warning

---

config/component_macros.cmake
config/windows-cl.cmake

* #650 didn't completely eliminate a build warnings issued by MSVC.  It eliminated build warnings related to linking libraries, but did not address identical warnings issued when creating executables.
* Ref [CDash report](https://rtt.lanl.gov/cdash/viewBuildError.php?type=1&onlydeltap&buildid=40109)
* No longer set `CMAKE_EXE_LINKER_FLAGS` in `windows-cl.cmake`.  Instead, set a build system variable `CMAKE_EXE_LINKER_FLAGS`.  In `component_macros.cmake`, set the `LINK_OPTIONS` target property the new variable for `LINK_FLAGS`.
* Use generator expressions to limit the use of this flag to _Debug_ builds.
* This model serves as a prototype of how compiler flags will be set in the near future.
* Reference:
* [CDash …

Another attempt to suppress MSVC warnings about .dbg files.

---

.travis.yml
tools/Dockerfile

* Autodoc checks were issuing warnings/errors because latex and ghostscript were not provided in the docker image.  These tools are needed for doxygen to generate graphics from latex style formulas.
+ new docker image: draco-ci-2019aug
+ includes ghostscript and texworks.
+ Also add more notes about how to update the docker image.
* Reference:
* Checks

Update docker image used by CI.

---

src/cdi/test/DummyEICoupling.cc
src/cdi/test/tDummyEICoupling.cc
src/cdi_analytic/Analytic_EICoupling.cc
src/cdi_analytic/Analytic_Models.hh

* Fix comments about ei_coupling units to be consistent [kJ/cc/keV/s]
* [Fixes Redmine Issue #1610](https://rtt.lanl.gov/redmine/issues/1610)
* Reference:
* Checks

cleanup ei-coupling comments about units

---

config/CMakeLists.txt

* Consumers of TRT codes are switching to cmake-based build systems and have asked for this standard file used by `find_package`.
* [Fixes Redmine Issue #1670](https://rtt.lanl.gov/redmine/issues/1670)
* Create and install the requested file.
* Reference:
* Checks

Provide draco-config-version.cmake when installing.

---

config/component_macros.cmake
src/rng/CMakeLists.txt

* The _rng_ package was not correctly exporting a transitive dependency on Random123's include directory forcing client codes to manually add this dependency.  This TPL dependency is slightly different than others in Draco because it is a header-only package.
* [Fixes Redmine Issue #1712](https://rtt.lanl.gov/redmine/issues/1712)
* I attempted to update the logic to use CMake's built-in capabilities for exporting targets, including their `INTERFACE_INCLUDE_DIRECTORIES` property.  However, CMake doesn't seem to be able to use generator expressions for values assigned to this property (issue reported [here](https://gitlab.kitware.com/cmake/cmake/issues/19791)).
* So, for now, I'm sticking with the existing hack that manually exports target properties.  With the changes provided in this PR, …

Update algorithm for exporting target properties.

---

src/c4/bin/ythi.cc
src/c4/test/tstofpstream.cc
src/diagnostics/draco_info.hh
src/ds++/Assert.cc
src/ds++/DracoStrings.cc
src/ds++/SystemCall.hh
src/ds++/path.hh
src/ds++/path_getFilenameComponent.cc
src/ds++/test/tstAssert.cc

* While working a couple of other issues, a handful of updates crept into my sandbox.  I think these changes are worth keeping.
+ Change how `ythi` sets `YTHI_NUM_WORKERS` so that when run from a machine that is running SLURM, the `get_cpus_per_task` function is queried.
+ In `tstofpstream` change `ofstream` to `ifstream` to match actual use.  This showed up as a warning on one machine.  Also add a more verbose diagnostic if the test fails.
+ Remove `DLL_PUBLIC` decoration from `draco_info`.
+ MSVC only: Add a `define _WINSOCKAPI_` to prevent a possible system header conflict related to the order in which `windows.h` and `winsock2.h` are included.
+ Clean up comments, indentation, spelling length of divider lines, etc.
* Reference: …

Two minor tweaks and some formatting fixes.

---

environment/bashrc/.bashrc

* It appears that the bash_aliases.sh path variable can be empty before it is sourced for interactive sessions.
* Apologies - I may close this, having learned that DRACO_ENV_DIR is supposed to be set by users; something like this may still be useful if DRACO_SRC_DIR is not set.
* Export `DRACO_ENV_DIR=${DRACO_SRC_DIR}/environment` before sourcing bash_aliases.sh.
* Reference:
* Checks

Move export DRACO_ENV_DIR before use in path to alias script.

---

src/ds++/Data_Table.hh
src/ds++/DracoMath.hh

* A new feature of the NVCC compiler allows device code to call host code if it's marked with `constexpr` (https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#options-for-altering-compiler-linker-behavior-expt-relaxed-constexpr). Draco has not been thoroughly marked for `constexpr` but this practice makes compiling GPU code much easier as constexpr functions work naturally on the CPU and GPU without any decoration or special compilation steps. When compiling the GPU libraries needed by Jayenne the `Data_Table` and `linear_interpolate` functions were needed in GPU code. These can both be marked `constexpr` (if `constexpr` values were passed to these functions they would return `constexpr` values and be evaluated at compile time).
* Allow GPU libraries to link against more Draco …

Mark some functions constexpr

---

config/FindGrace.cmake
config/unix-g++.cmake
config/unix-pgf90.cmake
environment/bashrc/.bashrc_darwin_fe
src/ds++/terminal/terminal.h

+ On Darwin, serveral new regression failures are being reported.  Fix these issues.
+ Also, install csk/0.5.0 and use it in the nightly regression tests.
* [Fixes Redmine Issue #1746](https://rtt.lanl.gov/redmine/issues/1746)
+ Update `FindGrace.cmake` to be more agressive in checking the the local Grace (ggrace or xmagrace) install is fully functional.  If `gracebat` fails, then report that Grace is not available.  This will fix the broken `plot2D` tests because we will no longer build or test this package on Darwin.
+ Add a note to `unix-g++.cmake` about possible ARM-specific compile flags.
+ Fix a spelling error in `unix-pgif90.cmake` that prevented the compile flags from being used.
+ Update the environment bashrc files to load csk/0.5.0 by default.
+ Add some guards around …

Address regression issues reported on Darwin:

---

config/generate_dll_declspec.cmake
src/c4/CMakeLists.txt

* After a recent PR was merged (#700), static builds were broken.
+ A change in `generate_dll_declspec.cmake` introduced a build failures for `DRACO_LIBRARY_TYPE=STATIC`.  Instead of triggering the CPP `#error` based on the CPP symbol `DRACO_SHARED_LIBS` use `rtt_dsxx_config_h` as this will exist for static builds while the previous symbol will not exist.
+ Also, install `xthi.hh` as part of c4 as this is needed by one of our clients.
* Reference:
* Checks

Fix static build.

---

src/units/PhysicalConstexprs.hh
src/units/test/tstPhysicalConstexprs.cc

* The constexpr physical constants PR from a few days ago used CODATA 2018 values. This switches to CODATA 2010 values, and evaluates derived constants directly, for compatibility.
* See background
* See background
* Reference:
* Checks

Rewind PhysicalConstexprs to CODATA 2010 values

---

src/c4/QueryEnv.hh

* gcc on snow is reporting signed/unsigned comparison [warnings. ](https://rtt.lanl.gov/cdash/viewBuildError.php?type=1&buildid=8745)
* Modify return types from `QueryEnv.hh` to fix warnings.
* Reference:
* Checks

Return uint32_t instead of int.

---

src/compton/config.h.in
src/diagnostics/config.h.in
src/experimental/mdspan

+ Provide a bit of cleanup after #714 and #715 to keep LLVM-based builds free of warnings.  The first of these PRs added `mdspan`.  The second turned on LLVM build warning for illegal CPP macro names.
+ Ref: https://rtt.lanl.gov/cdash/viewBuildError.php?type=1&buildid=10669
+ Fixes #718
+ Remove double underscores from CPP macros found in config.h.in files.
+ Add warnings suppressions for mdspan.
* Reference:
* Checks

Fix build warnings issued by LLVM related to illegal symbol names.

---

config/compilerEnv.cmake

+ Configuring the gcov-based coverage regression is broken.
+ Ref: https://rtt.lanl.gov/cdash/viewConfigure.php?buildid=10643
+ Fixes #720
+ Minor logic tweak in `compilerEnv.cmake` should fix the problem.
* Reference:
* Checks

Fix merge conflict that broke the gcov builds

---

config/platform_checks.cmake

* An error message is printed when building on Cray machines when environment variables like `CC` and `CXX` don't point to the Cray compile wrappers.  While helpful to most developers, this error can break spack-based builds.
* [Fixes Redmine Issue #1788](https://rtt.lanl.gov/redmine/issues/1788)
* Provide escape clause for this error.
* Reference:
* Checks

Only print help message related to CrayPE for non-spack builds.

---

src/device/GPU_Device.hh

* We're now compiling the GPU code nightly on darwin. This PR fixes type conversion warnings when device code is compiled.
* Clean up GPU code that's now being built and tested. 
* Fix `int` to `size_t` conversions in `device/GPU_Device.hh`
* Reference:
* Checks

Fix type conversion errors in GPU device helper

---

src/c4/test/CMakeLists.txt

* For regression runs that test code coverage, `tstythi` was only using 1 thread per MPI rank.  This left the `run_thread` function in `ythi.hh` untested.
* Forcing this test to use 2 threads fixed this missing code coverage check.
* Reference:
* Checks

Ensure that the ythi test uses more than 1 thread to improve code cov

---

config/setupMPI.cmake

* Capsaicin has requested better support in Draco for Intel-MPI and NGC has requested better support for MPICH.  Attempting to use either of these MPI implementations was causing Draco's configure stop to fail.
* [Fixes Redmine Issue #1803](https://rtt.lanl.gov/redmine/issues/1803)
* Remove a `FATAL_ERROR` from `setupMPI.cmake`.
* Also fix a compile warning related to builds with CUDA enabled.
* Reference:
* Checks

Make finding the MPI version more robust.

---

config/unix-cuda.cmake

* After #731, the power9 regressions fail to configure.
* Ensure `${CMAKE_CURRENT_BINARY_DIR}/config` exists before trying to create a file at that location.
* Reference:
* Checks

Fix power9 regression.

---

config/platform_checks.cmake
config/string_manip.cmake
src/CMakeLists.txt

* Make the cmake configure summary easier to read. 
+ No longer print the full TPL/Vendor summary unless `-DVERBOSE=ON` is provided to CMake. This shortens the report significantly.  Note that we already print the discovered path to each TPL.
+ When printing a summary of current compiler flags and the mpirun command, use a hanging indent to make the text easier to parse.
+ Sneak in a small change in `platform_checks.cmake` to do a better job of detecting when Draco is being built by spack.
```console
CXX Compiler: /scratch/vendors/spack.20180425/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-8.1.0-3c5hjkqndywdp3w2l5vts62xlllrsbtq/bin/g++
C FLAGS: -Wcast-align -Wpointer-arith -Wall -pedantic -Wno-expansion-to-defined -Wnarrowing 
-fopenmp -Werror -g -gdwarf-3 -fno-inline …
```

Cleanup and shorten the cmake configure report.

---

src/cdi_eospac/Eospac.hh
src/cdi_eospac/EospacException.hh
src/cdi_eospac/SesameTables.cc
src/cdi_eospac/SesameTables.hh

* While working on runtime failures related to eospac-6.4.0 under MSVC 2019, I fixed a number of spelling errors and formatting issues in `cdi_eospac`.
+ This commit is somewhat related to https://github.com/KineticTheory/eospac6/releases/tag/eospac-6.4.0 and https://github.com/KineticTheory/vcpkg. Both of these projects provide a modified version of eospac-6.4.0 that includes fixes related to MSVC 2019.
+ Fix spelling errors
+ Rewrap comment blocks at 80 columns.
* Reference:
* Checks

Fix spelling errors

---

.travis.yml
config/compilerEnv.cmake
tools/spack/lcov/package.py
tools/travis-run-tests.sh

* Travis isn't reporting code coverage (CodeCov.io).  The cause appears to be mismatch between gcc (version 8) and gcov (version 7).  Errors in the travis log look like the ones discussed [here](https://github.com/conan-io/conan-docker-tools/issues/161). 
* Attempt to install gcov-8 and use it instead of the default version of gcov.
* I also needed to install lcov-1.14 since older versions of lcov can't read the gcov-8 files.
* Use Draco's new ability to generate lcov-based reports (`cmake -DCODE_COVERAGE=ON; make covrep`).
* Enable the `fast_finish` option for Travis CI (report fail as soon as any of the four checks reports a failure).
* Reference:
* [CDash …

Fix broken codecov logic run by Travis and CodeCov.io

---

config/unix-ifort.cmake
environment/bashrc/.bashrc_darwin_fe

+ CMake versions have changed. Update env files.
+ Add one more compile flag for Intel-based debug builds.
* Reference:
* Checks

Fix dev-env for LANL darwin.

---

src/cdi_ndi/NDI_TN.cc

* NDI_TN in CDI_NDI broke CI
* Fix error in this module to fix CI. 
* `Remember` pairs with `Require`, not `Insist`; the latter pairing can fail for `DRACO_DBC_LEVEL=0`
* `Insist` -> `Require`
* Reference:
* Checks

Fix DBC mismatch in CDI_NDI

---

config/FindNDI.cmake

* NDI version 2.1.4alpha uses a new cmake build system and PIC was not enabled by default.  For this release of NDI, w need to select the 'pic' version of the library.
* [Fixes Redmine Issue #1837](https://rtt.lanl.gov/redmine/issues/1837)
* Reference:
* Checks

Help FindNDI.cmake find the PIC version.

---

.clang-format
README.md
config/component_macros.cmake

+ `.clang-format` was updated to register new draco components.  This update may change the order of include directives as sorted by clang-format.
+ The top level `README.md` was updated to include short descriptions of new components.
+ Fix a spelling error.
* Reference:
* Checks

Update some files after new components were added to Draco.

---

CMakeLists.txt
config/component_macros.cmake
environment/bashrc/.bashrc_darwin_fe

* We were seeing build failures on nodes that had GPUs that we were targeting with Cuda.  These failures seem to be related to a bug in cmake. 
* [Fixes Redmine Issue #1812](https://rtt.lanl.gov/redmine/issues/18212)
+ Change the default developer environment to use `cmake/3.16.4` instead of `cmake/3.15.3` This fixes some configuration/build issues when mixing C++ and Cuda.
+ Update some `CMakeLists.txt` files to shorten lines that were more than 80 columns wide.
* Reference:
* Checks

Minor cleanup after debugging session on darwin with GPUs.

---

config/vendor_libraries.cmake

* Client projects should use CMake's `find_package(Draco)` macro to find and define Draco targets and TPLs.  TPL link requirements should be transitive and automatic.  This small change in the installed `draco-config.cmake` script should fix current deficiencies.
* This design deficiency was discovered recently when Draco builds began linking against _libquo_ but client projects didn't have any knowledge of this dependency and the _libquo_ requirements were not provided transitively.
* When `draco-config.cmake` is sourced by client projects, ensure that all required TPLs are also found and associated _import targets_ are created.  This is done via the Draco CMake macro `setupVendorLibraries`.
* Reference:
* [CDash …

Find draco's TPL via draco-config.cmake.

---

src/c4/CMakeLists.txt
src/c4/xthi_cpuset.hh

* Similar to windows systems the hardware architecture needs to be queried differently the linux. This PR supplies the necessary information to do so.  
* Fix xthi and ythi issues on apple
* [Fixes xthi ythi issue on apple #1849](https://rtt.lanl.gov/redmine/issues/1849)
* Reference:
* Checks

fix xthi ythi for apple builds

---

src/c4/test/tstifpstream.cc

* We had parallel contention on the tstifpstream because we were overwriting the the parallel file for each parallel run case while it was still being read. This was fixed by using a different file name for each parallel instance of the test.
* Add number of nodes to the output/input filename
* Reference:
* Checks

fix tstifpstream

---

config/FindEOSPAC.cmake
config/component_macros.cmake
config/generate_dll_declspec.cmake
config/print_target_properties.cmake

+ Nightly regressions that target Visual Studio 2019 show `compton_tCompton_1` failing. I discovered that this test failure was cased by linking to one compton.dll file by when the test was executed a different dynamic library was called.
+ I modified the logic in `copy_dll_link_libraries_to_build_dir` (`component_macros.cmake`) to copy the correct flavor (Debug vs. Release) to the test installation.  This change required a small chagne to `FindEOSPAC.cmake` to keep it working.
+ Also fix a minor typo in `generate_dll_declspec.cmake` that could prevent `DLL_PUBLIC` function decoration from working properly.
+ Minor updates were added to the build system's debug helper `print_target_properties.cmake`.
* Reference:
* …

MSVC: Fix link issue related to CSK for Debug builds.

---

src/FortranChecks/f90sub/Draco_MPI.F90
src/c4/C4_MPI.cc
src/c4/C4_MPI.hh

* [Fixes Redmine Issue #1873](https://rtt.lanl.gov/redmine/issues/1873)
+ Provide a new `extern "c"` function that allows us to set `rtt_c4::initialized` from a Fortran function.
* Reference:
* Checks

Allow QuoWrapper to work correctly when mpi_init called from F90.

---

src/c4/bin/CMakeLists.txt

* If OpenMP is not found, xthi will not build
* skip building xthi with compilers that do not support OpenMP.
* place xthi target and install directives in conditional block
* Reference:
* Checks

Disable build of xthi if OpenMP is not found.

---

src/cdi_ndi/NDI_AtomicMass.cc

* Passing zaid=2004 to NDI_AtomicMass would cause NDI to return 7 AMWs (for zaid=2004 and other zaids like 20040)
* Tom Saller showed me how to fix this: append a "." to the zaid.
* Fix this bug by passing e.g. "2004." instead of "2004"
* [Fixes Redmine Issue #1884](https://rtt.lanl.gov/redmine/issues/1884)
* Reformat the ZAID when converting from an integer before passing to NDI.
* Reference:
* Checks

Fix for NDI AMW usage

---

src/ds++/Packing_Utils.hh
src/ds++/Soft_Equivalence.hh

* These are showing up on the CDash report.
* Reference:
* Checks

Fix a couple of clang-tidy warnings.

---

config/ApplicationUnitTest.cmake
config/component_macros.cmake
config/setupMPI.cmake

+ Jae noticed that we were using a CMake variable incorrectly.
+ Proper use is described at https://cmake.org/cmake/help/v3.17/module/FindMPI.html?highlight=mpiexec_preflags#usage-of-mpiexec
* [Fixes Redmine Issue #1856](https://rtt.lanl.gov/redmine/issues/1856)
*  This PR renames `MPIEXEC_POSTLFAGS` to `MPIEXEC_PRELAGS` to correct the issue.
* Reference:
* Checks

Fix variable name MPIEXEC_PREFLAGS.

---

src/ds++/test/CMakeLists.txt

* The clang-tidy build was still complaining about not finding `<stdexcept>`.
* [Fixes Redmine Issue #1889](https://rtt.lanl.gov/redmine/issues/1889)
* The error message only appeared for the test `do_exception`.  This is a special test that is configured in `ds++/test/CMakeLists.txt` and didn't use the normal macros from `config/component_macros.cmake`.  Test registration was missing the following required property that helps clang-tidy find the correct STL headers:
```cmake                                                 |
set_source_files_properties( ${tgt_sources} 
PROPERTIES 
INCLUDE_DIRECTORIES  ${CLANG_TODY_IPATH} 
)      
```
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&fil …

Help clang-tidy find correct STL headers.

---

config/FindNDI.cmake
src/cdi_ndi/CMakeLists.txt

+ `cdi_ndi` requires `NDI_ROOT_DIR` to be set, but not all module systems set this variable.  This is also the case for spack-based builds of jayenne that do not use modules for ndi.
* Fixes a spack build failure reported by asc_spackages developers.
+ If the Draco build system reports that ndi was found, but `NDI_ROOT_DIR` isn't set, then use other known information to extract the correct value and set `NDI_ROOT_DIR`.
+ Prune dead code from `FindNDI.cmake`.
* Reference:
* Checks

Automatically set NDI_ROOT_DIR if NDI is found.

---

config/platform_checks.cmake
src/ds++/config.h.in

+ Some of the checks in `platform_checks.cmake` will always fail for certain platforms.  Use this knowledge to skip these checks and thereby reduce configure time.
* Fixes #778
* Related to #779
+ Checks for `winsock` should only be done on `WIN32` platforms.
+ Checks for `unitstd.h` and `sys/param.h` should only be done on non-`WIN32` platforms.
+ Universally assume that `limits.h` and `direct.h` are available.
+ Checks for `gethostname` should only be done on non-`WIN32` platforms.
* Reference:
* Checks

Attempt to simplify platform_checks to speed up configure time.

---

src/c4/bin/CMakeLists.txt
src/c4/test/CMakeLists.txt

+ I ran across this issue while trying to use clang under Visual Studio.  The toolchain appears to behave similarly to apple-clang for OSX.  That is, `clang` doesn't support OpenMP.
+ The logic used to enable building `xthi` should match the logic used to enable `tstXthi.py`. 
* Related to #779
+ Update `src/c4/test/CMakeLists.txt` to make the enable/disable logic for `xthi` and `tstXthi.py` the same.
+ Update indentation, spacing, more more to cleanup these two `CMakeLists.txt`.
* Reference:
* Checks

Synchronize logic for enabling xthi and associated unit test.

---

config/component_macros.cmake

* Something was going wrong when my static library build with `CUDA_SEPARABLE_COMPILATION` was linked into other libraries and executables as a `cudaErrorInvalidDeviceFunction` was being thrown at runtime. The only way I've found so far to get around this error is to remove the separable compilation flag from static CUDA libraries.
* [Towards #1427](https://rtt.lanl.gov/redmine/issues/1427)
* Change the default setting for CUDA libraries to turn off CUDA_SEPARABLE_COMPILATION.
* Reference:
* Checks

Turn off separable compilation by default for CUDA libs

---

environment/bashrc/.bashrc_darwin_fe

* We hadn't updated the developer-environment for KNL nodes on Darwin for quite a long time.  
* [Fixes Redmine Issue #1898](https://rtt.lanl.gov/redmine/issues/1898)
+ Update module list and point to modules/TPLs built for x86_64.
```bash
export VENDOR_DIR=/usr/projects/draco/vendors
export DRACO_ARCH=x86_64
module use --append ${VENDOR_DIR}/user_contrib
module use --append ${VENDOR_DIR}-ec/Modules/$DRACO_ARCH
module load user_contrib
mflavor="$cflavor-openmpi-3.1.3"
lapackflavor="lapack-3.8.0"
noflavor="git random123 cmake gcc/7.3.0"
compflavor="cmake/3.16.4 gsl/2.5-$cflavor netlib-lapack/3.8.0-$cflavor numdiff/5.9.0-$cflavor random123/1.09-$cflavor metis/5.1.0-$cflavor eospac/6.4.0-$cflavor openmpi/3.1.3-gcc_7.3.0"
mpiflavor="libquo/1.3-$mflavor parmetis/4.0.3-$mflavor …
```

Update Draco dev environment to support KNL on darwin.

---

src/parser/Abstract_Class_Parser.hh
src/parser/Abstract_Class_Parser.i.hh

* The Abstract_Class_Parser uses std::pointer_to_unary_function, which is deprecated in C++11 in favor of std::function and dropped completely in C++17. std::pointer_to_unary function dates back to before the introduction of variable template argument lists, which allow std::function to represent all kinds of functions.
* Replace uses of std::pointer_to_unary_function with std::function.
* [Fixes Redmine Issue #775](https://rtt.lanl.gov/redmine/issues/775)
* Reference:
* Checks

Replace deprecated std::pointer_to_unary_function with std::function.

---

config/unix-g++.cmake
src/CMakeLists.txt

* Some flags were only enabled for gcc version > 5.0.  Since we always use version 6+, remove some of the extra logic.  
* Fixes #784
+ Move some gcc debug flags from `src/CMakeLists.txt` to `config/unix-g++.cmake`.
+ This doesn't change draco, but it does make some new flags the default for Jayenne: `-Wfloat-equal -Wunused-macros -fsanitize=bounds-strict -Wshadow -Wformat=2`
* Reference:
* Checks

Enable more gcc debug flags by default.

---

src/c4/xthi_cpuset.hh
src/cdi_analytic/test/tstCompound_Analytic_MultigroupOpacity.cc

* Found two minor bugs on Mac builds that result in compilation errors 
* Fix those bugs
* In `c4/xthi_cpuset.hh`, comment out parameters that are not used in the Apple implementation of sched_getaffinity.
* In `cdi_analytic/test/tstCompound_Analytic_MultigroupOpacity.cc`, rename `sig_t` to `sig_test`, since the former conflicts with a typedef in Apple's `sys/signal.h`.
* Reference:
* Checks

Fix minor errors on Apple

---

config/vendor_libraries.cmake
environment/bashrc/.bashrc_cray
environment/bashrc/.bashrc_cts1
src/diagnostics/CMakeLists.txt
src/diagnostics/qt/CMakeLists.txt
src/diagnostics/qt/diWidget.cc
src/diagnostics/qt/diWidget.hh
src/diagnostics/qt/main.cc
src/diagnostics/qt/mainwindow.cc
src/diagnostics/qt/mainwindow.hh

+ After upgrading to cmake-3.17.0, our one Qt example failed to configure or build. I have updated build system logic to match what cmake-3.17+ expects for Qt applications.
* [Fixes Redmine Issue #1900](https://rtt.lanl.gov/redmine/issues/1900)
+ Greatly simplify Qt discovery in `vendor_libraries.cmake`, but require Qt5 (disallow Qt3 or Qt4).
+ When building `diagnostics/qt` require cmake-3.17.0+:
+ Begin using `CMAKE_AUTOUIC` and `CMAKE_AUTORCC`.
+ CMake no longer requries the use of the macros `qt5_wrap_ui` or `add_resources`.
+ `.ui` files are now treated like source files.
+ Add code to delete move ctors and move assignment operators.
* Reference:
* [CDash …

Update to diagnostics/qt to reflect new cmake behavior.

---

environment/bashrc/.bashrc_ats2
src/diagnostics/CMakeLists.txt

+ I was finally able to build `trilnos % xl ^spectrum-mpi` on rznsel with spack.  But this requires a newer version of spack that we were using for the last two releases.
+ Update `.bashrc_ats2` to point to the new spack and load all relevant modulefiles.  This includes *trilinos*, *libquo* and *ndi* that were missing from the last spack instance.
* Also, don't attempt to build Qt-based applications from PPC.
* Reference:
* Checks

Rzansel: point to new spack instance for dev TPLs.

---

src/diagnostics/qt/CMakeLists.txt

+ The Intel compiler generates warnings about disabling IPO when linking to Qt run time libraries.  To eliminate the warning, disable IPO when linking to Qt run time libraries.
* [Fixes Redmine Issue #1904](https://rtt.lanl.gov/redmine/issues/1904)
* Reference:
* Checks

Eliminate compile warning from Intel.

---

src/cdi_eospac/CMakeLists.txt
src/compton/CMakeLists.txt

+ For cdi_eospac and compton, teach the build system to provide required dlls.
+ After #798, the build system no longer copied the eospac or compton dll to the build tree.  When these files are missing at run time, the tests will fail.
+ This PR fixes issue #802
+ TPLs provided by the vcpkg package manager know how to install themselves into the build tree.  This is what allowed the simplifications found in #798 to work.  However, eospac and compton are not currently provided by vcpkg, so they must be copied via `POST_BUILD` rules.
* Reference:
* Checks

Re-teach the build system to install eospac and csk dll files.

---

config/CMakeLists.txt
config/compilerEnv.cmake

* Coverage reporting is working as desired for draco, but not for client codes like Jayenne.  This update ensures that the new helper shell script is installed and available for client codes to use.
* [Related to Redmine Issue #1903](https://rtt.lanl.gov/redmine/issues/1903)
+ Install `capture_lcov.sh` so other projects can find and use this helper script.
+ Help client projects find `capture_lcov.sh` to allow the `covrep` build target to function correctly.
* Reference:
* Checks

Another tweak to help lcov reporting work for client projects.

---

config/CMakeLists.txt

* I'm still working out all of the kinks related to switching from BullseyeCoverage to gcov/lcov coverage reporting. I am hopeful this fixes the the last remaining issue.  The helper script `capture_lcov.sh` did not have execute permission when installed.
* [Related to Redmine Issue #1930](https://rtt.lanl.gov/redmine/issues/1930)
* When installing shell scripts use `install( PROGRAMS ... )` instead of `install(FILES ... )`.
* Reference:
* Checks

Installed shell scripts need +X permissions.

---

src/c4/test/tstQuoWrapper.cc

* A Quo test was failing on RZ Ansel that checked to see if number of available hardware threads that Quo sees matched the value of `std::thread::hardware_concurrency` (https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency). This difference is because Quo uses an hwloc command that gets the number of cores that are available for use (as set by the system admins) where as std::thread seems to just see the total number of cores on the machine (I don't know exactly how it gets this but its number matches the value in /proc/cpuinfo). We would like to only use the available cores and thus go with the answer Quo gives. I've modified the test to treat the `std::thread::hardware_concurrency` value as an upper bound.
* [Fixes Redmine Issue …

Fix quo test failure by treating std::thread as upper resource bound

---

.travis.yml
CMakeLists.txt
tools/Dockerfile
tools/spack/packages.yaml
tools/travis-run-tests.sh

* We are adopting cmake-3.17.0 as the minimum required version.  Update the docker image with this new install.  Also provide libquo, lcov, and eospac.
* Use updated docker image from dockerhub, `draco-ci-2020april`.
* Set `cmake_minimum_required(VERSION 3.17)`
* Travis script expects to find the following new items in the CI environment:
* cmake-3.17.0
* lcov
* eospac
* libquo
* The following packages are no longer provided 
* superlu-dist
* trilinos
* Reference:
* Checks

Update docker image with cmake-3.17.0 and more

---

environment/bashrc/.bashrc_darwin_fe

* Manually sourcing .bashrc on Darwin still loads earlier cmake version than 3.17.0.
* It looks like all partitions that .bashrc_darwin_fe checks for have cmake 3.17.0
* Update .bashrc_darwin_fe to load cmake 3.17 module, consistent with min version required.
* Update .bashrc_darwin_fe to load cmake 3.17.0 module.
* Reference:
* Checks

Update darwin bashrc to load cmake 3.17.0.

---

config/setupMPI.cmake

* _Perfbench_ regressions run one test at a time and when working with _libquo_, we want the work to be spread out across the available sockets.
* [Related to Redmine Issue #1881](https://rtt.lanl.gov/redmine/issues/1881)
* Provide a new variable `MPIEXEC_PREFLAGS_PERFBENCH` that can be used when registering tests under the `ENABLE_PERFBENCH=ON` regression mode.
* Reference:
* Checks

Provide a new variable for MPIEXEC_PREFLAGS for PERFBENCH.

---

src/cdi_ndi/CMakeLists.txt
src/cdi_ndi/NDI_AtomicMass.cc
src/cdi_ndi/NDI_Base.cc
src/cdi_ndi/NDI_Base.hh
src/cdi_ndi/NDI_TNReaction.cc
src/cdi_ndi/NDI_TNReaction.hh
src/cdi_ndi/config.h.in
src/cdi_ndi/test/CMakeLists.txt

* previously, the cdi_ndi library wasn't built *at all* when NDI was not found
* this is fine in theory, but it made things tricky in upstream code; because the NDI_FOUND cmake variable was not available, there was no obvious way to protect against includes of draco cdi_ndi header files that were not installed.
* Instead of omitting the cdi_ndi lib entirely when NDI is not found, stub out the routines that need NDI (have them throw assertions)
* This means that upstream code can be built without protecting cdi_ndi includes in macros -- the calls to cdi_ndi will just throw if it is not found
* This is needed to get a corresponding pull request in gitlab going (I will update the description of that PR shortly)
* update CMakeLists logic for cdi_ndi - there was previously a confusing …

Change CMake logic for lib cdi_ndi to ensure upstream code can build when NDI is not found

---

config/unix-xl.cmake
src/c4/test/tstTime.cc

* While working with McKay yesterday on XL build issues, I revisited our XL compiler flags. A couple of tweaks are worth making. 
* Also, try to make tstTime a little more robust.
+ No need to support very old XL.  Delete these from the settings.
+ Move the location of setting power9 specific options so that C++ flags also get these options.
+ Loosen tolerance for `tstTime`.  This test has never been stable, but I don't want to toss it because it is good to know that the code doesn't crash, even if the results are a little uncertain (its just a coverage test).
* Reference:
* Checks

Tweak XL compiler flags.

---

src/cdi_ndi/CMakeLists.txt
src/cdi_ndi/NDI_AtomicMass.cc
src/cdi_ndi/NDI_AtomicMass.hh
src/cdi_ndi/NDI_Base.cc
src/cdi_ndi/NDI_Base.hh
src/cdi_ndi/config.h.in
src/cdi_ndi/test/tstNDI_AtomicMass.cc
src/cdi_ndi/test/tstNDI_TNReaction.cc

* NDI's data and installation are not always collocated. `NDI_ROOT_DIR` points to the library installation location but not necessarily to the data location.
* `NDI_GENDIR_PATH` should point to the data location.
* Change `cdi_ndi` by adding a new variable `NDI_DATA_DIR` that helps locate the `gendir*` files. Save this value in `cdi_ndi/config.h` and use it in the library when looking for NDI data.
* Begin using `gendir` instead of `gendir.all` as the default NDI data file for this package. This change is based on new information from the NDI team.  The specialized constructor allows any NDI data file to be used, including `gendir.all`.
* I reworked the formatting of the `.cc` files to make it easier to distinguish between the stubbed-out version and the regular version.
* To improve …

Fix a bug in cdi_ndi related to expected data path.

---

src/CMakeLists.txt
src/c4/config.h.in
src/diagnostics/draco_info.cc

* I missed updating these three files when I changed Draco to use `MPIEXEC_PREFLAGS` instead of `MPIEXEC_POSTFLAGS`.
* Reference:
* Checks

Fix informational code concerning MPIEXEC_PREFLAGS.

---

CMakeSettings.json
config/buildEnv.cmake
src/cdi_eospac/CMakeLists.txt
src/compton/CMakeLists.txt

+ Update `CMakeSettings.json` so that it is more generic and easier to modify.
+ Wrap long lines in `buildEnv.cmake`.
+ Improve correctness and robustness of branching logic used to copy _eospac_ and _csk_ dll files to the build directory.
* Reference:
* Checks

Provide some logic cleanup for MSVC-based builds.

---

appveyor.yml
environment/bashrc/.bashrc_linux64
src/ds++/SortPermutation.hh

* While exploring the option to build with LLVM version 10, I found a bug in one Draco file.
* Add a copy constructor.
* Also,
* Add a debug print to the appveyor script. I was having trouble getting some extra regression environment tools to install correctly.
* Add a robustness check to `.bashrc_linux64` to ensure that a basic module environment is available on ccs-net machines.
* Reference:
* Checks

Update to support LLVM version 10.

---

config/setupMPI.cmake
config/unix-xl.cmake
config/unix-xlf.cmake
environment/bashrc/bashrc_slurm

+ It is difficult to debug on ATS-2 machines.  Building and testing on Darwin power9 nodes with the IBM XL compiler and Spectrum MPI provides a similar environment.
* [Fixes Redmine Issue #1948](https://rtt.lanl.gov/redmine/issues/1948)
+ Provide minor build system updates to support Draco builds for XL on Darwin.
+ The compiler option `--gcc-toolchain` appears to be ATS-2 specific so restrict it to ATS-2 machines.
+ Help the build system identify spectrum-mpi as installed on Darwin.
+ Update the draco developer environment so that X11 is automatically enabled for the salloc alias.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=buildname&compare1=63 …

Begin supporting IBM XL builds on Darwin

---

config/setupMPI.cmake

+ The desired flags provided to Spectrum-MPI's `mpirun` are the same as OpenMPI and different than the options used by Spectrum-MPI on rzansel (via `jsrun`). Tell the build system to configure tests with the correct options.
* [Fixes Redmine Issue #1948](https://rtt.lanl.gov/redmine/issues/1948)
* Reference:
* Checks

Spectrum-MPI on Darwin works the same as OpenMPI.

---

src/ds++/SortPermutation.hh

* A recent change to `SortPermutation.hh` to fix LLVM build issues, introduced a gcc build warning.
* fixes #828 
* Add  `noexcept` to the copy constructor.
* Reference:
* Checks

Fix build warning reported by gcc-9.2.0.

---

src/mesh_element/Geometry.hh

The new enumeration is consistent with common practice in hydrodynamics codes,
where the enumerated value is the number of suppressed dimensions. See the
expanded description of the enumeration in the modified definition for further
explanation.
By adopting an enumeration that matches many hydrocodes, we avoid having to do as much translation from host code enumeration to our library enumeration, with all the unpleasant surprises that brings.
* Reorder enumerators without changing their names. The corrensponding integral value for each enumerator then matches the common hydrodynamics code definition.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1&field1=bu …

Reorder enumeration of geometry in mesh_element/Geometry.hh

---

config/setupMPI.cmake
config/unix-xl.cmake
environment/bashrc/.bashrc_ats2
src/quadrature/test/quadrature_test.cc

* When building optimized builds with IBM XL, the quadrature unit tests and `dsxx_fpe_trap_2` fail.  Some tests launched with `jsrun` would report warnings.
* Fixes #830 
* [Fixes Redmine 1949](https://rtt.lanl.gov/redmine/issues/1949)
* Might fix test failures reported by XL-based regressions on Darwin.
**Changes for test registration:**
+ For _rzansel_, switch from using `jsrun` to `lrun`.  This fixes an issue where  `jsrun` was complaining about the requested number of threads being greater than the 4 hardware threads provided by each power9 core.
+ For rzansel, update the `MPIEXEC_PREFLAGS` so they work with `lrun`.
- `MPIEXEC_PREFLAGS="--pack --threads=1 --bind=off -v"`
- `MPIEXEC_OMP_PREFLAGS="--pack -c $ENV{OMP_NUM_THREADS} --threads=$ENV{OMP_NUM_THREADS} --bind=off -v"`
- …

Clean up testing environment for rzansel with XL.

---

src/c4/test/tstofpstream.cc

* KT was seeing intermittent failures in the ofpstream test, likely because of file system contention (the 1, 2, and 4-proc variants all wrote to / read from the same test file)
* [Fixes Redmine Issue #1950](https://rtt.lanl.gov/redmine/issues/1950)
* Change test file name to append the number of procs used by the test.
* Reference:
* Checks

Change filename in ofpstream test to be n-rank-dependent

---

src/cdi_eospac/test/CMakeLists.txt

* There are build environments where the Eospac libraries are installed but the data files are not available.
* If the Eospac libraries are found, always build the `cdi_eospac` library and some of the tests.
* Do not build are register `cdi_eospac` tests that require the eos data files, when those files are not available.
* Reference:
* Checks

Check availability of eos data before registering tests.

---

config/setupMPI.cmake
environment/bashrc/.bashrc_ats2

+ The `--pack` option assumes tests only use one core and one thread.  This is not appropriate for most Draco tests.
+ Also, set an environment variable to prevent warnings about oversubscribing.
* Reference:
* Checks

On rzansel, do not use the --pack lrun/jsrun option.

---

config/draco-config-install.cmake.in
config/platform_checks.cmake
config/setupMPI.cmake
config/unix-g++.cmake
config/unix-intel.cmake
src/CMakeLists.txt
src/ds++/CMakeLists.txt

+ CMake now provides a built-in mechanism that tells us if we are using Cray compiler wrappers. The value of `CMAKE_CXX_COMPILER_WRAPPER` will be `CrayPrgEnv`.
* [Fixes Redmine Issue #1661](https://rtt.lanl.gov/redmine/issues/1661)
+ Remove `CRAY_PE` from the build system and replace the existing logic with `CMAKE_CXX_COMPILER_WRAPPER`.
* Reference:
* Checks

Remove CRAY_PE from the build system.

---

src/mesh_element/Geometry.hh

* The Geometry enumeration has meaningful integer values for its enumerators, based on a common convention in hydrodynamics codes of specifying geometry by the number of suppressed dimensions. This value is actually used in computations in such codes.
* We should go just a bit further, and spell out that the base type of this enumeration is int. This should allow FORTRAN codes using the common convention to safely pass their geometry to C++ codes using iso_c bindings.
* Add base type of int to the Geometry enumeration.
* Reference:
* Checks

Spell out that the base type of Geometry is int.

---

environment/bashrc/.bashrc_darwin_fe

* Use no-cuda version of trilinos on darwin which is faster.
* [Fixes Redmine Issue #1964](https://rtt.lanl.gov/redmine/issues/1964)
* Load no-cuda version of trilinos
* Reference:
* Checks

Load no-cuda version of trilinos on darwin.

---

.travis.yml
tools/Dockerfile

+ The docker image has a different version of doxygen than the ccs-net machines.  This occasionally results in different nightly regression and CI behavior for the autodoc target.
+ [Fix Redmine 1707](https://rtt.lanl.gov/redmine/issues/1707)
+ Update doxygen in the docker image to 1.8.14 to match ccs-net.
* Reference:
* Checks

Update doxygen version in docker image.

---

config/buildEnv.cmake
config/dracoTesting.cmake
config/platform_checks.cmake

+ Perfbench tests have been failing recently and the issue was traced back to defects in the build system that are fixed by this PR.
* [Fixes Redmine Issue #2002](https://rtt.lanl.gov/redmine/issues/2002)
+ The value of `MPIEXEC_MAX_NUMPROCS` was set in several places in the build system.  Consolidate logic into a single location.
+ Eliminate the rarely used build target `check`.
+ Similar changes were also provided to the regression system.
* Reference:
* Checks

Fix test registration for trinitite (perfbench)

---

config/vendor_libraries.cmake
environment/bashrc/.bashrc

+ No longer look for `dia` as a tool to be used by `doxygen`.  `dia` is no longer maintained and is incompatible with newer tools like `python3`.
+ Fix an incorrect value for `NO_PROXY` in `.bashrc`.
* Reference:
* Checks

Minor tweak to dev environment.

---

config/configureFileOnMake.cmake
config/dracoVersion.cmake
src/c4/SLURM_Task_Info.hh
src/c4/bin/ythi.cc
src/c4/bin/ythi.hh
src/c4/test/tstQuoWrapper.cc
src/c4/test/tstSLURM_Task_Info.cc
src/ds++/Query_Env.hh
src/ds++/test/tstQuery_Env.cc

* I want to use the `get_env_val` function without including all of the SLURM info.
+ Pull `gen_env_val` out of `c4/QueryEnv.hh` and into a new file `ds++/Query_Env.hh`.
+ Rename `c4/QueryEnv.hh` to `c4/SLURM_Task_Info.hh`.
+ Add a unit test for `ds++/Query_Env.hh`.
+ Update include directives as needed.
+ I also included two one-line fixes to the build system that I needed during the most recent release.  
+ In `configureFileOnMake.cmake`, use a hack to correctly set `DOXYGEN_HTML_DYNAMIC_MENUS` in `doxygen_config`.  This will eliminate a build warning that occurs for the `make autodoc` rule.
+ In `dracoVersion.cmake`, ensure that the _patch_ version is saved to the `CMakeCache.txt`. This should fix an annoyance related to releases where the patch version is always listed as the build …

Split QueryEnv into Query_Env and SLURM_Task_Info for better reuse.

---

config/vendor_libraries.cmake
src/diagnostics/CMakeLists.txt
src/diagnostics/Timing.hh
src/diagnostics/config.h.in
src/diagnostics/test/tstTiming.cc

* Caliper is a useful timing and diagnostics library
* Change existing Draco timing macros to allow either old-school Draco timing or exciting new Caliper.
* Add a `find_package` to the build system to find Caliper.
* When Caliper is available, Draco timing macros are switched over to Caliper timing macros.
* When Caliper is not available, Draco timing macros use Draco Timing diagnostics.
* Reference:
* Checks

Feature Add Caliper

---

.github/workflows/linter.yml

* Attempt to enable new GitHub linter tool, https://github.com/github/super-linter
* Reference:
* Checks

Enable github super-linter

---

src/diagnostics/Timing.hh

* In adding Caliper capability, neglected to update the case where DRACO_TIMING is on but Caliper is not used.
* Update macros for the case where DRACO_TIMING is on but Caliper is not used.
* Add argument (unused) to `TIMER_START` and `TIMER_END` so signatures are consistent in all cases.
* Reference:
* Checks

Fix timing macros for Draco diagnostics timing case.

---

config/component_macros.cmake
src/device/config.h.in
src/ds++/Assert.hh
src/ds++/config.h.in
src/rng/test/CMakeLists.txt

* Code compiled on the GPU currently sees the preprocessor variable `USE_CUDA` but CPU code that sees GPU code or conditionally calls GPU code also needs to see if `USE_CUDA` is set. To this end, I've added `USE_CUDA` back to the config files in draco. I've also hid a few DBC macros that are used on the GPU behind an `if defined(USE_CUDA) && defined(__NVCC__)` instead of just a `USE_CUDA` check. This makes sure that the CPU does not end up with GPU versions of the DBC calls.
* Needed to get `mcgrid` tests passing with GPUs in Jayenne
* Remove CMake commands that add "USE_CUDA" to compile line
* Wrap some macros in "__NVCC__" to ensure they are only processed by the NVCC compiler
* Reference:
* [CDash …

Add "USE_CUDA" preprocessor definition to config file

---

src/viz/test/tstEnsight_Stream.cc

* TstEnsight_Stream had a couple of small possible issues with resource contention
* Append number of procs to test output to prevent multiple instances of tstEnsight_Stream from writing to the same file simultaneously
* Add a global barrier between "serial" (rank 0 only) and parallel calls to test_simple to let rank 0 finish its write/read before the parallel calls access the same file.
* see above :)
* Reference:
* Checks

Minor fix to tstEnsight_Stream

---

config/FindCaliper.cmake
config/draco-config-install.cmake.in
config/vendor_libraries.cmake
environment/bashrc/.bashrc_cray
environment/bashrc/.bashrc_cts1
src/diagnostics/CMakeLists.txt

+ We recently added optional support for using LLNL's Caliper library. There were a few unexpected issues related to exporting the new dependency.  This PR addresses this issue and provides other related cleanup.
+ Provide a new cmake `find_package` helper `FindCaliper.cmake`.  This allows us to create a `CALIPER::caliper` cmake target that knows about library and include file locations for the vendor.
+ Use the new `FindCaliper.cmake` features to simplify code in `vendor_libraries.cmake` and in `diagnostics/CMakeLists.txt`.
+ For LANL HPC machines, load caliper as part of Draco's default developer environment.
+ When generating the export targets (e.g.: `draco-config.cmake`), ensure that client projects find and define the imported target `CALIPER::caliper` correctly.
* Reference:
* …

DevEnv, build, export improvements for Caliper.

---

config/setupMPI.cmake
environment/bashrc/.bashrc
environment/bashrc/.bashrc_cray
tools/ats1-env.sh
tools/cts1-env.sh
tools/release.sh

* During the recent release cycle, @jhchang-lanl and @KineticTheory discovered some developer and release environment settings that needed to be updated.  This change-set fixes those items.
+ Make the `.bashrc` system more robust on Darwin by always sourcing the setup files.
+ Use `cmake/3.17.2` on Trinitite
+ For releases, disable loading quo when using `intel/17.0.4` on trinitite (it doesn't exist).
+ For releases, also provide a release folder based on `gcc/7.4.0`.
+ Fix script error related to the patch version number printed by `draco_info`.
* Reference:
* Checks

Minor environment cleanup

---

config/draco-config-install.cmake.in

* PR #865 installed a broken `draco-config.cmake` that broke downstream projects.
* I chose to call Draco's setup macros to define the import target `CALIPER::caliper`, but I forgot to tell `draco-config-cmake` to `include(vendor_libraries)`.  This is required to bring the `setupCaliper` macro into scope.
* Reference:
* Checks

Fix broken cmake code introduced in PR 865

---

environment/bashrc/.bashrc
src/CMakeLists.txt
src/cdi_ndi/CMakeLists.txt
src/cdi_ndi/NDI_AtomicMass.cc
src/cdi_ndi/NDI_AtomicMass.hh
src/ds++/Index_Set.hh
src/linear/gaussj.i.hh
src/linear/ludcmp.i.hh
src/linear/qrdcmp.i.hh
src/linear/test/tstqrdcmp.cc
src/linear/test/tstqrupdt.cc
src/linear/test/tstsvdcmp.cc
src/memory/memory.cc
src/memory/memory.hh
src/memory/test/tstmemory.cc
src/mesh_element/Element_Definition.cc
src/mesh_element/Element_Definition.hh
src/mesh_element/test/TestElementDefinition.cc
src/ode/Function_Traits.hh
src/ode/quad.i.hh
src/ode/rkqs.i.hh
src/ode/test/tstquad.cc
src/units/PhysicalConstexprs.hh
src/units/UnitSystemEnums.hh
src/units/UnitSystemType.cc
src/units/UnitSystemType.hh
src/units/test/tstFundUnit.cc
src/units/test/tstUnitSystem.cc
src/units/test/tstUnitSystemEnums.cc
src/units/test/tstUnitSystemType.cc

* Process four additional components with _clang-tidy_ code transformation recommendations and add these packages to the nightly regression that processes _clang-tidy_.
* Provide updates for mesh_element, ode, linear, and memory components.
* Transform `typedef` to `using` commands.
* Make use of `auto` when the data type is specified on the RHS with a `static_cast`.
* Use `<cmath>` instead of `<math.h>`
* Use `std::array` instead of C-style arrays. 
* https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-stack
* https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#slcon1-prefer-using-stl-array-or-vector-instead-of-a-c-array
* When possible, use C++14 style range-based for-loops.
* Big changes in mesh_element take advantage of new C++14 …

Provide clang-tidy recommended changes

---

src/device/config.h.in

* I'm using CUDA constant memory for our random walk data tables in the Jayenne GPU port (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#constant).  This requires the `__constant__` decorator for arrays that will be placed in constant device memory. This PR adds a macro that returns `__constant__` when compiling for the GPU and `constexpr` for the CPU. Functions that use constant memory generate a warning if the function is marked `__host__` `__device__` which is what I've used for all functions thus far so I added a macro for just the `__device__` decorator.
* Allow use of CUDA constant memory
* Add GPU_DEVICE macro for `__device__` only decorator in GPU builds
* Add CONSTANT macro for `__constant__` memory decorator in GPU builds
* Use `constexpr` for CONSTANT in host …

Add two macros for GPU builds

---

src/CMakeLists.txt
src/linear/btridag.i.hh
src/linear/ludcmp.i.hh
src/linear/ludcmp_pt.cc
src/linear/svbksb.i.hh
src/linear/tred2.hh
src/linear/tred2.i.hh
src/linear/tred2_pt.cc
src/ode/CMakeLists.txt
src/ode/test/CMakeLists.txt
src/ode/test/tstFunction_Traits.cc
src/ode/test/tstquad.cc

* PR #869 added several more directories to the clang-tidy night regression.  While these packages were mostly free of warnings, 6 new ones were reported.  This follow up PR addresses these new warnings.
+ Most of these changes are simply replacing `typedef` with `using`.
+ Remove a possible namespace injection.
+ Remove redundant `DLL_PUBLIC_*` decoration.
+ Make use of `UT_MSG` in simple unit tests.
* Reference:
* Checks

Clean up clang-tidy warnings that were missed in #869

---

src/c4/C4_Functions.hh
src/c4/C4_MPI.cc
src/c4/C4_Req.hh
src/c4/C4_Serial.cc
src/c4/test/tstsend_is.cc

* In the parMETIS local redecomposition implementation I'm working on, I need to be able to access a list of source ranks that have sent me data. Adding this wait_all_with_source call accomplishes that.
* add needed MPI functionality to c4, including dummy functions for serial case
* Modify MPI send test to exercise the new function
* see above :)
* Reference:
* Checks

Add a wait_all call to c4 that returns the source rank ID for MPI comms

---

src/c4/test/tstsend_is.cc
src/ds++/config.h.in

+ The `restrict` keyword behaves a little differently in the latest MSVC.  Make a CPP adjustment to keep builds working.
+ The new MSVC also starting warning on a integral type conversion that I fixed with a `static_cast`.
* Reference:
* Checks

Minor compatibility update for MSVC 2019 16.7.0 Preview 4.0

---

.github/workflows/linter.yml

* Attempt to fix 'failed' email report when PR doesn't touch any script files.
* Ref: https://github.com/github/super-linter/issues/422
* Reference:
* Checks

Upgrade super-linter from 2.1.0 to 3.3.1

---

config/compilerEnv.cmake

* We need the ability to disable compilation with CUDA even when _nvcc_ is found in the build environment.
* [Fixes Redmine Issue #2083](https://rtt.lanl.gov/redmine/issues/2083)
* Do not set `CUDA_DBS_STRING`  or `COMPILE_WITH_CUDA` cmake variables unless `(HAVE_CUDA AND USE_CUDA)` is true.
* No need to set CUDA compiler flags if cuda is disabled.
* Reference:
* Checks

Fix USE_CUDA=OFF logic so that Cuda is actually disabled.

---

environment/git/pre-commit-clang-format

* Allow clang-format other than version 6.0 to work as a git commit hook.
* Reference:
* Checks

Fix clang-format version issue.

---

src/cdi_CPEloss/Analytic_CP_Eloss.cc
src/cdi_eospac/test/tEospac.cc
src/diagnostics/qt/diWidget.cc
src/diagnostics/qt/diWidget.hh
src/diagnostics/qt/main.cc
src/diagnostics/qt/mainwindow.hh
src/diagnostics/test/tstTiming.cc
src/meshReaders/Hex_Mesh_Reader.cc
src/min/test/tstmrqmin.cc
src/parser/Parse_Table.hh
src/parser/test/tstAbstract_Class_Contextual_Parser.cc
src/parser/test/tstAbstract_Class_Parser.cc
src/parser/test/tstExpression.cc
src/roots/test/tstzbrac.cc
src/roots/test/tstzbrent.cc

+ The clang-tidy builds on my local machine report a slightly different set of issues compared the CI system. Fix the items that are still reporting warnings.
+ Note: the `diagnostics/qt` sources weren't checked previously.
* Reference:
* Checks

Apply clang-tidy recommendations in a few more places

---

src/cdi_CPEloss/Analytic_Constant_Eloss_Model.hh
src/cdi_CPEloss/test/tstAnalytic_CP_Eloss.cc

* It would be nice to have zero and infinite stopping power models for CPT for testing purposes. This has also been requested by other developers to facilitate cross-code comparisons.
* Add a constant analytic stopping power model to be used to construct zero, ~infinite stopping powers.
* [Fixes Redmine Issue #2089](https://rtt.lanl.gov/redmine/issues/2089)
* Add `cdi_CPEloss/Analytic_Constant_Eloss_Model.hh` which takes a constant stopping power value as an argument in the constructor and returns this value when used to evaluate a stopping power.
* Reference:
* Checks

Constant analytic stopping power model

---

environment/bashrc/.bashrc_ats2
environment/bashrc/.bashrc_cray
environment/bashrc/.bashrc_cts1

+ Provide two additional variables that will aid developer who are working on `ccsrad-next` branches.  These variables help us keep a sane spack setup.
* Reference:
* Checks

Augment Draco developer environment for CTS-1 and ATS-1.

---

config/setupMPI.cmake
environment/bashrc/.bashrc_darwin_fe

* TPLs on darwin were updated. Some TPL versions were advanced.
* Add more options to the Spectrum-MPI `mpirun` command.
+ For the gcc environment, bump to `cuda/11`, `cmake/3.17.3`, and `superlu-dist/5.4.0`. Add caliper.
+ Rework spectrum-mpi arguments and associated cmake logic.
+ For SMPI on darwin, use options `-intra sm -aff off --reort-bindings`.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=`1&showfilters=1&field1=buildname&compare1=63&value1=-pr)
* Checks

Update darwin p9 environment and spectrum-mpi args.

---

src/parser/test/tstutilities.cc
src/parser/test/utilities.inp
src/parser/utilities.cc

* We occasionally see jerk = 1 gigajoule and shake = sh = 10 nanoseconds as units. It would be nice to support these in the Draco unit parser.
* Add sh, shake, and jerk as recognized units in unit parser.
* Reference:
* Checks

Add jerk, sh==shake as unit names in unit parser.

---

src/cdi_eospac/test/tEospacWithCDI.cc

* CDash is reporting two clang-tidy warnings.  Fixed 'em.
* I also re-wrapped the comment blocks to be 80 cols.
* Reference:
* Checks

Fix clang-tidy warning in tEospacWithCDI.cc

---

config/setupMPI.cmake
config/unix-cuda.cmake
environment/bashrc/.bashrc_ats2
environment/bashrc/.bashrc_linux64
src/c4/test/CMakeLists.txt
src/c4/test/tstOMP_API_on.cc

* Tests were running about 100X too slow on rzansel because the test launcher wasn't configured correctly.
* [Fixes Redmine Issue #1945](https://rtt.lanl.gov/redmine/issues/1945)
* [Fixes Redmine Issue #1933](https://rtt.lanl.gov/redmine/issues/1933)
+ Switch back to `lrun --pack` for launching jobs on ATS-2.
+ Set lrun as the default launcher for ATS-2.
+ In the Draco developer environment for ATS-2, make `cuda/11.0.2` the default.
+ Ensure that the c4 tests `tstOMP_API_off` and `tstOMP_API_on` are registered as having OpenMP enabled. In the `_on` test, change the test to use 39 OpenMP threads instead of 51.  ATS-2 throws an error if more than 40 threads are requested.
* Reference:
* [CDash …

More updates to support testing and regression on ATS-2.

---

src/c4/xthi_cpuset.hh

* Some functions in c4/xthi_cpuset.hh have external linkage; this leads to multiple definition errors.
* make functions have internal linkage
* [Fixes Redmine Issue #2127](https://rtt.lanl.gov/redmine/issues/2127)
* mark function definitions `inline`
* Reference:
* Checks

Mark functions defined in header inline to change to internal linkage

---

environment/bashrc/.bashrc_ats2

* There were some weird permissions issues related _workspace_ locations on rzansel and sierra.  This change fixes those issues.
* Reference:
* Checks

Fix TF_ environment for rzansel and sierra

---

environment/bashrc/.bashrc
environment/bashrc/.bashrc_ccsnet

* move to new spack provided TPL installations and modules.
* Update the `.bashrc` for ccs-net machines so that modules and vendors located at `/ccs/opt/vendors/spack.20200429`
* Provide and use new 'super'-modules that live at `/ccs/codes/radtran/draco`
* Reference:
* Checks

New vendor locations for ccs-net

---

src/c4/test/tstReduction.cc

* Fixes a test that started diffing with `gcc/9.3.0`. The behavior of gcc/9.3.0 is not what I'd expect but I don't care to look into it further.
* Fixes failing tests (https://rtt.lanl.gov/cdash/viewTest.php?onlyfailed&buildid=68633)
* Static cast the `std::numeric_limits<int>::max()` to a uint32_t type to avoid unexpected behavior
* Static cast the `std::numeric_limits<int64_t>::max()` to a uint64_t type to avoid unexpected behavior
* Reference:
* Checks

Make type conversions explicit when testing large ints

---

environment/bashrc/.bashrc
environment/bashrc/.bashrc_ccsnet
environment/bashrc/bash_aliases.sh
environment/bashrc/bash_functions.sh

+ Add alias for connecting to `rzansel` and `sierra`.
+ Add alias `mica` for `module --ignore_cache avail`.  This is useful on CTS-1 as we transition to a new user_contrib stack.
+ Update debug statements and copyright dates.
* Reference:
* Checks

Minor update to draco-developer bash files.

---

environment/bashrc/.bashrc_ats2
environment/bashrc/.bashrc_cts1
environment/git/pre-commit-f90-format
environment/lmod/README.lmod
environment/lmod/sample.lmodrc.lua
environment/lmod/sample.modulerc.lua

* Trying to keep our environments working on ATS-2 and CTS-1.
+ On ATS-2 systems, move to `python/3.8.2`.
+ On CTS-1 systems, make the module setup scripting more generic so that it works properly on fire/ice.
+ Improve the robustness of our f90-format checker that can be installed in the git hooks directory.  If _emacs_ isn't found, don't fail, just print a warning and skip the check.
+ Provide sample lmod config files.
* Reference:
* Checks

Minor developer environment updates.

---

CMakeLists.txt
config/platform_checks.cmake
config/vendor_libraries.cmake

* A logic error related to discovery of Cray compile wrappers in `platform_checks.cmake` could lead to a configuration failure when building under spack.
* Fixes #900 
* ~~Convert `SPACK_ROOT` to canonical form.~~
* Remove `query_craype` check as superfluous.
* This check was helpful we we were still learning how to build and run on Cray machines, but isn't really that helpful now and gets in the way when building TRT codes via spack.
* Reference:
* Checks

Fix a CrayPrg + spack configuration logic issue

---

config/compilerEnv.cmake
config/unix-clang.cmake
src/VendorChecks/test/tstMetis.cc

+ There was a bug in how we set compiler flags for clang that was causing the clang-tidy regression to fail with the error `clang-9: error: no input files`.   This was caused by an unexpected semicolon in the list of compiler flags.
+ Error shown on cdash for `clang-9.0.0-clangtidy_Debug-develop`.
* [Fixes Redmine Issue #2165](https://rtt.lanl.gov/redmine/issues/2165)
+ Cleaning up the logic used to set compiler flags fixes this issue.
- Use `string` instead of `list` to append compiler flags.
- Deduplicate the list of compiler flags.
- Ensure that flags set in the environment or as cmake options are captured.
+ Provide two new cmake functions to reduce cmake code duplication.
+ Process `tstMetis.cc` for 100-column formatting.
* Reference: …

Fix the clang-tidy regression failure.

---

.flake8
.github/workflows/linter.yml
config/setupMPI.cmake

* We are trying to debug openmpi run failures on ccs-net.  Howard asked that I add `--debug-daemons` to our run line.  Unfortunately, this generates a lot of output and seems to destabilize some of our regressions, so I'm reverting this change.
+ We are also in the process of using more static analysis (lint) tools.
+ Remove the `--debug-daemons` command line parameter for OpenMPI's `mpiexec` command.  This seems to be causing some issues for regressions even though Howard Pritchard wants to see the debug output from OpenMPI when our tests fail.
+ Adopt Spack's `.flake8` formatting rules for python style checks.
+ Update the superlinter configuration file to use `.flake8`. Also make another stab at setting `FILTER_REGEX_EXCLUDE` for `.cc` files.  I'm having trouble getting this right.
* …

Remove openmpi debug-daemons option.

---

src/c4/test/CMakeLists.txt

* This test fails to run under valgrind due to a hwloc API conflict between openmpi and libquo.  Disable for now.
* Might be fixed by moving to openmpi@4, but openmpi@4.0.3 has other issues that cause multiple regression failures.
* Might be fixed by using internal hwloc linkage in openmpi, but this build variant isn't available from [spack yet](https://github.com/spack/spack/pull/19109).
* [Fixes Redmine Issue #2163](https://rtt.lanl.gov/redmine/issues/2163)
* Reference:
* Checks

Disable tstQuoWrapper_4 unit test from running under valgrind.

---

src/CMakeLists.txt
src/viz/Ensight_Stream.cc
src/viz/Ensight_Stream.hh
src/viz/Ensight_Translator.cc
src/viz/Ensight_Translator.hh
src/viz/Ensight_Translator.i.hh
src/viz/Viz_Traits.hh
src/viz/test/tstEnsight_Stream.cc
src/viz/test/tstEnsight_Translator.cc
src/viz/test/tstEnsight_Translator_Unstructured.cc
src/viz/test/tstViz_Traits.cc

+ Add the viz component to the list of packages checked nightly by clang-tidy.
+ Initialize class data when declared when possible instead of using default initializer in the constructor.
+ Use `std::make_unique` instead of `reset` for shared_ptrs.
+ Use `nullptr` instead of `NULL`
+ Use range-based for-loops when possible.
+ Only use `std::endl` at the end of a composed iostream/string.
+ Make use of `using` instead of `typedef`.
+ Implement `std::move` in constructors in place of pass by reverence and then copy.
+ Replace c-style arrays with `std::array`.
* Reference:
* Checks

Apply clang-tidy transformations to 'viz'

---

src/cdi_ndi/CMakeLists.txt
src/cdi_ndi/NDI_AtomicMass.cc
src/cdi_ndi/NDI_AtomicMass.hh
src/cdi_ndi/NDI_Base.cc
src/cdi_ndi/NDI_Base.hh
src/cdi_ndi/NDI_TNReaction.cc
src/cdi_ndi/NDI_TNReaction.hh
src/cdi_ndi/config.h.in
src/cdi_ndi/test/CMakeLists.txt
src/cdi_ndi/test/tstNDI_AtomicMass.cc
src/cdi_ndi/test/tstNDI_TNReaction.cc

* Cleaning up the code base for the 100 column format.
* No code changes.
* Processed files with clang-format wrapping at 100 cols.
* Manually processed files to rewrap comment blocks at 100 cols.
* Reference:
* Checks

Process ndi_cdi with clang-format at 100 columns

---

config/CMakeAddFortranSubdirectory.cmake
config/unix-gfortran.cmake
src/c4/fc4/CMakeLists.txt

+ After #939 modified how compiler flags are set, the CAFS specific compiler flag manipulation no longer worked as originally designed.
* Fixes #945
+ Tweak how Fortran_FLAGS are modified for CAFS-gfortran builds under MSVC so that `-fno-range-check` is correctly specified.
+ Remove check for too old a version of gfortran.
+ Apply 100 column formatting update for these cmake files.
* Reference:
* Checks

Fix Fortran Flags used by MSVC+CAFS build.

---

environment/bashrc/.bashrc_ats2

* These functions are no longer needed.  Use the _draco_ super-modules instead.
* Fixes a problem caused by setting `OMP_NUM_THREADS`.
* Reference:
* Checks

Do not use dracoenv functions for ATS2.

---

config/CMakeAddFortranSubdirectory.cmake
config/compilerEnv.cmake

* #946 fixed the Debug build, but this issue also shows up in the Release build.
* Use compile option `-fno-range-check` to suppress this warning/error.
* Reference:
* Checks

Another fix for gfortran based MSVS-CAFS build.

---

.travis.yml
tools/Dockerfile-autodoc.txt
tools/Dockerfile-basic.txt
tools/Dockerfile-codecov.txt
tools/Dockerfile-spack-common-tools.txt
tools/Dockerfile-spack-gcc.txt
tools/Dockerfile-spack-llvm.txt
tools/Dockerfile-spack-setup.txt
tools/Dockerfile-style-checks.txt
tools/README.docker
tools/check_style.sh
tools/mirrors.yaml
tools/modules.yaml
tools/packages.yaml
tools/travis-run-tests.sh

* Testing new docker images that are used by the Travis-based CI system.  Use different images based on the requirements of each CI configuration (autodoc, style-check, gcc-mpi, gcc-scalar).
* Update to Ubuntu 20.04
* Update to gcc-9.3.0 and openmpi-3.1.6
* Add caliper
* The main issue with the older test setup was that clang-format was too old.  Moving from version 6 to 10.
* The old system also lacked caliper.
* Paves the way for adding LLVM-based CI testing.
* Provide a new set of docker files and README that details how the images are created.
* Tweaks to the `travis.yml` file and the main `travis-run-tests.sh` script.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1& …

Test new CI system and associated docker image.

---

config/doxygen_config.in
src/c4/C4_MPI.hh
src/c4/C4_Req.hh
src/c4/C4_Serial.hh
src/cdi_CPEloss/Analytic_CP_Eloss.cc

+ C4 is designed so that `c4/global.hh` or `c4/C4_Functions.hh` should be called instead of `c4/C4_MPI.hh` or `c4/C4_Serial.hh`.  Update the headers to enforce this inclusion model.
+ Remove some redundant include directives from c4.
+ Force the CPP macro `C4_MPI=1` for doxygen builds.  This provides the correct file-to-file hyperlinks.
+ Fix a clang-tidy warning issued from `Analytic_CP_Eloss.cc` and rewrap the comment blocks to 100 columns.
* Reference:
* Checks

Provide a build error if C4_MPI.hh is included directly.

---

src/ds++/Assert.hh

* nvcc_wrapper preprocesses everything with nvcc. As such, any cpu code that includes the previous version of Assert.hh and uses Insist was getting the version intended for device code. This causes API breaks when compiling with the wrapper were strings are generally passed to this function in most cpu code.
* Add another macro that is explicitly for use in device code until kokkos developers fix the wrapper.
* One will find general replacement of __NVCC__ with __CUDA_ARCH__ which was thought to correct the issue before we fully understood what the root cause was. However this change remained as it is more general.
* Added the Insist_device macro which is an alias to no_exception_insist and is only for use in device code.
This was tested by hand when in a build context and we also tested …

Nvcc wrapper support

---

config/autodoc_macros.cmake
config/compilerEnv.cmake
config/component_macros.cmake
config/vendor_libraries.cmake
src/parser/test/CMakeLists.txt

+ I am adopting a technique used in CSK.  If valgrind is available and `-DENABLE_MEMEORYCHECK=ON`, then register each unit test twice: (1) the regular `<test>` and (2) `memcheck_<test>`.  The latter test will run `<test>` under valgrind.  All `memcheck` tests will be have the test label `memcheck`.
+ Documented at https://rtt.lanl.gov/redmine/projects/draco/wiki/Common_Configure_Options.
+ This update was needed to allow Jayenne valgrind runs in gitlab setuid runners.
+ Preferred use is:
```
cmake -DENABLE_MEMORYCHECK=ON
-DCTEST_MEMORYCHECK_SUPPRESSIONS_FILE=/scratch/regress/ccsradregress/valgrind_suppress.txt
```
+ `CMAKE_MEMORYCHECK_COMMAND` and `CMAKE_MEMORYCHECK_COMMAND_OPTIONS` can also be set on the cmake line, but reasonable defaults will be used if omitted.
+ If enabled `ctest -N` …

Make it easier to enable valgrind tests.

---

environment/bashrc/bash_functions.sh

* Attempting to address the super-linter warnings for our bash sources resulted in a couple of broken features.  This PR undoes one of those fixed and restored the correct code behavior related to using `~ == $HOME` in the prompt.
* Reference:
* Checks

Undo another overzealous linter fix that broke behavior.

---

src/ds++/Assert.hh
src/ds++/test/tstAssert.cc

* Introducing a new insist specifically for device code helped the NVCC kokkos wrapper compile draco. This PR just cleans up a few issues with the `Insist_device` function--it's added to the other DBC modes (hard to see in Draco's `Assert.hh` since preprocessor logic is not indented).
* Improve on device insist macros
* Make a clearer distinction between non-throwing insists
* Define Insist_device in other DBC modes to be standard insist
* Fix the last fall through check in `Assert.hh` that checked if `Insist` was defined instead of `Insist_device`
* Reference:
* Checks

Fix device insist issues

---

src/device/test/Dual_Call.cu
src/ds++/Assert.hh

* This should be the last PR for the `Insist_device` change. This adds an `Insist_device` call to a test in `src/device/test` and adds a newline to the end of the printf in `no_exception_insist`.
* Clean up the `Insist_device` function
* Add an Insist_device call to Dual_Call.cu
* Add a newline character to the end of the printf in no_exception_insist
* Reference:
* Checks

Use the Insist_device function in device test code

---

autodoc/CMakeLists.txt
config/autodoc_macros.cmake
config/component_macros.cmake
config/doxygen_config.in
config/draco-config-install.cmake.in
environment/bashrc/.bashrc_ccsnet
environment/bashrc/.bashrc_cray
environment/bashrc/.bashrc_cts1
environment/bashrc/.bashrc_rfta
environment/bashrc/sample.bash_profile

* Clean old code that I needed to work through recently.
+ Simplify bashrc files.
- For ccs-net, move more environment into the module system.
- For ATS-1 and CTS-1, improve logic used to set `TF_DEPLOYMENT_CLONES` and `TF_SPACK_INSTANCES`. Also remove some deprecated setup code.
- For redcap/fta machines, don't try to load modules that have been removed.
+ Build system files.
- Re-wrap CMake scripts for `autodoc` to 100 cols.
- Add a `RUN_SERIAL` option for `add_[scalar]_test`.
- When installing Draco, save extra data to `draco-config.cmake`: `DRACO_TIMING`,  `DRACO_DIAGNOSTICS`, and `DRACO_STATIC_ANALYZER`.
* Reference:
* [CDash Status](https://rtt.lanl.gov/cdash/index.php?project=Draco&filtercount=1&showfilters=1& …

More environment and build system updates.

---

src/c4/ParallelUnitTest.cc

* Remove a debug print that might be causing false positive failures.
* Reference:
* Checks

Remove debug print.

---

src/compton_tools/cskrw.cc

* Fix compile warning issued by gcc on Power9 and ARM architectures.
```
/projects/gitlab-runner/jayenne/jayenne/builds/users/kellyt/Hu51Ct7C/2/jayenne/jayenne/draco/src/compton_tools/\
cskrw.cc: In member function 'void Dense_Compton_Data::read_from_file(UINT64, std::string, bool)': 
/projects/gitlab-runner/jayenne/jayenne/builds/users/kellyt/Hu51Ct7C/2/jayenne/jayenne/draco/src/compton_tools\
/cskrw.cc:221:26: error: comparison is always false due to limited range of data type [-Werror=type-limits]
221 |       if (c == '\n' || c == EOF) {
|                          ^
```
* Remove 2nd part of the conditional since it is always `False`.
* Reference:
* [CDash …

Fix a build warning issued by gcc on ARM and Power9.

---

config/vendor_libraries.cmake

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
* The flag application's spack environment was not building with some combinations of compilers/cpu arch/qt installs owing to issues with QT's moc not working right.
* enable optional use of QT package - some compiler/QT install/archs don't work. 
* Reference:
* Checks

CMAKE: add option to not use QT

---

src/cdi_ndi/NDI_CP_Eloss.cc
src/cdi_ndi/NDI_CP_Eloss.hh

* #844 was merged in without waiting for the CI, and now there are some warnings-treated-as-errors in `develop`. This attempts to fix that
* Fix LLVM warnings
* Decorate `NDI_CP_Eloss` member functions with `override` where appropriate.
* Add DBC for `ndi_error`from an NDI call.
* Reference:
* Checks

Fix CI issues related to recent NDI stopping power PR

---

src/c4/C4_Functions.hh
src/c4/C4_MPI.t.hh
src/c4/C4_MPI_reductions_pt.cc
src/c4/C4_Serial.t.hh
src/c4/test/tstReduction.cc
src/cdi_ndi/NDI_Base.cc
src/cdi_ndi/NDI_Base.hh
src/cdi_ndi/NDI_TNReaction.cc
src/cdi_ndi/NDI_TNReaction.hh
src/compton_tools/Compton_Native.cc
src/ds++/DracoStrings.cc
src/ds++/DracoStrings.hh
src/ds++/test/tstDracoStrings.cc

+ This started out as a fix to some code flagged by clang-tidy.  I ended up changing additional code as a result.  All changes are minor and should not change behavior (minus a bug fix for `trim`).
+ Add an overload of `global_sum` that takes a `size_t` as the array size.  This eliminates the need to downcast `size_type` to an `int`. Provide unit tests of this overload.
+ The `trim` function in `DracoStrings` had a minor deficiency that needed to be accounted for.  Previously, if the string passed to this function was a c-style string with null termination, the string was not trimmed correctly. Unit tests were added to check the new functionality.
+ `Compton_Native.cc` was updated to use a range-based for-loop.
+ `cdi_ndi` was updated with these fixes:
- use `std::move` in constructors …

Clang tidy fixes and more.

---

src/c4/C4_Functions.hh
src/c4/C4_MPI.i.hh
src/c4/C4_Serial.hh

+ This approach is a little easier to parse the the previous solution merged in #979.
+ Also fixes 3 clang-tidy issues.
* Reference:
* Checks

Provide an alternate implementation for global_sum

---

config/FindNDI.cmake
src/cdi_ndi/config.h.in

* Update build system to scrape NDI version and save it to `cdi_ndi/config.h`.
* Produces something like this:
```c++
#define NDI_VERSION_STRING "2.2.0alpha"
#define NDI_MAJOR "2"
#define NDI_MINOR "2"
```
* Note that NDI itself defines:
```
#define NDI_VERSION_DATA "2.2.0alpha"
...
```
* We must be careful to avoid symbol collision.
* Reference:
* Checks
* WIP

Save ndi version to cdi_ndi/config.h

---

config/FindNDI.cmake
src/cdi_ndi/NDI_Base.cc
src/cdi_ndi/NDI_CP_Eloss.cc
src/cdi_ndi/NDI_CP_Eloss.hh
src/cdi_ndi/config.h.in

* NDI added stopping power support with 2.2.0alpha, which we want to use if possible.
* Hide macros added with NDI 2.2.0alpha behind preprocessor logic
* [Fixes Redmine Issue #2285](https://rtt.lanl.gov/redmine/issues/2285)
* Changed `NDI_MAJOR` and `NDI_MINOR` in `config.h` to integers from strings to facilitate comparisons.
* `load_ndi()` fails if `NDI_MAJOR`, `NDI_MINOR` indicate insufficient support.
* Reference:
* Checks

Disable NDI stopping powers if NDI version < 2.2.x

---

environment/bashrc/.bashrc_vm

* In preliminary building testing on a VM, it was noticed that sourcing the bashrc does not load modules.
* Load modules in .bashrc_vm
* Load modules set in the `dracomodules` variable in .bashrc_vm
* Load git as well.
* Reference:
* Checks

Load modules in .bashrc_vm.

---

config/CMakeLists.txt
config/draco-config-install.cmake.in

+ Previous logic was broken but harmless. Newer versions of cmake are now issuing warnings about this broken logic.  Previously, a list of build types was saved to the list `CMAKE_CONFIGURATION_TYPES`, but this list cannot be known at configure time and construction  must be delayed until `find_package(draco)` is called.
+ This change only affects multi-config build tools like Visual Studio.
* [Related to Redmine Issue #2096](https://rtt.lanl.gov/redmine/issues/2096)
+ Also fix some 100 column wrap formatting.
* Reference:
* Checks

Fix broken logic that sets CMAKE_CONFIGURATION_TYPES.

---

config/setupMPI.cmake
tools/travis-run-tests.sh

+ Teach the build system to look for and use mpirun command options found in the environment variable (or cmake variable) `MPIEXEC_PREFLAGS`.
+ This allows the CI system to call cmake like this:
```
export MPIEXEC_PREFLAGS="--allow-run-as-root --oversubscribe" cmake $source/Draco
```
+ This mechanism can also be used to append other mpirun flags like `--mca btl ^openib` during test registration.
* Reference:
* Checks

Use env/cmake variable MPIEXEC_PREFLAGS to add extra mpirun options.

---

src/rng/Counter_RNG.hh

* In a future PR for Jayenne I've started sourcing particles on the GPU and need to make RNG objects. Previously I only called RNG functions to generate doubles. This PR just adds the decorator for GPUs to the RNG constructor.
* Allow particles to be constructed on the GPU
* Add GPU decorator to the Counter_RNG constructor
* Reference:
* Checks

Make the explicit Counter_RNG constructor available on the GPU

---

config/vendor_libraries.cmake
src/lapack_wrap/CMakeLists.txt
src/lapack_wrap/test/CMakeLists.txt

+ CMake's FindBLAS and FindLAPACK were recently updated to produce import targets. Use these new targets instead of the complicated logic that was used previously.
+ This update was tested with netlib-lapack, openblas, and intel-mkl, but additional testing is required to ensure that the new TPL discovery works on HPC systems that may have slighlty different LAPACK installations.
* [Fixes Redmine Issue #2027](https://rtt.lanl.gov/redmine/issues/2027)
* Reference:
* Checks

Update the build system to use new cmake FindLAPACK features.

---

config/apple-clang.cmake

* `apple-clang` config file has stray period that causes configuration to end in error.
* Restore apple / Clang cmake configuration!
* Remove period (.) 
* Reference:
* Checks

Remove trailing period in config file

---

config/draco-config-install.cmake.in

* Pull request #990 introduced a bug that broke Makefile-based projects.  
* `CMAKE_CONFIGURATION_TYPES` must only be set for CMake projects that support multi-config builds (not Makefiles).
* Reference:
* Checks

Bug fix: CMAKE_CONFIGURATION_TYPES should not be set for Makefiles

---

config/unix-g++.cmake
src/CMakeLists.txt
src/ds++/terminal/terminal.h
src/experimental/mdspan
src/rng/Counter_RNG.hh
src/rng/test/CMakeLists.txt
src/rng/test/kat_main.h
src/rng/test/time_serial.cc
src/rng/test/ut_carray.cpp
src/rng/test/ut_uniform.cpp
src/rng/test/util_cpu.h
src/rng/uniform.hpp

+ gcc-7 ignores pragmas that silence some for Random123 code.  Add special compiler flags for gcc7 to fix this issue.
+ New xlc++ defines `__clang__`, so replace `#ifdef __clang__` with `#if defined(__clang__) && !defined(__ibmxl__)`.
* Reference:
* Checks

Fix warnings reported by gcc7 and xl16

---

src/c4/test/CMakeLists.txt
src/rng/test/CMakeLists.txt

* Regressions are reporting a couple of annoying errors and warnings.  These are false positives as far as our code is concerned.  
* fixes #1000 
+ Don't run `tstOMP_1` under the coverage build. Collecting the coverage data slows the test down a bit and causes it to fail. This false positive is anoying and the coverage data is already collected for the `_2` case.
+ Use compiler flags to suppress a warning issued by gcc (`-Wexpansion-to-defined`) concerning Random123 code.  Pragmas don't seem to do the trick here.  Limit this flag to the `rng/test` subdirectory.
* Reference:
* …

Fix a couple of regression/CI issues.

---

config/compilerEnv.cmake

* While debugging a different issue, I realized that the value of `DRACO_SHARED_LIBS` that was saved to `ds++/config.h` was corrupt.  I tracked the issue to storing a cmake string into a bool variable.  It is possible that this issue only appeared after we adopted cmake-3.18+, but I didn't try to track it down since the old behavior was wrong.
* Reference:
* Checks

Fix bug in DRACO_SHARED_LIBS CPP macro saved to config.h

---

config/component_macros.cmake
src/parser/test/CMakeLists.txt

+ There was some messy logic in `parser/test/CMakeLists.txt` that I moved into the test registration macros.
+ The `add_[scalar|parallel]_test` macros now accept a new argument `ENV`.
* fixes #959
* Reference:
* Checks

Allow environment sets via add_[scalar|parallel]_test macro.

---

src/cdi_ipcress/python/plot_ipcress_opacity.py

+ Starting with `python@3.5.0`, the python module `matplotlib.backends.backend_tkagg` has a slightly different API.
* [Fixes Redmine Issue #2231](https://rtt.lanl.gov/redmine/issues/2231)
* As per discussion on stackoverflow, I am replacing `NavigationToolbar2TkAgg` with `NavigationToolbar2Tk`.
* I am also replacing the command `show` with `draw` as recommended [here](https://github.com/jarvisteach/appJar/issues/551).
* Reference:
* Checks

Fix plot_ipcress_opacity.py to work with python@3.5+

---

src/cdi_ipcress/CMakeLists.txt
src/compton_tools/CMakeLists.txt

+ Use CMake's `install( PROGRAMS ...)` command instead of `install( FILES ...)` to ensure that the group and world execute bits are set for installed python scripts.
* [Fixes Redmine Issue #2176](https://rtt.lanl.gov/redmine/issues/2176)
* Reference:
* Checks

Ensure installed python programs have the exec bit set.

---

src/kde/kde.cc

* I minor oversight in the original KDE PR. In this PR we replace the math.h import with cmath.
* Reference:
* Checks

change math.h to cmath import in KDE

---

config/setupMPI.cmake

+ While releasing Draco-7_9_0, a couple of tests were spitting out warnings from `lrun`. I worked with LLNL's admins to isolate the issue.  For the updated `lrun`, we need to use `--bind=none` instead of `--pack` in our testing system.
+ I also found a bug related to setting these flags when `OMP_NUM_THREADS` was not set in the developer's environment and provided a fix.
* Reference:
* Checks

rzansel: Tweak SMPI's lrun options for tests that use MPI+OpenMP.

---

config/compilerEnv.cmake
src/RTT_Format_Reader/CellData.cc
src/mesh/Draco_Mesh.cc
src/mesh/Draco_Mesh.hh
src/mesh/Draco_Mesh_Builder.t.hh
src/mesh/test/tstDraco_Mesh_Builder.cc
src/mesh_element/Geometry.hh
src/parser/test/tstutilities.cc
src/parser/utilities.cc
src/quadrature/Galerkin_Ordinate_Space.cc
src/quadrature/Octant_Quadrature.cc
src/quadrature/Ordinate_Set.cc
src/quadrature/Ordinate_Set_Factory.cc
src/quadrature/Ordinate_Space.cc
src/quadrature/Quadrature.cc
src/quadrature/Sn_Ordinate_Space.cc
src/quadrature/test/quadrature_test.cc
src/quadrature/test/tstOrdinate_Set_Mapper.cc

+ Convert `mesh_element`'s `Geometry` into a scoped enum and examine the fallout.
+ Scoped enum help to eliminate variable shadowing (two enums with the same name in the same scope). Most lint programs flag our 'traditional' use of `Enum` as bug-prone.
+ For Draco, the impact is minimal.  Other codes that include Draco headers will need to be evaluated against this PR before merging.
* Reference:
* Checks

Explore the impact of using scoped enum for mesh_element Geometry.
